### ISSUE TITLE
Cross Origin Resource Sharing CORS

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-alb-ingress-controller#1002]
Does it support CORS? I don't see any such annotations as found in nginx ingress controller. Thanks.

**Comment by TiloGit** [comment]
also see #1005

**Comment by khteh** [comment]
CORS works. I use ASP.Net Core and all configurations are done in the application and make use of the platform middleware. Test is done using `curl`. Make sure to set the header when testing. Otherwise there won't be CORS headers in the response.
