### ISSUE TITLE
How to config CORS with ALB?

### ISSUE THREAD

**Issue by anemptyair** [kubernetes-sigs/aws-alb-ingress-controller#1005]
How to config CORS with ALB? 
Like nginx ingress annotations. "nginx.ingress.kubernetes.io/enable-cors"

**Comment by tspycher** [comment]
Same issue/question here! I think adding AWS "API Gateway" in front is a bad idea...

**Comment by log2** [comment]
Same issue here: tried with nginx's enable-cors annotation, with no luck! Is there another way to enable CORS on ALB?

**Comment by ank337** [comment]
is there any way to resolve it ?

**Comment by thestrid3r** [comment]
has anyone find an way around or aws is going to provide a fix in future ?

**Comment by lightsaway** [comment]
Wondering why its closed? Isn't it a good thing to have CORS on ALB instead of putting it on every server?

**Comment by saharanrenu** [comment]
Why they are trying to close the issue without the answer.Thats not the way around to do the work.Btw facing the same issue :( .

**Comment by dailyherold** [comment]
Also interested in keeping this open.

**Comment by dailyherold** [comment]
Also interested in keeping this open.

/remove-lifecycle rotten

**Comment by mailjunze** [comment]
ALB  itself doesn't natively support CORS, therefore, CORS headers need to be added by the backend application.  ALB just  forwards CORS requests to the back-end application as well as forwards CORS responses to the clients. 

Nginx's ingress controller does have a native support for adding CORS headers  which works completely fine with ALB/CLB. https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#enable-cors

**Comment by TapTap21** [comment]
Is this a feature we can request?
