### ISSUE TITLE
Update the AWS Go SDK version to support Web Identity providers for IAM credentials

### ISSUE THREAD

**Issue by barryib** [kubernetes-sigs/aws-alb-ingress-controller#1011]
Update the AWS Go SDK version to support Web Identity providers for IAM credentials

More infos here:
- https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
- https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by devkid** [comment]
See #1017

**Comment by marcincuber** [comment]
When can I expect a new release to happen with OIDC support?

**Comment by M00nF1sh** [comment]
v1.1.3 supports :D
