### ISSUE TITLE
EKS pods is not getting client ip 

### ISSUE THREAD

**Issue by sarath9985** [kubernetes-sigs/aws-alb-ingress-controller#1013]
Requirement: In application pod level, need to see all client ip's.
I tried with type=LoadBalancer and externalTrafficPolicy: Local in local, But it is not working for me.
I've tried with alb ingress and nginx ingress, both also not working.
So, i disabled SNAT also, still my pods not getting client IP.
In load balancer level i can see client IP's.

Every time my pod logs showing source ip, Client Request comes to load balancer then forward to nodeport and forward to pod. Due to this process my pods was getting node ip's only.

I want to see all client ip's in pod logs.

**Comment by genieai-vikas** [comment]
@sarath9985 How did you manage to get the client IP? Even I am facing same issue I am getting node IP
