### ISSUE TITLE
Update ingress controller with the latest AWS SDKs

### ISSUE THREAD

**Issue by jicowan** [kubernetes-sigs/aws-alb-ingress-controller#1015]
The ALB ingress controller is currently using an older version of the AWS SDK that is not compatible with IAM Roles for Service Accounts (IMSA).  Upgrade to https://github.com/aws/aws-sdk-go/releases/tag/v1.23.13 or newer.

**Comment by DZDomi** [comment]
Already noted here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1011

**Comment by devkid** [comment]
See #1017

**Comment by M00nF1sh** [comment]
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1026 done :D
