### ISSUE TITLE
Enhanced certificate auto-discovery produces excessive amounts of acm/DescribeCertificate API calls

### ISSUE THREAD

**Issue by devkid** [kubernetes-sigs/aws-alb-ingress-controller#1021]
Changes made by this pull request:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/commit/dacad85a40d03507086ea40232e6648ffb3ae557
(this is not released yet, only on master)

See my comment here:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/923/files#r324230498

**Comment by M00nF1sh** [comment]
should be solved by https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1025
