### ISSUE TITLE
ingress controller route to external AWS resouces

### ISSUE THREAD

**Issue by alepeltier** [kubernetes-sigs/aws-alb-ingress-controller#1022]
Hello,

I'm working on a project migrating a monolithic application to EKS. We've chosen to use the ALB ingress controller and it works great for routing traffic to our pods.

However, we need to keep the legacy system working. The intended architecture is that /api/ routes to EKS and / routes to the current legacy EC2 instance. I know this is possible with a standard ALB using target groups. I can't find anywhere to set the / rule in the ingress alb as the backend expects serviceName to be present and we're routing to an EC2 outside of EKS. 

I can add the route manually but the ingress controller removes the rule after a while. 

Have I missed something or is it not possible? 

Any help will be appreciated.

**Comment by M00nF1sh** [comment]
@alepeltier It's possible, check out tutorial here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/tasks/migrate_legacy_apps.md

**Comment by alepeltier** [comment]
@M00nF1sh that's exactly what I need. Thank you very much for such a quick response.
