### ISSUE TITLE
Ingress v1.1.3 is calling waf-regional/GetWebACLForResource even though waf annotations are not specified 

### ISSUE THREAD

**Issue by fmmasood** [kubernetes-sigs/aws-alb-ingress-controller#1032]
Controller version: 1.1.3 (not observed in v1.1.2)

I am running Ingress controller inside a private subnet. When  create a new ingress resource with following annotations:

```javascript
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alb-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-11111,subnet-2222
```

in the ingress controller logs I can see following sequence:

```
ec2metadata/GetMetadata
ec2/DescribeSecurityGroups
elasticloadbalancing/DescribeLoadBalancers
elasticloadbalancing/CreateLoadBalancer
elasticloadbalancing/DescribeLoadBalancerAttributes

waf-regional/GetWebACLForResource

```

My question is:

Is it possible to not call <service/Action> unless an annotation is specified ? 
Also note this is not the case in controller v1.1.2.

Thanks

**Comment by M00nF1sh** [comment]
Hi, there is no behavior change around this between v1.1.2 and v1.1.3.
You add an additional arg to controller "--feature-gates=waf=false" to disable waf support.
The reason to query for WAF even if there is no annotation specified is the controller need to clean-up WAF on alb if it's already there.

**Comment by fmmasood** [comment]
Thanks for looking into this @M00nF1sh . Adding additional arg to controller helped.

Is this defaulted to 'false' for version 1.1.2 ? and where can I find a list of all arguments (and their impact)

**Comment by M00nF1sh** [comment]
@fmmasood it's default to true in 1.1.2 too. So i supposed u have that flag in the old controller.
This flag is missing from the docs, but will be supported in future versions too. (need to find some time to update the docs)
