### ISSUE TITLE
Can ALB be shared across multiple cluster?

### ISSUE THREAD

**Issue by manlinl** [kubernetes-sigs/aws-alb-ingress-controller#1033]
We have the need to deploy a service across more than one k8s cluster. Is it possible share the underlying ALB across the clusters?

Many thanks.

**Comment by M00nF1sh** [comment]
currently we don't support it. But ideally it should be possible.
But it need some federated control plane to coordinate information between clusters. (like rule orders)

**Comment by manlinl** [comment]
iiuc, If the controller allows explicitly specifying ALB ARN directly, we can deploy the controller across multiple k8s clusters. Each k8s service resource will be a separated target group added the this ALB.

**Comment by OmriHarary** [comment]
Just wanted to chime in and second this request, we have a major need for it on the horizon.
