### ISSUE TITLE
networking.k8s.io/v1beta1?

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-alb-ingress-controller#1034]
I am using v1.1.3 running on EKS 1.13. Does it support the networking.k8s.io/v1beta1 API version or do we stick to extensions/v1beta1?

**Comment by M00nF1sh** [comment]
Hi, networking.k8s.io is only supported above k8s v1.14. need to find some time to upgrade this controller to networking and convert extensions to networking on client-side for k8s version <=1.14
