### ISSUE TITLE
Service instance mode and IP mode question

### ISSUE THREAD

**Issue by manlinl** [kubernetes-sigs/aws-alb-ingress-controller#1037]
I am curious, in service instance mode (that is using NodePort), are all active nodes in the cluster added to each service' ALB target group, or just those nodes with running service backend pod?

IP mode seems more efficient since NodePort adds another hop. In IP mode, does the controller coordinate with service rolling upgrade. The scenario I worry about is,  when a service is in rolling upgrade, if the controller fails to timely add newly created pod to target group, the service can become completely unavailable. I am curious if you have already a solution for this.   

Many thanks!

**Comment by M00nF1sh** [comment]
Yes, all active nodes will be added to ALB target group. (And these node will proxy traffic to all pods by default).

IP mode cannot achieve 0 downtime deployment, we are going to add support for using pod-readiness gate to solve it.

**Comment by manlinl** [comment]
Make senses. Thanks for the clarification.
