### ISSUE TITLE
Power on EKS auto scaling group via lambda?

### ISSUE THREAD

**Issue by dmarkey** [kubernetes-sigs/aws-alb-ingress-controller#1044]
Hi there, this is just an idea.

We have an EKS cluster that used rarely and needs to be powered on when it's used.

It would be great, somehow that if the ALB notices the target group is empty, that it can execute a lambda function to power on the cluster.

Could it be possible?

**Comment by M00nF1sh** [comment]
Hi,
not sure whether i correctly understand this question.
But yes, ALB publish metrics about targets(e.g. HealthyHostCount) in targetgroup: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html
So ideally you can have alarms on these metrics and send to SNS and triggers lambda, then you can do almost anything inside an lambda function :D
