### ISSUE TITLE
Targets recovery after nodes replacement

### ISSUE THREAD

**Issue by sebolabs** [kubernetes-sigs/aws-alb-ingress-controller#1049]
**EKS Kubernetes version:** 1.14
**ALB-ingress-controller:** 1.1.3

I ran some tests and it seems that ALB-ingress-controller that controls the ALB and its target groups does not support targets recovery after nodes replacement.

Situation:
- ingress configured
- ALB IC detects new configuration added
- ALB IC creates the ALB and target groups
= everything works smoothly, and then:
- ASGed nodes go down _(because of scaling event or need for replacement)_
- ALB target groups lose their target instances _(expected)_
- ASGed nodes go up _(scaled up again)_
- All services on the EKS recover _(expected)_
- **ALB target group remain without targets** _(here's the problem)_

Have I missed a setting somewhere, is there a way to cope with that automatically somehow or this is the actual behavior and ALB IC doesn't really manage situations like that?

**Comment by sebolabs** [comment]
Annotations! :) It seems that because of, let's say, ingress annotations misconfiguration (integers that were supposed to be passed as strings) ALB IC was not able to track stuff. I played with that a little bit more once I fixed the issue in my config and managed to get it working.
Scaling down and up again works as expected, targets get recovered properly. All good!

Sorry for any confusion caused. Big up!

**Comment by gevial** [comment]
Hi @sebolabs 

We're facing the same issue.
Could you please elaborate on what exactly did you change to fix this?

Thanks!

**Comment by sebolabs** [comment]
I suggest to comment out your specific ingress annotations and then adding them one by one and watching (logs) whether changes are being picked up by your ALB IC.
That way I managed to figure out that for some reason having thresholds' counts provided as integers caused other annotations being ignored for some reason and therefore the entire thing did not behave properly.

**Comment by gevial** [comment]
Thanks @sebolabs 

Indeed Helm v3 `upgrade` didn't add proper annotations for some reason however `helm template` clearly shows they will be added.
Target reconciled properly after we've added annotations.
