### ISSUE TITLE
Target groups not deleted when load balancer is deleted

### ISSUE THREAD

**Issue by jhoos** [kubernetes-sigs/aws-alb-ingress-controller#1050]
If I remove an ingress from my cluster, it appears that the ALB controller deletes the ALB listeners, and the ALB itself. However, it never tries to delete the target groups.

Is this expected behavior, or should the controller be deleting the target groups as well?  If not, why?

Example logs from removing an ingress:
```
I1016 18:50:42.441912       1 lb_attachment.go:49] qa/cloudfront-merged: modify securityGroup on LoadBalancer arn:aws:elasticloadbalancing:us-west-2:<redacted> to be [sg-<redacted>]
I1016 18:50:42.637179       1 listener_group.go:85] qa/cloudfront-merged: deleting listener 443, arn: arn:aws:elasticloadbalancing:us-west-2:<redacted>
I1016 18:50:42.706573       1 loadbalancer.go:150] qa/cloudfront-merged: deleting LoadBalancer arn:aws:elasticloadbalancing:us-west-2:<redacted>
```

Note there's no errors or any messages indicating that it even considered removing the target groups.  I had to remove them by hand through the AWS console.

**Comment by sebolabs** [comment]
I cannot confirm that behavior, just tested it and everything got deleted properly, including target groups 👍🏻

```
I1017 22:00:41.848203       1 targetgroup_group.go:93] demo/ingress: deleting target group arn:aws:elasticloadbalancing:eu-west-1:XXXXXXXXXXXX:targetgroup/408547c3-1d0dae14bb3ca6663fd/204a09b721de4ad9
I1017 22:00:41.848434       1 api.go:1053] Request: elasticloadbalancing/DeleteTargetGroup, Payload: {  TargetGroupArn: "arn:aws:elasticloadbalancing:eu-west-1:XXXXXXXXXXXX:targetgroup:targetgroup/408547c3-1d0dae14bb3ca6663fd/204a09b721de4ad9"}
I1017 22:00:41.881124       1 api.go:1053] Response: elasticloadbalancing/DeleteTargetGroup, Body: {}
```

**On v. 1.1.3**

**Comment by jhoos** [comment]
We're running v1.1.3.  I did some further testing, and figured out how to cause the issue.  If you run the ingress controller with the `--default-tags` option, and then in the Ingress itself you also specify the `alb.ingress.kubernetes.io/tags` annotation with a tag using the same tag name as one of the default tags, but a different value, you can reproduce the behavior I saw.

For example: run the ingress controller with the `--default-tags=Foo=Bar` option, then create an ingress with the annotation `alb.ingress.kubernetes.io/tags: Foo=Baz`. Once the ALB has been built, delete the ingress.  You will see the load balancer and and listener be deleted, but not the target group.

It seems that the `--default-tags` option affects what tags the controller is using to actually find the target groups, in addition to just decorating the target groups with those tags. That may very well be intended behavior, in which case the fix may be to just document that if you provide default tags, you should not override them with the annotation or target groups may get orphaned.

In any case knowing this, I can at least work around the issue for now.
