### ISSUE TITLE
etcd restore: old vpc used

### ISSUE THREAD

**Issue by Morriz** [kubernetes-sigs/aws-alb-ingress-controller#1052]
After restoring a cluster from etcd, the alb controller is re-using the old vpc id, which is leading to errors:
```
InvalidTarget: The following targets are not in the target group VPC
```
Can the controller not get the correct vpc id?

**Comment by s-tokutake** [comment]
I am also facing a similar issue.
I deployed alb ingress controller which vpc id parameter was wrong.
And i fixed it and re-deployed, but the controller used the worng vpc id.
So I re create the eks cluster and deployed alb ingress controller with correct paramter, but the problem is not solved.
