### ISSUE TITLE
routing.http2.enabled does not work

### ISSUE THREAD

**Issue by eddycharly** [kubernetes-sigs/aws-alb-ingress-controller#1059]
Setting `routing.http2.enabled=false` in the alb attributes annotation does not work correctly.
Sometimes i set it to true, and the alb has http2 disabled.
Sometimes i set it to false, and the alb has http2 enabled.

In any case, when i succeed to set it to false, http2 is disabled for a few minutes and is reactivated a few minutes later.

Maybe a sort of cache issue...

Below are the controller logs, notice how it is reset to true after a while though i didn't change the ingress annotations :
```
I1101 18:55:12.539522       1 attributes.go:144] ingress/internet: Modifying ELBV2 attributes to [{    Key: "routing.http2.enabled",    Value: "true"  }].
I1101 19:23:09.220610       1 attributes.go:144] ingress/internet: Modifying ELBV2 attributes to [{    Key: "routing.http2.enabled",    Value: "false"  }].
I1101 19:55:10.642617       1 attributes.go:144] ingress/internet: Modifying ELBV2 attributes to [{    Key: "routing.http2.enabled",    Value: "true"  }].
I1101 20:42:08.725861       1 attributes.go:144] ingress/internet: Modifying ELBV2 attributes to [{    Key: "routing.http2.enabled",    Value: "false"  }].
I1101 20:55:12.355644       1 attributes.go:144] ingress/internet: Modifying ELBV2 attributes to [{    Key: "routing.http2.enabled",    Value: "true"  }].
```

**Comment by gws** [comment]
This is happening consistently to me as well, using `v1.1.4`, but with a different annotation.

When I first set the annotation `alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300`, nothing happened.

Later, I set `alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=360` (note the different timeout value), and the following was logged by the controller:

```
Modifying ELBV2 attributes to [{    Key: "idle_timeout.timeout_seconds",    Value: "300"  }].
```

I then set `alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300` once more and the following was logged:

```
Modifying ELBV2 attributes to [{    Key: "idle_timeout.timeout_seconds",    Value: "360"  }].
```

Further testing yielded the same results - the **previous** set of attributes are getting synced, not the **current** set of attributes.
