### ISSUE TITLE
ALB custom added target group got periodically cleanup

### ISSUE THREAD

**Issue by pcchannz** [kubernetes-sigs/aws-alb-ingress-controller#1066]
If I map a target group manually to a path in ALB, it will get periodically clean up by the ingress controller.

Is there any annotation in ingress to map service name to target group, or to disable cleanup for custom added rule?

Thanks!

**Comment by M00nF1sh** [comment]
@pcchannz 
Use this https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/tasks/migrate_legacy_apps.md , exactly for your use case

**Comment by pcchannz** [comment]
@M00nF1sh you just save my day! Thanks :)
