### ISSUE TITLE
How to restrict source IP access for creating alb by ingress?

### ISSUE THREAD

**Issue by gxjluck** [kubernetes-sigs/aws-alb-ingress-controller#1070]
How to automatically add restricted source IP access policies through annotations?

**Comment by gxjluck** [comment]
For example, I want to restrict the specified source IP to have access to my http: //$domain/admin directory.

**Comment by alFReD-NSH** [comment]
Currently this is not supported, but being discussed in #909

**Comment by alFReD-NSH** [comment]
With #1088 merged now you can route based on source ip and various other conditions, also you can use security groups to to limit your ELB access.

/close
