### ISSUE TITLE
aws-alb-ingress-controller in EKS randomly returns 460 HTTP code

### ISSUE THREAD

**Issue by evgpisarchik** [kubernetes-sigs/aws-alb-ingress-controller#1075]
In our system, we use aws-alb-ingress-controller for EKS.
We have millions of requests per day.
Some days the number of returned 460 HTTP codes reaches 5%.

According to AWS docs.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-460-issues
**The load balancer received a request from a client, but the client closed the connection with the load balancer before the idle timeout period elapsed.**

**Check whether the client timeout period is greater than the idle timeout period for the load balancer. Ensure that your target provides a response to the client before the client timeout period elapses, or increase the client timeout period to match the load balancer idle timeout, if the client supports this.**

Have anyone experienced the same issue and how did you solve this?

**Comment by rjl79** [comment]
We experienced an unexpected number of 460's with ALB's, but at the time were not running on EKS. If I remember correctly it was due to a timer issue in our JS client, which was closing connections prematurely. 

What is connecting to your EKS cluster and could there be a timeout on the client side causing these 460's?

**Comment by evgpisarchik** [comment]
The frontend sends HTTP API calls to the cluster.
Client timeout period > 30 seconds.

**Comment by xtroncode** [comment]
Hi @evgpisarchik , were you able to solve this ?

**Comment by evgpisarchik** [comment]
As it seems it was a problem with CPU utilization (spikes) on EC2 instances.
After we managed to implement proper scalability for our scenarios most of the 460s were gone.
