### ISSUE TITLE
Automatic ACM certificate association isn't working.

### ISSUE THREAD

**Issue by echoboomer** [kubernetes-sigs/aws-alb-ingress-controller#1076]
I had originally opened this issue:

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/896

This PR was merged in which theoretically fixed the problem:

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/923

This was apparently implemented in `v1.1.3`:

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.1.3

We're running `v1.1.3` currently:

```
Containers:
  aws-alb-ingress-controller:
    Image:         docker.io/amazon/aws-alb-ingress-controller:v1.1.3
```

When not providing the annotation `alb.ingress.kubernetes.io/certificate-arn`, certificate association still fails:

```
E1118 13:34:42.159210       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to build listener config due to missing certificates annotation alb.ingress.kubernetes.io/certificate-arn could not find any matching certificates from ACM to auto-load"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"foo-rest"}
```

For example purposes, we're passing in the `external-dns` annotation `external-dns.alpha.kubernetes.io/hostname` with the hostname `foobar.stage.domain.com`. This certificate in ACM is for `stage.domain.com` with the additional name `*.stage.domain.com`.

This specific error appears to generate from here:

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/85ab900eeeb4451818eac164385b1f433a8ff125/internal/alb/ls/listener.go#L228

Are there any other things we should be checking for this functionality to start working properly?

**Comment by enver** [comment]
I think #923 brings good solution for your problem, however some changes made in that PR are clearly out of the scope. Returning an error in case multiple certificates cover same domain is one of those because it could happen that multiple certificates cover same domain even before #923 

Perhaps instead of returning error when multiple certs are found it would be better to print warning.
