### ISSUE TITLE
Feature Request: Support Weighted Target Groups

### ISSUE THREAD

**Issue by tsndqst** [kubernetes-sigs/aws-alb-ingress-controller#1078]
https://aws.amazon.com/blogs/aws/new-application-load-balancer-simplifies-deployment-with-weighted-target-groups/ was announced recently.  Are there plans to support this in the ALB Ingress Controller?

Some of the use cases described in the blog post are blue/green deployments and transitioning from one AWS resource type to another.

**Comment by GnatorX** [comment]
To add to this, I am interested in knowing how this work with instance mode vs IP mode. Specifically would instance mode respect the weights?
