### ISSUE TITLE
Why a delay between Adding and Removing targets is bigger than 1 minute?

### ISSUE THREAD

**Issue by kivagant-ba** [kubernetes-sigs/aws-alb-ingress-controller#1080]
Hello.

I'm trying to implement graceful pod termination without blue/green or canary mechanisms. With `preStop` lifecycle hooks it is possible to reduce the amount of 5xx errors. But in Alb Ingress Controller's logs I see a very big delay between adding and removing targets:

```
aws-alb-ingress-controller-56ffbf6999-lf6m8 aws-alb-ingress-controller I1122 13:50:09.322793       1 targets.go:80] default/my-app: Adding targets to arn:aws:elasticloadbalancing:us-east-1:XXXXXXXXX:targetgroup/342d60af-f0f175891e811e51c33/eacd1828295233e0: 10.56.25.27:8080
aws-alb-ingress-controller-56ffbf6999-lf6m8 aws-alb-ingress-controller I1122 13:51:32.393294       1 targets.go:95] default/my-app: Removing targets from arn:aws:elasticloadbalancing:us-east-1:XXXXXXXXX:targetgroup/342d60af-f0f175891e811e51c33/eacd1828295233e0: 10.56.52.247:8080
```

In this example the delay is bigger than one **minute**. And usually it is always bigger than 40 seconds. Which means that ALB is sending requests to the pod that was switched to Terminating state for more than minute! And after a "Deregistration delay" adds even more waiting time if configured.

> (By the way, during my tests I saw even worse situation when a new target instance was added after more than 10 minutes which may cause a really huge downtime in production.)

Why it takes so long to send an API call to ALB to remove targets that are already in Terminating state in Kubernetes?

**Comment by M00nF1sh** [comment]
@kivagant-ba 
I assume you are using the target ip mode. 
If so, it's highly likely you are been throttled by WAF API calls(yes, we call it on every pod relocate event even if you won't have any waf annotations :( ). You can disable it by add `--feature-gates=waf=false` to controller argument.

BTW, you might try out https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.2.0-alpha.1, which perform much quicker(with less aws api calls) on pod relocate events.

**Comment by kivagant-ba** [comment]
Thank you for the explanation, @M00nF1sh.

> alb.ingress.kubernetes.io/security-groups

This is a good tip, I have already configured one SG for all ALBs, without that it works much longer.

> You can disable it by add --feature-gates=waf=false to controller argument.

I assume that [it can be configured here](https://github.com/helm/charts/blob/master/incubator/aws-alb-ingress-controller/templates/deployment.yaml#L50) as an extra argument to the controller's execution command. I will try this.

> v1.2.0-alpha.1

I'm very happy to hear about so massive and perspective update and I will be watching for the evolution of this. We are not in production yet with ALB IG but in a complex environment, so enabling so alpha feature can cause enough big negative effect for the team. Maybe I'll to some experiments in an isolated cluster.

**Comment by kivagant-ba** [comment]
I added `--feature-gates=waf=false` flag and updated ALB IG from 1.1.2 to 1.1.3. Now I see a new suspicious behavior that which was not visible before in logs. Now there are many messages like this:

```
...
rule 7 modified with conditions [{    Field: "host-header",    Values: ["REDACTED"]  },{    Field: "path-pattern",    Values: ["/*"]  }]
rule 8 modified with conditions [{    Field: "host-header",    Values: ["REDACTED"]  },{    Field: "path-pattern",    Values: ["/*"]  }]
...
```

They appear for many applications after every `kubectl rollout restart` call even though the applications were not in the restart list. Nothing is really changed in the values, but ALB IG modifies them again and again.

However, the delay between `Adding` and `Removing` seems to be shorter now.
