### ISSUE TITLE
[Feature request]: Add support for Linkerd Service Mesh

### ISSUE THREAD

**Issue by nicholasgcoles** [kubernetes-sigs/aws-alb-ingress-controller#1081]
I am not sure where exactly the responsibility of something like this would sit, but it would be great if a [Linkerd](https://linkerd.io/) integration was supported by the ALB ingress controller. 

Linkerd discovers services based on the `:authority` or `Host` header. This allows Linkerd to understand what service a request is destined for without being dependent on DNS or IPs.

This should be achievable by allowing the relevant annotations to be added to the ALB ingress controller.

Example annotations for an `nginx` ingress:
```
nginx.ingress.kubernetes.io/configuration-snippet: |
  proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
  grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
```

Current ingress types supported by Linkerd:
- Nginx
- Traefik
- GCE
- Ambassador
- Gloo

More information about the ingress integration with Linkerd can be found [here].(https://linkerd.io/2/tasks/using-ingress)

Is something like this even possible at this stage?

**Comment by nicholasgcoles** [comment]
Any idea if this is possible?

**Comment by wmorgan** [comment]
@nicholasgcoles how are you working around this today?

**Comment by Gowiem** [comment]
@wmorgan @nicholasgcoles was there ever any workaround found here? Is it not possible to use Linkerd with aws-load-balancer-controller?

**Comment by wmorgan** [comment]
@Gowiem I'm not sure. From Linkerd's perspective we need that `l5d-dst-override` header to be set by ingress. If aws-load-balancer-controller supports that then we're good. If not, then they cannot be used together.

**Comment by Gowiem** [comment]
@wmorgan gotcha, yeah I had a similar discussion with a Charles from ya'lls team (I think) in Slack. He mentioned that I could try routing at the Service layer instead of the LB layer and see if that works for my use-case, but I would like to understand if this is something that might be 100% supported in the future.  

@M00nF1sh, sorry to ping you out of the blue, but since you've helped me out in regards to this project before: do you have any thoughts here? Is this something that AWS ALBs / the controller can or will support?

**Comment by rverma-nsl** [comment]
Not sure why this is closed, it seems its still not working. @M00nF1sh can we reopen this?

**Comment by zachfeld** [comment]
has anyone been able to implement a reliable workaround?

**Comment by omidraha** [comment]
I'm using AWS Load Balancer in EKS Kubernetes,
How can I enable mesh at https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/?
I added `"linkerd.io/inject": "enabled"` to the ingress controller, but it didn't make a difference.
