### ISSUE TITLE
Error: AccessDeniedException when creating ALB

### ISSUE THREAD

**Issue by nafpliot** [kubernetes-sigs/aws-alb-ingress-controller#1085]
Hello,

I get the following error when I try to create the ALB
```
kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to get AWS tags. Error: AccessDeniedException: User: arn:aws:sts::1122334455:assumed-role/eksctl-devops-nodegroup-ng-1-work-NodeInstanceRole-J08FDJHIWPI7/i-000000000000 is not authorized to perform: tag:GetResources\n\tstatus code: 400, request id: 94d614a1-c05d-4b92-8ad6-86b450407f6a"  "Controller"="alb-ingress-controller" "Request"={"Namespace":"superset","Name":"superset-ingress"}
```

I tried creating the access permissions not with kube2iam but rather with the [IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/?utm_sq=g6ppph45hf) and then basically followed [these steps](https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/#:~:targetText=The%20AWS%20ALB%20Ingress%20controller,different%20endpoints%20within%20the%20cluster). I have the feeling however that I am missing something. I would expect for the pod to need proper access to create the ALB, not the node. Is there some specific configuration that needs to be done in the controller manifest to work with IRSA?

Thank you.

**Comment by MiniJerome** [comment]
Hi @nafpliot 

As stated in the [IRSA documentation](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html), ALB Ingress Controller does not currently support IRSA.

IRSA requires to call AWS STS to retrieve temporary credentials and I don't think this part is supported in ALB Ingress Controller for now.

AFAIK there are some PRs (https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1017 and https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1026) to update the AWS SDK to enable this feature but it's not available yet.

**Comment by john-auld** [comment]
Hi @nafpliot 

The IRSA documentation now states that the ALB Ingress Controller does support IRSA. Go >= 1.23.13 is required.

I can also confirm that the ALB Ingress Controller works with IRSA
`AWS ALB Ingress controller
  Release:    v1.1.5
  Build:      git-2560c813
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller.git
`

The only problem I see is that the controller only uses the global sts address, sts.amazonaws.com. If the controller is in a private subnet with no Internet access the controller is unable to reach the sts service, which is obviously a fatal error.

I have tried to use environment variables to configure the API to use the regional endpoint (via a vpc endpoint for sts) but that does not appear to work.

`
env:
  - name: AWS_DEFAULT_REGION
    value: eu-west-1
  - name: AWS_SDK_LOAD_CONFIG 
     value: "1"
`

To work in secure environments, it is necessary to use the regional endpoint for STS.

**Comment by nafpliot** [comment]
Thanks for the info @josh-auld . In the meantime I have managed to make it work with 1.1.3. Please check the answer https://stackoverflow.com/a/59267429/2527906 .

Am I missing something here?

**Comment by john-auld** [comment]
I have success too, but only when the controller has access to the Internet. The test case needed to recreated my issue involves setting up a VPC with public and private subnets. Deploy EKS to the private subnet and use NACL's to block outbound traffic, especially for https://sts.amazonaws.com:443/. Now add a VPC Endpoint for the STS service and add an audience to the IAM OIDC identity provider for your region, e.g. sts.us-west-1.amazonaws.com.

Enable API debugging on the controller and observer the following error message in the pod logs.

`
"msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: dial tcp 52.46.134.192:443: i/o timeout"
'

VPC Endpoints are regional and they do not work with the global STS endpoint.

What's needed is an option to configure the Go SDK to use the regional endpoint.

https://github.com/aws/aws-sdk-go/blob/master/aws/session/env_config.go

**Comment by john-auld** [comment]
P.S. Be aware that EKS with IRSA uses AssumeRoleWithWebIdentity.

**Comment by nafpliot** [comment]
> I have success too, but only when the controller has access to the Internet. The test case needed to recreated my issue involves setting up a VPC with public and private subnets. Deploy EKS to the private subnet and use NACL's to block outbound traffic, especially for https://sts.amazonaws.com:443/. Now add a VPC Endpoint for the STS service and add an audience to the IAM OIDC identity provider for your region, e.g. sts.eu-west-1.amazonaws.com.
> 
> Enable API debugging on the controller and observe the following error message in the pod logs.
> 
> `"msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: dial tcp 52.46.134.192:443: i/o timeout"`
> 
> VPC Endpoints are regional and they do not work with the global STS endpoint.
> 
> What's needed is an option to configure the Go SDK to use the regional endpoint.
> 
> https://github.com/aws/aws-sdk-go/blob/master/aws/session/env_config.go

Ah! I understand you now. Probably for me it works because I don't completely block outbound traffic.

**Comment by jaypipes** [comment]
> The IRSA documentation now states that the ALB Ingress Controller does support IRSA. Go >= 1.23.13 is required.
 
Just clarifying... it's the aws-sdk-go v1.23.13+ package that is required, not Go itself :)

**Comment by M00nF1sh** [comment]
I think i can do a change in next release to force use regional sts and remove dependency on RGT(which don't have private link)

**Comment by starchx** [comment]
My worker nodes do not have internet access. All relies on VPC Endpoints. I had same error:

`E0221 21:36:08.250355       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to get AWS tags. Error: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: dial tcp 54.239.29.25:443: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"nginx"}`

Just for testing, I disabled the IRSA and using the worker node instance role instead, but still ran into this error:  

`E0221 23:53:39.184700       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to get AWS tags. Error: RequestError: send request failed\ncaused by: Post https://tagging.eu-west-1.amazonaws.com/: dial tcp 52.94.220.75:443: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"nginx"}`

**Comment by john-auld** [comment]
Update for your information - setting the environment AWS_STS_REGIONAL_ENDPOINTS=regional had the expected result, but it is not specific to sts. When that was enabled I started to get errors from calls to the AWS Waf service, which went via a regional URL.

It seems that vpc endpoints are required for all aws services used by the controller if this environment variable is set to regional. But that is also what's needed if Internet traffic is blocked. So the solution may simply be to set the env var to regional and ensure that all relevant endpoints are available. I have not had time to test that scenario to confirm that it works.

'
RequestError: send request failed\ncaused by: Post https://waf-regional.eu-west-1.amazonaws.com/: dial tcp 52.94.218.95:443: i/o timeout"
'

**Comment by rafaelpereyra** [comment]
I can confirm this issue. The ALB ingress controller timesout trying to read the web ACL from the regional endpoint:

`E0428 16:17:37.559225       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to get web acl for load balancer arn:aws:elasticloadbalancing:us-east-2:403584117900:loadbalancer/app/2546b6ac-default-nginxingr-29e9/c5406ab99d3ec44a: RequestError: send request failed\ncaused by: Post https://waf-regional.us-east-2.amazonaws.com/: dial tcp 52.95.21.40:443: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"nginx-ingress"}`

Maybe it's possible to skip the WAF validation at all? This use case is forn an internal ALB so there are other protections and WAF might not be needed.

**Comment by madhu131313** [comment]
I created a cluster with an existing VPC and I got this error for the first time and it was working fine earlier with a new VPC for cluster creation, have you resolved the issue?

**Comment by john-auld** [comment]
@madhu131313 Assuming that you have a VPC endpoint for STS and traffic is allowed by SG's and there is no direct path to the global sts endpoint, try setting the environment AWS_STS_REGIONAL_ENDPOINTS=regional for the pod.

If not, you need to check the pod logs to see which AWS service has problems. Access to the WAF endpoint is needed too, even if you do not use the WAF service.

**Comment by toytown** [comment]
> Update for your information - setting the environment AWS_STS_REGIONAL_ENDPOINTS=regional had the expected result, but it is does not seem to be specific to sts.
> 
> https://github.com/aws/aws-sdk-go/blob/9c9db07028aeb7d607e54b2b5aa97bbbbebcbbfd/aws/session/env_config.go
> 
> When that was enabled I started to get errors from calls to the AWS Waf service, which went via a regional URL.
> 
> It seems that vpc endpoints are required for all aws services used by the controller if this environment variable is set to regional. But that is also what's needed if Internet traffic is blocked. So the solution may simply be to set the env var to regional and ensure that all relevant endpoints are available. I have not had time to test that scenario to confirm that it works.
> 
> '
> RequestError: send request failed\ncaused by: Post https://waf-regional.eu-west-1.amazonaws.com/: dial tcp 52.94.218.95:443: i/o timeout"
> '

Could you provide some more info where you set this AWS_STS_REGIONAL_ENDPOINTS - ALB ? or pods or configmaps ?

**Comment by john-auld** [comment]
> > Update for your information - setting the environment AWS_STS_REGIONAL_ENDPOINTS=regional had the expected result, but it is does not seem to be specific to sts.
> > https://github.com/aws/aws-sdk-go/blob/9c9db07028aeb7d607e54b2b5aa97bbbbebcbbfd/aws/session/env_config.go
> > When that was enabled I started to get errors from calls to the AWS Waf service, which went via a regional URL.
> > It seems that vpc endpoints are required for all aws services used by the controller if this environment variable is set to regional. But that is also what's needed if Internet traffic is blocked. So the solution may simply be to set the env var to regional and ensure that all relevant endpoints are available. I have not had time to test that scenario to confirm that it works.
> > '
> > RequestError: send request failed\ncaused by: Post https://waf-regional.eu-west-1.amazonaws.com/: dial tcp 52.94.218.95:443: i/o timeout"
> > '
> 
> Could you provide some more info where you set this AWS_STS_REGIONAL_ENDPOINTS - ALB ? or pods or configmaps ?

Via values.yaml (extraEnv)

https://github.com/helm/charts/blob/master/incubator/aws-alb-ingress-controller/templates/deployment.yaml. (Line 51)

`           - name: AWS_DEFAULT_REGION
               value: eu-west-1
            - name: AWS_SDK_LOAD_CONFIG # Required by golang to observe the AWS_DEFAULT_REGION env var
               value: "1"
            - name: AWS_STS_REGIONAL_ENDPOINTS
               value: regional`
