### ISSUE TITLE
ALB dose not work properly on EKS Managed Node Group with Fargate nodel

### ISSUE THREAD

**Issue by XiaoYangZhu** [kubernetes-sigs/aws-alb-ingress-controller#1097]
I created the latest 1.14 EKS cluster with Managed Node group(in public subnet) in us-east-1, and this cluster is also enabled with Fargate model by default:

![image](https://user-images.githubusercontent.com/24489117/70404895-67e8e200-1a76-11ea-8b3e-151ad811c78f.png)

managed node group info:
![image](https://user-images.githubusercontent.com/24489117/70404922-7800c180-1a76-11ea-8dcf-b4bf496aba82.png)

then followed the steps listed here:
https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

however, i received two different behaivors when use ip and instance mode:
[instance mode]:
$ cat 2048-ingress-instance.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "2048-ingress-instance"
  namespace: "2048-game"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
  labels:
    app: 2048-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service-2048"
              servicePort: 80

ALB was created with no listener:
![image](https://user-images.githubusercontent.com/24489117/70405244-75529c00-1a77-11ea-8544-9e0ee3a365e8.png)

Target group was created with no target:
![image](https://user-images.githubusercontent.com/24489117/70405274-93b89780-1a77-11ea-84e9-2832d878161b.png)

After checked the log, we found some info associated with worker node in fargate mode:
kubectl logs -n kube-system -f deployment.apps/alb-ingress-controller
...
E1206 10:37:55.876428       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to reconcile targetGroup targets due to Unable to DescribeInstanceStatus on fargate-ip-192-168-213-217.ec2.internal: InvalidInstanceID.Malformed: Invalid id: \"fargate-ip-192-168-213-217.ec2.internal\"\n\tstatus code: 400, request id: 2aba56f2-3f9d-4510-89dd-7af8e48ca19a"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}
...

We could find that "fargate-ip-192-168-213-217.ec2.internal" with:
$ kubectl get nodes
NAME                                      STATUS   ROLES    AGE     VERSION
fargate-ip-192-168-156-158.ec2.internal   Ready    <none>   17h     v1.14.8-eks
fargate-ip-192-168-192-211.ec2.internal   Ready    <none>   2d21h   v1.14.8-eks
fargate-ip-192-168-213-217.ec2.internal   Ready    <none>   2d21h   v1.14.8-eks
ip-192-168-108-148.ec2.internal           Ready    <none>   2d21h   v1.14.7-eks-1861c5
ip-192-168-12-85.ec2.internal             Ready    <none>   2d21h   v1.14.7-eks-1861c5 

[ip mode]:
$ cat 2048-ingress-ip.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "2048-ingress-ip"
  namespace: "2048-game"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: 2048-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service-2048"
              servicePort: 80
We found that all is good; we can see ip was registered in the target group and also alb has the right listener configured as below:

![image](https://user-images.githubusercontent.com/24489117/70405584-a5e70580-1a78-11ea-9361-afd9e5746aff.png)

PLS NOTE: initially the status of the ip target is in the unheathy and after the deep check, we found that the security group of ALB was not trusted in the security group of worker node in the Managed Node group. After we manually configured the SG in Managed Node group, then all the ip target came back to healthy:
![image](https://user-images.githubusercontent.com/24489117/70405830-813f5d80-1a79-11ea-885a-901428c312ea.png)

Last, in both ip and instance mode, the ip address of the two ingress resource is both empty:
$ kubectl get ingress -n 2048-game
NAME                    HOSTS   ADDRESS   PORTS   AGE
2048-ingress-instance   *                 80      15h
2048-ingress-ip         *                 80      15h

**Comment by M00nF1sh** [comment]
Hi, currently only IP mode can be used if you have Fargate pods. (there will be changes to enable instance mode if you have ec2 nodes as well). 
For security group, ```initially the status of the ip target is in the unheathy and after the deep check, we found that the security group of ALB was not trusted in the security group of worker node in the Managed Node group.```, is the pods for your ingress fargate pods or ec2 pods? and is your fargate pods(fargate profile) using same security group as managed node group?

**Comment by jpadams** [comment]
@M00nF1sh I've had problems as well for a similar use case, but using `eksctl`.
Can you take a look at my approach? Perhaps it could help @XiaoYangZhu as well.

https://github.com/weaveworks/eksctl/issues/1640#issuecomment-563309793

I basically create the cluster with `eksctl`using this script. Then I expected to get an alb created when I created an ingress.
https://gist.github.com/jpadams/9de54c2399bb8fda1809aada35f00de2

**Comment by XiaoYangZhu** [comment]
> Hi, currently only IP mode can be used if you have Fargate pods. (there will be changes to enable instance mode if you have ec2 nodes as well).
> For security group, `initially the status of the ip target is in the unheathy and after the deep check, we found that the security group of ALB was not trusted in the security group of worker node in the Managed Node group.`, is the pods for your ingress fargate pods or ec2 pods? and is your fargate pods(fargate profile) using same security group as managed node group?

I do not think there is a notion of security group for fargate profile and the pod is my ec2 pod. Also, i have some new update as replied below. thank you!

**Comment by XiaoYangZhu** [comment]
> @M00nF1sh I've had problems as well for a similar use case, but using `eksctl`.
> Can you take a look at my approach? Perhaps it could help @XiaoYangZhu as well.
> 
> [weaveworks/eksctl#1640 (comment)](https://github.com/weaveworks/eksctl/issues/1640#issuecomment-563309793)
> 
> I basically create the cluster with `eksctl`using this script. Then I expected to get an alb created when I created an ingress.
> https://gist.github.com/jpadams/9de54c2399bb8fda1809aada35f00de2
> 
> ```
> ---
> apiVersion: apps/v1beta1
> kind: Deployment
> metadata:
>   name: aws-example-octodex
> spec:
>   replicas: 1
>   strategy:
>     rollingUpdate:
>       maxSurge: 1
>       maxUnavailable: 1
>   minReadySeconds: 5
>   template:
>     metadata:
>       labels:
>         app: aws-example-octodex
>     spec:
>       containers:
>       - name: aws-example-octodex
>         image: XXXXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/example-eks:dfe25be0fe406aa2f0142414edec47c0b43adb45
>         ports:
>         - containerPort: 5000
>         resources:
>           requests:
>             cpu: 250m
>           limits:
>             cpu: 500m
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: aws-example-octodex
>   annotations:
>     alb.ingress.kubernetes.io/target-type: ip
> spec:
>   type: ClusterIP
>   ports:
>     - port: 80
>       targetPort: 5000
>   selector:
>     app: aws-example-octodex
> ---
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: "aws-example-octodex-ingress"
>   namespace: "default"
>   annotations:
>     kubernetes.io/ingress.class: "alb"
>     alb.ingress.kubernetes.io/scheme: "internet-facing"
>   labels:
>     app: aws-example-octodex-ingress
> spec:
>   rules:
>     - http:
>         paths:
>           - path: /
>             backend:
>               serviceName: "aws-example-octodex"
>               servicePort: 80
> ```

pls keep the service with nodeport and I have no issue for it now.

**Comment by XiaoYangZhu** [comment]
latest update:
1. successfully created the alb ingress on managed node group (with no any fargate container created)

2. successfully created the alb ingress on fargate container

3. sitll failed create the alb ingress on managed node group AFTER step-2, where there is some fargate container/node appeared in the cluster. ingress controller log:

E1213 06:43:34.253354       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to reconcile targetGroup targets due to Unable to DescribeInstanceStatus on fargate-ip-192-168-136-154.ec2.internal: InvalidInstanceID.Malformed: Invalid id: \"fargate-ip-192-168-136-154.ec2.internal\"\n\tstatus code: 400, request id: cc33e6b7-1ac7-433f-af0f-b07e2298f31a"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game-after-fargate","Name":"2048-ingress-after-fargate"}

**Comment by jpadams** [comment]
This is what unblocked me:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1092#issuecomment-561400256

**Comment by M00nF1sh** [comment]
Hi guys,
Just released an new release V1.1.5 which solves this problem :D 
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.1.5
