### ISSUE TITLE
Instances in Non Running state get added to targetGroups

### ISSUE THREAD

**Issue by jescarri** [kubernetes-sigs/aws-alb-ingress-controller#1099]
Kubernetes version: 1.14.6
alb-ingress-controller version: custom build of v1.1.3 with aws-sdk-go v1.16.35 

We use spot-instances and our clusters get a lot of new instances all the time.

Config:

````
        - args:
          - --cluster-name=cluster1.foo
          - --restrict-scheme=true
          - --restrict-scheme-namespace=$(POD_NAMESPACE)
          - --feature-gates=waf=false
          - --max-concurrent-reconciles=5
          - -v=5
````

We have seen a lot of errors like this:

````
E1209 16:19:29.826259       1 targets.go:87] foo/bar: Error adding targets to arn:aws:elasticloadbalancing:us-east-1:NNNNNNNNNN:targetgroup/fooo-bar: InvalidTarget: The following targets are not in a running state and cannot be registered: 'i-NNNNNN', 'i-NNNN', 'i-NNNNN', 'i-NNNN'
E1209 16:19:29.826274       1 targets.go:87] foo/bar: 	status code: 400, request id: 60f9ea7f-6761-44f6-9765-25cd15a5d871
````

The reconcile loop gets into a deadlock and ingress updates get stuck for about 20 minutes.

**Comment by s2504s** [comment]
Have you tried to use lambda function for avoiding this issue?
https://github.com/s2504s/kube_alb_lambda_deregister

**Comment by jescarri** [comment]
nice! @s2504s  we use SpotInst and the SpotInst cluster autoscaler, probably we will add some logic for the labeling of the node on that front, thanks for this!.
