### ISSUE TITLE
aws-alb-ingress-controller deletes manually added listeners and security groups

### ISSUE THREAD

**Issue by saket9550** [kubernetes-sigs/aws-alb-ingress-controller#1105]
Hi Team,
I manually added some listeners in the ALB to expose one of my service.
I found teh listener was automatically deleted by ingress controller.
Similarly, I added security group also for the load balance.It also got deleted.

Can you please help me here?

**Comment by M00nF1sh** [comment]
The ALB Ingress Controller is driving the desired state of ALB to match the specified spec on Ingress Object. So any direct modification to ALB via AWS API will be overwritten.

For SecurityGroups, you can use [`alb.ingress.kubernetes.io/security-groups` annotation](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/) to control securityGroups, the draw back is you need to modify securityGroup on nodes on allow inbound access from the ALB securityGroups you specified.
For Listeners, you can use [`alb.ingress.kubernetes.io/listen-ports` annotation](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/) to control the listen ports(if all listen ports have same routing rule/backend.  If it's different routing rule/backend, there is an alpha version to let u do that: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.2.0-alpha.1. 

Also, i think an additional annotation like `alb.ingress.kubernetes.io/listen-ports-unmanaged` maybe a good idea.

**Comment by saket9550** [comment]
Thanks.
Can you please tell me when can we use this in production  https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.2.0-alpha.1?
We really have a use case where we expose different microservices on different ports.

**Comment by jvargas-fs** [comment]
I'm currently trying to add an AWS WAF protected ALB as a target group for an NLB. LBC doesn't support target groups of type ALB which the console does. When I add a new listener with the ALB as target via Terraform, the listener is deleted by the LBC after some time as it's reconciling state. I think @M00nF1sh's suggestion of having a `alb.ingress.kubernetes.io/listen-ports-unmanaged ` annotation is the least we should have to cover this type of scenarios without to switch to having the NLB be externally managed.
