### ISSUE TITLE
question least outstanding requests

### ISSUE THREAD

**Issue by renperez** [kubernetes-sigs/aws-alb-ingress-controller#1106]
do we have the annotation yet to support LOR? I know LOR came out recently and I'm wondering if we have a way to implement this yet.

Least outstanding requests (LOR) algorithm is now available for Application Load Balancer. This is in addition to the round-robin algorithm that the Application Load Balancer already supports. Customers have the flexibility to choose either algorithm depending on their workload needs.

**Comment by eakmanrq** [comment]
It was added in version `v1.1.4`: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.1.4

**Comment by renperez** [comment]
@eakmanrq thanks!
