### ISSUE TITLE
Need the ability to get the name of the ALB for Pod Metrics. 

### ISSUE THREAD

**Issue by seivan** [kubernetes-sigs/aws-alb-ingress-controller#1116]
To use ALB metrics from Cloud Watch in HPA you would need to know the name.
Since the name uses a generated UUID and doesn't seem accessible it would be useful to either give it a name straight off, or expose the name somehow when describing the ingress. 

Almost similar to https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/870 but knowing the prefix isn't enough when using https://github.com/awslabs/k8s-cloudwatch-adapter

**Comment by dusansusic** [comment]
I hit this issue, too.
Provisioning everything with Terraform and now I have couple TGs per ALB and there's no way to gather data to create CloudWatch alarms but to do that manually.
Even Terraform data resrouce "aws_alb" is useless in this case since we need to provide name or ARN.

**Comment by seivan** [comment]
Why even have a [name generator](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/48f365724488bf8b4f4deddd60f7ccda06a778f5/internal/alb/generator/name.go)
What is the actual purpose instead of accepting name as a config param?

**Comment by devkid** [comment]
You can also easily find the ALB for a specific ingress via the tags that are applied to the ALB (namespace, ingress name, cluster name).

**Comment by seivan** [comment]
@devkid Not sure you can do that in Terraform where the name of the ALB is needed to setup further infrastructure (such as Cloudwatch) but I am happy with that solution if it works.

**Comment by mattdodge** [comment]
I'm looking for this as well. We use the ALB Ingress Controller to create the ALBs for us from the cluster. But then I need the name or the ARN of the ALB to add it as an origin to our CloudFront distribution with terraform.

A few possible options I see:
1. Allow setting the name of the ALB with a kubernetes annotation. I tried to set the `Name` tag with an annotation but no luck.
2. Make the name generation somewhat deterministic and calculatable offline. This may already be the case, I see the name generator but I'm not fully parsing it.
3. Improve the [aws_lb data source](https://www.terraform.io/docs/providers/aws/d/lb.html) in Terraform to accept more than just a name/arn. Obviously this is out of scope for this project but it would at least solve our use case.

**Comment by dudicoco** [comment]
@mattdodge can't this be easily resolve by using `external-dns` to create a CNAME/ALIAS record for the load balancer and using this DNS in the CloudFront origin?

**Comment by mattdodge** [comment]
@dudicoco You're right, I suppose I could do that. I had replaced external-dns since I figured my DNS names would point to the cloudfront distro rather than the LB, but I could use an additional DNS name to refer to the LB. It's an extra DNS hop but that might be better than the hard coded ALB names that I'm currently using.
