### ISSUE TITLE
Provide example to setup ALB ingress controller with EKS fargate

### ISSUE THREAD

**Issue by nithu0115** [kubernetes-sigs/aws-alb-ingress-controller#1117]
Provide example on how to setup ALB ingress controller with EKS fargate

**Comment by mikestef9** [comment]
Blog post out to address this 

https://aws.amazon.com/blogs/containers/using-alb-ingress-controller-with-amazon-eks-on-fargate/

**Comment by M00nF1sh** [comment]
:D
