### ISSUE TITLE
How to pass multiple acm certificate into a single ingress

### ISSUE THREAD

**Issue by vrathore18** [kubernetes-sigs/aws-alb-ingress-controller#1118]
Any one know to pass multiple certificate for a single ALB

I am aws_alb_ingress controller. Below is my ingress

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "my-ingress"
  namespace: "my-namespace"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.external.acmCertificateARN }}
  labels:
    app: my-ingress-app
spec:
  rules:
    - host: app1.host1.example.com
      http:
         paths:
            - path: /*
              backend:
                serviceName: "my-first-service"
                servicePort: 80
    - host: app2.host2.example.com
      http:
         paths:
            - path: /*
              backend:
                serviceName: "my-other-service"
                servicePort: 80

As I am 2 different host. I created 2 acm certificate for *.host1.example.com and *.host2.example.com. But How can I pass two certificate for in a single ingress (**alb.ingress.kubernetes.io/certificate-arn: {{ .Values.external.acmCertificateARN_first }}, {{ .Values.external.acmCertificateARN_second }}**)

aws-alb-ingress-controller version is v1.0.1

**Comment by rparsonsbb** [comment]
See [here](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#certificate-arn).

The list is comma separated without spaces.
