### ISSUE TITLE
Advanced Routing based on http header

### ISSUE THREAD

**Issue by saket9550** [kubernetes-sigs/aws-alb-ingress-controller#1120]
Hi Team,
I have a use-case where I would like to do routing based on the http header referer field.
Is this supported in aws-alb-ingress-controller?

**Comment by M00nF1sh** [comment]
new V1.1.5 release supports such use case :D
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.1.5
