### ISSUE TITLE
Remove path prefix from url?

### ISSUE THREAD

**Issue by nsisodiya** [kubernetes-sigs/aws-alb-ingress-controller#1133]
I have created my paths like this.

https://api.syn-platform.com/service1/
https://api.syn-platform.com/service2/
Now these service1 and service2 are two independent node js backend server.
If tomorrow, If I want to change the path, from /service1 to /service1-beta/
I have to change urls and coding inside the service.
Also, I need to register my urls like /service1/health inside the codebase. I wish if ALB Ingress do some remove some portion of path so that my service will receive it as `/health` and not `/service1/health`.

fastify support Route prefixing which we are using it - https://github.com/fastify/fastify/blob/master/docs/Routes.md#route-prefixing but I wish if something can be done so that we don't need to use Route prefix too.

**Comment by M00nF1sh** [comment]
Hi, this is known as pathRewrite. ALB itself doesn't support this feature yet, so it's not possible for now.
But i'm aware that ALB team is building features like this

**Comment by bjorngoossens** [comment]
Really hoping that the ALB team can realise such pathRewrite functionality! We now also have to rely on services implementing a URL prefix for path-based routing. We could also use NGINX as ingress controller but would rather have rewriting functionality out of the box for ALB.

**Comment by kaykhancheckpoint** [comment]
I'm also looking for this, any news?

**Comment by Yuval-Peled** [comment]
+1 for this. Would greatly simplify my architecture

**Comment by ahmednawaz10p** [comment]
any update on this ?

**Comment by hamza-saqib** [comment]
i am also looking this feature to be implemented in ALB this will solve big problem, right now i have 6 app running inside the ECS and i have to tell my development team to add those urls inside their code base which is kind of more work and not professional, so anyone from can give me an alternate to this solution because i don't wanna change my app endpoints. i have asp.net app which is for APIs.

**Comment by Zavy86** [comment]
any news?

**Comment by rsmets** [comment]
Man, this would nice... please reopen. Is there somewhere we can upvote the development work?

**Comment by joarobles** [comment]
It's been 4 years now and without any official answer
