### ISSUE TITLE
Advanced routing option gives: failed to GC targetGroups due to failed to delete targetGroup due to ResourceInUse

### ISSUE THREAD

**Issue by mohitanchlia** [kubernetes-sigs/aws-alb-ingress-controller#1140]
Release: 1.1.5
Advanced routing option with weights on a TG is what I am trying to test. But I get error:

The below configuration did create 2 rules, however it is now trying to delete one of the preexisting TGS from those rules. Below configuration create 2 rules like this:

THEN
Forward to
caf3bb0c-5458b9d866d32d43ccc: 80 (80%)
caf3bb0c-497bf45e8963ca6ecd6: 20 (20%)
Group-level stickiness: 20 seconds

alb ingress logs
E0122 19:57:38.167233       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to GC targetGroups due to failed to delete targetGroup due to ResourceInUse: Target group 'arn:aws:elasticloadbalancing:us-west-2:XXXX:targetgroup/caf3bb0c-5458b9d866d32d43ccc/db26700c342b16e8' is currently in use by a listener or a rule\n\tstatus code: 400, request id: 1935d805-83ec-472a-8823-19a72768ef69"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"nginx-service-ip-ingress"}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx-service-ip-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/actions.forward-multiple-tg: >
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"TargetGroupArn":"arn:aws:elasticloadbalancing:us-west-2:XXXXX:targetgroup/caf3bb0c-5458b9d866d32d43ccc/db26700c342b16e8","Weight":80},{"ServiceName":"nginx-2","ServicePort":"80","Weight":20}],"TargetGroupStickinessConfig":{"Enabled":true,"DurationSeconds":20}}}
  labels:
    app: nginx-ingress
spec:
  rules:
    - host: nginx.service.eks4.internal.aws
      http:
        paths:
          - path: /*
            backend:
              serviceName: forward-multiple-tg
              servicePort: use-annotation

Questions:
- Why is the TG being deleted?
- Why are we getting this error?
- We need to do this in production without any impact on the existing ingress

**Comment by M00nF1sh** [comment]
Hi,
would you help add the full logs above this error(related to this reconcile loop)

**Comment by M00nF1sh** [comment]
Also, check this "use ARN in forward Action": https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#actions.

ARN can be used in forward action(both simplified schema and advanced schema), **it must be an targetGroup created outside of k8s**, typically an targetGroup for legacy application.

I assume you are using an targetGroup created by alb ingress controller. You should use ServiceName/ServicePort for such case.

**Comment by srinivasreddych** [comment]
@mohitanchlia 
The intended usage of "TargetGroupArn" field is to leverage any TGs created out of k8s. In your case, as the TG was created by the Ingress's backend, and as you were trying to reuse the same TG for the new feature "multi TGs", you should consider using "serviceName/servicePort" in your ingress file. Example is below:

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "2048-ingress"
  namespace: "2048-game"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/actions.forward-multiple-tg: >
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"service-2048","ServicePort":"80","Weight":80},{"ServiceName":"service-1","ServicePort":"80","Weight":20}],"TargetGroupStickinessConfig":{"Enabled":true,"DurationSeconds":200}}}
  labels:
    app: 2048-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: forward-multiple-tg
              servicePort: use-annotation`

Notes: 

- In the above snippet, we were using serviceName/servicePort syntax but not the "TargetGroupArn".
- "service-2048" was the service created initially (for which the TG existed in your case), "service-1" is the new service i added for testing.
- Once you modify your ingress file to reflect the above changes, which means, once you add 2 serviceNames/servicesPorts, you should not be seeing the reported errors in the controller logs.

**Comment by mohitanchlia** [comment]
Does it mean I can use target groups created outside of K8s? In other words can I manage ingress inside of K8 but only have external target groups? For eg: classic tomcat service running on a EC2 with ALB in the front, but ALB is being managed by K8? Is that possible?

**Comment by M00nF1sh** [comment]
@mohitanchlia Yes, that's exactly the intended use case for TargetGroupArn. it let you mix tradition application with k8s application.
For TargetGroups created by k8s, we should use serviceName/port instead :D
