### ISSUE TITLE
unable to reroute the path from alb its taking to old servicename

### ISSUE THREAD

**Issue by daparthi001** [kubernetes-sigs/aws-alb-ingress-controller#1145]
i am trying to configure the ingress for the http://login.stage.<>/
for some how its taking the service name while hiting the url 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.openam: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "Host": "port.login.<>",
      "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.openam-ssl: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "Host": "login.<>",
      "Path":"/", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: <crt arn>
    alb.ingress.kubernetes.io/enable-cors: "true"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/rewrite-target: /
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: <public facing subnets>
    kubernetes.io/ingress.class: alb
  creationTimestamp: "2020-01-27T17:19:02Z"
  generation: 9
  labels:
    app: openam
    chart: openam-6.5.1
    heritage: Tiller
    release:<>
    vendor: forgerock
  name: openam
  namespace: default
  resourceVersion: "1113084"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/openam
  uid: 1d4a9953-4129-11ea-8dbe-06928e912210
spec:
  rules:
  - host: login.stage.<>
    http:
      paths:
      - backend:
          serviceName: openam
          servicePort: 80
        path: /XUI/#login/*
      - backend:
          serviceName: openam
          servicePort: 80
        path: /*
status:
  loadBalancer:
    ingress:
    - hostname: <masking the name>.us-west-2.elb.amazonaws.com

**Comment by daparthi001** [comment]
![image](https://user-images.githubusercontent.com/17385792/73214795-7a97a300-4118-11ea-9b35-3a3e0af8c790.png)

**Comment by M00nF1sh** [comment]
Hi,
do you have an service of `openam` with port '80'? 
I saw u defined 'actions.openam:', but didn't use the 'use-annotation' as port. 
BTW, alb doesn't support path rewrite feature. so `alb.ingress.kubernetes.io/rewrite-target` is no-op

**Comment by daparthi001** [comment]
Yes i got the service with name openam with service port 80 and target port 8080 .As soon as i hit the alb its redirecting to application name which is openam.

**Comment by M00nF1sh** [comment]
it's still not clear what's the problem here to be honest..Is the rule setup on alb incorrect?
