### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by kamalperumal** [kubernetes-sigs/aws-alb-ingress-controller#1146]
Hello,

I'm encountering the same error as above

E0131 12:52:37.524644       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment: expect one securityGroup tagged with kubernetes.io/cluster/ceng-eks-dev on eni eni-0f65b7aded0bdc0a1, got 2"  "controller"="alb-ingress-controller" "request"={"Namespace":"sun-web-dev","Name":"2048-ingress"}
E0131 12:55:23.580341       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment: expect one securityGroup tagged with kubernetes.io/cluster/ceng-eks-dev on eni eni-0f85b01ce93f35590, got 2"  "controller"="alb-ingress-controller" "request"={"Namespace":"sun-web-dev","Name":"2048-ingress"}

_Originally posted by @kamalperumal in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1028#issuecomment-580725169_

**Comment by M00nF1sh** [comment]
@kamalperumal 
Which version you are using? would help check the security groups on "eni-0f85b01ce93f35590" from AWS console. The controller expects only one securityGroup tagged with `kubernetes.io/cluster/ceng-eks-dev`

**Comment by M00nF1sh** [comment]
Feel free to reopen this if the issue persists 😄
