### ISSUE TITLE
Document HTTPS requirement for Cognito/OIDC authentication

### ISSUE THREAD

**Issue by otterley** [kubernetes-sigs/aws-alb-ingress-controller#1149]
If a user attempts to configure Cognito or OIDC authentication for an ALB ingress using the appropriate annotations, but fails to configure a TLS listener, the annotations will have no effect, and no error will be returned to the user or printed to the controller logs.  This leaves the user very confused as to why things aren't working.

Document this requirement in the docs, and provide some sort of error messaging that the user can use for debugging.

**Comment by M00nF1sh** [comment]
/kind documentation
Thanks for the feedback. This indeed should be some documentation improvement for this.

We can have a warning about unused annotations starting with 'alb.kubernetes.io' too, but seems hard to implement for now without massive changes.
