### ISSUE TITLE
Cannot configure Ingress

### ISSUE THREAD

**Issue by khilmanoj** [kubernetes-sigs/aws-alb-ingress-controller#1153]
Hi,

I am still unable to fix the below issue. Read through the other solutions but still not working. 
 
E0205 20:10:10.502538       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to get AWS tags. Error: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 82e28498-4853-11ea-af47-a9b8372e9ea2"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}

I added the policy to the worker nodes and added the tags to the subnet.

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/alb-ingress-controller.yaml
deployment.apps/alb-ingress-controller created

kubectl edit deployment.apps/alb-ingress-controller -n kube-system

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/2048/2048-ingress.yaml

Thanks
Manoj Khilnani

**Comment by M00nF1sh** [comment]
Hi, 
Are you using IAM for service accounts?
seems like the trust relationship on the IAM role for your service-account isn't setup correctly

**Comment by khilmanoj** [comment]
Hi, Yes you are correct. The issue was with the trust relationship. The documentation has the below configuration
"oidc.eks.us-east-1.amazonaws.com/id/C0ABB71E7A517B90B7A04D4519951F14:sub": "alb-ingress-controller"

But this does not work, I had to change it to below

"oidc.eks.us-east-1.amazonaws.com/id/C0ABB71E7A517B90B7A04D4519951F14:sub": "system:serviceaccount:kube-system:alb-ingress-controller"

Thanks.
Manoj Khilnani
