### ISSUE TITLE
Now to to access the application via ALB created

### ISSUE THREAD

**Issue by vrathore18** [kubernetes-sigs/aws-alb-ingress-controller#1156]
Hey Folks,
I am using aws-alb-ingress-controller in my k8s setup. I created ingress which ultimately creating the alb loadbalancer and target group. I used route53 with the same alb.
I am getting "This site can’t be reached" when hitting the route53 url. I even tested the record set. I don't see any error then why I can't access my application?

```
DNS request sent to Route 53
xxxx.xxx.co.     IN     A
EDNS0 client subnet IP
24
DNS response code
NOERROR
Protocol
UDP
Response returned by Route 53
172.17.49.33
172.17.55.17
172.17.59.211
```
Also when I did the port-forward on the pod(alb is attached to the same pod via service). I am able to access the application. That means alb is not able to access the service/pod. I even checked the health. Both worker node is healthy.

**Comment by khilmanoj** [comment]
Can you check the logs 
kubectl logs -f alb-ingress-controller-cdd84df5d-tpx95 -n kube-system

**Comment by M00nF1sh** [comment]
Hi, seems you are using a private ALB.  Is it intended?
If not, you should add annotation `alb.ingress.kubernetes.io/scheme: internet-facing` to your ingress to make it a public ALB.
