### ISSUE TITLE
Running controller in private vpc without egress internet access

### ISSUE THREAD

**Issue by franklevering** [kubernetes-sigs/aws-alb-ingress-controller#1168]
Is it possible to run the ALB Ingress Controller in a Private VPC without internet access? Currently, when trying to deploy the controller I'm getting the following error:

`"msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: dial tcp 52.46.134.192:443: i/o timeout"`

Although I have setup a private VPC endpoint for STS, it doesn't seem to try to stay within the VPC. Therefore, is it possible to configure the ALB Ingress Controller to use a regional STS endpoint?

**Comment by john-auld** [comment]
Please see https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1085
