### ISSUE TITLE
"No OpenIDConnect provider found" error in AWS China regions with IAM Role for Service Account enabled

### ISSUE THREAD

**Issue by walkley** [kubernetes-sigs/aws-alb-ingress-controller#1180]
Just following the [deploy steps in the blog](https://aws.amazon.com/cn/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/),  there's no ALB created, below is the log in alb ingress controller:

```
E0302 12:23:02.110634       1 request_pagination.go:107] Failed request: ec2/DescribeSubnets, Payload: {  Filters: [{      Name: "tag:kubernetes.io/cluster/zhy1",      Values: ["owned","shared"]    },{      Name: "tag:kubernetes.io/role/elb",      Values: ["","1"]    }]}, Error: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.cn-northwest-1.amazonaws.com.cn/id/D00332FAF339AE6D708DF119B2EEEDB1
	status code: 400, request id: a6b3d5b9-4e2c-4cd1-ade7-4669b569e32d
E0302 12:23:02.110710       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.cn-northwest-1.amazonaws.com.cn/id/D00332FAF339AE6D708DF119B2EEEDB1\n\tstatus code: 400, request id: a6b3d5b9-4e2c-4cd1-ade7-4669b569e32d"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}
```

AWS ALB Ingress controller version: v1.1.4 & v1.1.5
eksctl: 0.15.0-rc.0, (there's a [issue](https://github.com/weaveworks/eksctl/issues/1871) in this version, need to change the trusted identity in IAM role )

**I tried to set --aws-region=cn-northwest-1 which didn't work, the workaround is adding Env variable AWS_REGION=cn-northwest-1 in the deployment.**

**Comment by M00nF1sh** [comment]
Hi, 
It's a limitation of iam-for-service-accounts features. which requires `AWS_REGION=cn-northwest-1` environment variable to work.

**Comment by dz902** [comment]
Hi @walkley, exactly same problem here. Seems the [eksctl issue](https://github.com/weaveworks/eksctl/issues/1871) was not fixed in 0.15.0, so setting AWS_REGION won't have an effect.

Or am I missing anything? Thanks.

**Comment by walkley** [comment]
> Hi @walkley, exactly same problem here. Seems the [eksctl issue](https://github.com/weaveworks/eksctl/issues/1871) was not fixed in 0.15.0, so setting AWS_REGION won't have an effect.
> 
> Or am I missing anything? Thanks.

That issue is regarding IRSA itself, specifically, it's caused by the incorrect ARN of OIDC provider in the generated IAM Role. Here the issue is AWS SDK need AWS_REGION env variable to access STS endpoint in AWS China region, otherwise it will point to AWS global STS endpoint.

**Comment by M00nF1sh** [comment]
close this, since v1.1.6 removed the need to use AWS_REGION :D

**Comment by M00nF1sh** [comment]
reference: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1198

**Comment by limouren** [comment]
I encounter a problem with the same error output as this bug with v1.1.9, but with region `us-east-2`. Adding `AWS_REGION` triggered a warning, but solved the problem. The tutorial I followed is: https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html
