### ISSUE TITLE
Error "expect one securityGroup tagged with kubernetes.io/cluster/devCluster"

### ISSUE THREAD

**Issue by ahrtr** [kubernetes-sigs/aws-alb-ingress-controller#1181]
I followed the walkthrough guide below,
```
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/walkthrough/echoserver/
```

The ALB load balancer could be created automatically, but I always see the following error,
```
E0303 01:40:06.827703       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment: expect one securityGroup tagged with kubernetes.io/cluster/devCluster on eni eni-01b7360a1de3f5518, got 0"  "controller"="alb-ingress-controller" "request"={"Namespace":"echoserver","Name":"echoserver"}
```

**Comment by hugoprudente** [comment]
Same error can occur also if there are more than 1 security group on the ENI.

```
E0315 02:48:16.615359       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment: expect one securityGroup tagged with kubernetes.io/cluster/devCluster on eni eni-00000000000000000, got 2"  "controller"="alb-ingress-controller" "request"={"Namespace":"cattle-system","Name":"rancher-alb"}
```

**Comment by spacebarley** [comment]
Hi, any updates on this issue? I'm experiencing a same issue when update to v1.1.3 from v1.1.2.

**Comment by gp42** [comment]
I can see the same issue on 1.1.6

**Comment by SidduAngadi** [comment]
I am facing same issue in EKS 1.21. Any update on this how to resolve ?

**Comment by paltaa** [comment]
The problem is that there are 2 or more security groups with the tag cluster owned, just untag and leave one security group with that tag

**Comment by rmalenko** [comment]
I have got the same issue

**Comment by awsitcloudpro** [comment]
This is still an issue with the latest version of ALB controller and EKS 1.22. I have 2 security groups attached to the ENI. Only one of them has the cluster "owned" tag, but the ALB controller keeps giving this error and fails to create target group bindings.
