### ISSUE TITLE
Specifying nodes for the ALB ingress controller

### ISSUE THREAD

**Issue by hjpotter92** [kubernetes-sigs/aws-alb-ingress-controller#1183]
In our cluster, we have setup 2 deployment services to register
an Application LB each. However, since our usage requires one of the service
to use GPU enabled AMI, we were surprised to notice that instances from
both node groups (CPU and GPU) were registering on the Application LBs
of both services.

Is there a way by which we can specify nodes which should be registered for
load balancer for a service?

We need this to implement an autoscaling rule which should step up/down
our GPU node group as a function of active connections to the ALB for the CPU
based service, and the current number of healthy hosts in the GPU dependent
service's ALB.

However, if all the nodes of a cluster are registering to all ALB; our metrics for
fetching the current count of healthy instances in a specific target group get
skewed.

Kindly suggest a way to limit registration of all instances to all ALB target groups;
and have it specified similar to how deployments in a k8s cluster have the
`nodeSelector` property.

**Comment by chrisdrobison** [comment]
We are looking for this exact same thing. We have different classes of machines and would like to control traffic via the ALB a little better.

**Comment by hjpotter92** [comment]
I raised this issue with the AWS support team as well. The suggestion they have for this is adding the following to manifest:

```yaml
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
```
