### ISSUE TITLE
Same targets being removed and added for no reason

### ISSUE THREAD

**Issue by yhware** [kubernetes-sigs/aws-alb-ingress-controller#1184]
We're using this ingress controller for our production deployments at the moment and we noticed two strange things.

1. ALB sends traffic to deregistered pods. (I'm guessing this is related to #955 and I've added 30sec preStop hook)

2. Controller keeps removing and registering the exact same target immediately after which seems to cause a few 504 errors.  Here's an example log from the controller
![log](https://user-images.githubusercontent.com/7122981/75936039-63d92e80-5ec4-11ea-88d9-5bc4f1aafa5c.png)

The 4 lines of log above happened over 2 minutes and during this period elb recorded hundreds of 504 errors. I checked events within the deployment's namespace and there was nothing. No pod restarts or failures of any kind. Is this a known behaviour?

**Comment by M00nF1sh** [comment]
@yhware 
1. Are you using instance mode? You need to disable HTTP-keep-alive in your backend or add 'connection: close' header to your response when SIGTerm have been received. (since the targets been registered is the node instead of pod)
2. We have checked a similar case, it's due to the nodes cannot report heartbeat and marked as unhealthy and thus all pods are marked as unhealthy and been removed by the controller. Would you confirm that in your audit logs?

**Comment by yhware** [comment]
Hi, thanks for the quick response :)

1. I was using IP mode and as far as I'm aware the Keep-Alive option was not explicitly enabled by the devs. I will obviously need to check on this but just as a general question, what would you consider to be the most stable setup? For apps that I wrote, I switched to instance mode upon hearing that's bit more reliable. 

2. Apparently I'm stupid enough to not turn on audit logs in EKS... even though it's literally a push of a button. So I'm afraid I cannot confirm this but since I now know better, I will check the audit logs in the future.

As a addon to the question to 1, I'm generally curious whether I should be expecting some level of 5xx responses due to pod scaling, rescheduling etc when using this controller. This may sound ignorant but I thought the controller was pretty easy to configure and get started. So I guess the question is, is there anything I should be aware / do to make my ingress reliable?
