### ISSUE TITLE
failed to reconcile managed LoadBalancer securityGroup: InvalidVpcID.NotFound:

### ISSUE THREAD

**Issue by 404-geek** [kubernetes-sigs/aws-alb-ingress-controller#1188]
I0313 07:52:16.625658       1 security_group.go:36] eng-ns/eng-web: creating securityGroup xxxxxx-xxxxx-xxxxx LoadBalancer securityGroup by ALB Ingress Controller

E0313 07:52:16.690920       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile LB managed SecurityGroup: failed to reconcile managed LoadBalancer securityGroup: InvalidVpcID.NotFound: The vpc ID 'vpc-xxxxxxxxxxx' does not exist\n\tstatus code: 400, request id: xxxxxxxxxxxxxxxxx"  "controller"="alb-ingress-controller" "request"={"Namespace":"eng-ns","Name":"eng-web"}

**Comment by cyberjso** [comment]
Hey @404-geek 

I was facing the exactly the same issue when trying to deploy  an Internet facing ALB on top of EKS 1,15. 

In my case, t[he ALB deployment spec](https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.6/docs/examples/alb-ingress-controller.yaml) was miss configured. I was using the wrong region, so the API was not able to find the VPC. 

After setting the region properly, the error message disappeared.

**Comment by M00nF1sh** [comment]
@cyberjso @404-geek 
If the controller is running on EC2-node, you don't need to specify region and vpc-id. It will automatically discover it from ec2metadata on worker nodes.

**Comment by 404-geek** [comment]
Hi @cyberjso and @M00nF1sh , I resolved the problem , I found out that i was missing the proper iam access to the resource due to which the vpc id was not found. Its resolved now.
