### ISSUE TITLE
Add new target groups and create rule in existing ALB

### ISSUE THREAD

**Issue by kirnberger1980** [kubernetes-sigs/aws-alb-ingress-controller#1191]
Hi,

We have the following requirement in our company:

Let's assume we have an application load balancer with tls on 443 with a custom domain:
- ALB Name: my-public-alb
- DomainName: *.casualcompany.com

We now want to apply deployments (with the ALB Ingress Controller) for our apps, so that for e.g. app1 we
- create a new target-group tg-app1
- create a new rule in the tls listener of my-public-alb, that when app1.casualcompany.com is the host, that it is routed to tg-app1

Is there a way to achieve this using annotations of the ingress controller?

Regards,
kirnberger

**Comment by goyertp** [comment]
Hi Team,
i would very much appreciate this solutions too.
Regards
Philipp

**Comment by M00nF1sh** [comment]
@kirnberger1980 
In V2, we will release a CRD to allow dynamically update targetGroups's targets based on k8s service. Is it what you want?
It's not available in current version.

**Comment by chris27git** [comment]
Hi,
I am also very interested in a solution @kirnberger1980 suggests. The dynamic association of target groups based on a K8s service would be very helpful regarding current use cases @M00nF1sh.

Thank you all in advance,
Chris

**Comment by kirnberger1980** [comment]
@M00nF1sh We use only one ALB for our apps. We want to add a rule to the TLS Listener, that if the Host is app1.casualcompany.com then it directs the request to the target group for app1. It would be great, if this is possible to configure this with the ingress controller (maybe in V2).

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-update-rules.html

**Comment by shukla2009** [comment]
When can we expect v2 ?

**Comment by alwibrm** [comment]
I consider this feature request very useful, too.

**Comment by kirnberger1980** [comment]
@M00nF1sh : any news on this subject? We would like to add a **rule** and a **target group** to an existing ALB listener instead of creating a dedicated one for each deployment
