### ISSUE TITLE
apigateway(aws) to ingress alb

### ISSUE THREAD

**Issue by rafaelsilvaa10** [kubernetes-sigs/aws-alb-ingress-controller#1192]
Hello, I have some applications (apis) configured in k8s, all of them have a configured ingress controller (alb) , already work normally.

However, as per my company's policy, all external apis, need to go through a gateway.
It was then that I configured the apigateway(aws) pointing to my ingress endpoint(alb). I was not successful, I believe that the apigateway(aws) works only with nlb.

Here we use basic resources of the apigateway (aws), such as auth cognito, acl waf e timeout... 

Is it worth saying that ingress (Alb) can be my final endpoint, acting as a gateway?
does anyone have this scenario? if positive, how did you treat?

Thank you all.

**Comment by M00nF1sh** [comment]
Hi, ALB supports cognito & waf. 
The missing gap between ALB and APIGW i know is throttling. 
So if ALB supports all features you need, then it can be acting as a gateway
