### ISSUE TITLE
confused with ingress scheme with cidrs

### ISSUE THREAD

**Issue by vrathore18** [kubernetes-sigs/aws-alb-ingress-controller#1194]
can someone please help me out with this option
```
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingressScheme }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ipWhiteList }}
```
1.   if my scheme is internal and i am using route53. will I am able to access the app.
2.  if I put ingressScheme as internal and inbound-cidrs as 0.0.0.0/0 is it same as external or internet-facing?

I am looking for a proper documentation of internal and external ald with inbound-cidrs. the AWS documentation link provided is not helping

**Comment by gsharm2020** [comment]
1. if my scheme is internal and i am using route53. will I am able to access the app.: Internal scheme works only within a VPC. 
So if you are using internal scheme, you will be able to access the application within the VPC only.
if I put ingressScheme as internal and inbound-cidrs as 0.0.0.0/0 is it same as external or internet-facing? : No, even if you put 0.0.0.0/0 you won't be able to access the services from outside the VPC network.
Internal means within the VPC only.
If you want to browse services from outside , then scheme should be internet-facing.

Thanks
