### ISSUE TITLE
Path based routing using ALB ingress is not working

### ISSUE THREAD

**Issue by gsharm2020** [kubernetes-sigs/aws-alb-ingress-controller#1195]
I'm trying to use path-based routing using ALB ingress  (internal scheme) as following:
[root@ip-10-0-60-180 test-lb]# cat ingresstestlb.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: test-ingress
namespace: "default"
annotations:
kubernetes.io/ingress.class: "alb"
alb.ingress.kubernetes.io/certificate-arn: xxxxx
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
alb.ingress.kubernetes.io/scheme: internal
alb.ingress.kubernetes.io/subnets: subnet-1,subnet-2
alb.ingress.kubernetes.io/security-groups: sg-xxxxx
alb.ingress.kubernetes.io/actions.test123: >
{"Type":"forward","TargetGroupArn": "xxxxx"}
spec:
rules:
- host: abcdef.com
http:
paths:
- path: /abcservices/*
backend:
serviceName: test123
servicePort: use-annotation

I'm not able to browse the service in any browser but I'm getting response from curl.

On the other hand, If I simply configure host without any path configured, I am able to browse the services.

My requirement is to use path based routing.

Please advise what I'm missing here.

Thanks

**Comment by adalandrade** [comment]
external access should be

alb.ingress.kubernetes.io/scheme: internet-facing

**Comment by gsharm2020** [comment]
@a5a5a9 No, I have to access those services within the VPC only, so that should be internal only.
I am able to browse services without path but not able to fetch the service when path is involved.

**Comment by gsharm2020** [comment]
@M00nF1sh kindly help me in this query. What's missing in my ingress that the service is not turning on the browser?
PLs help.

**Comment by M00nF1sh** [comment]
Hi,
If you can access with "CURL", then the Ingress itself is working fine. (You can turn on neywork debug from your browser to see which request is failing)

Also, i saw u are using `actions.test123` with a targetGroupArn. Is the targetGroup created outside of k8s? otherwise, use serviceName&servicePort instead.

Another thing i want to note is ALB don't support path rewrites. So your services should accept traffic at HTTP path you specified.

**Comment by gsharm2020** [comment]
Hi @M00nF1sh , thanks for checking this out.

Yes, I created target group manually and then forwarded the Ingress ALB to that target group.

It seems application is running on root not on the path specified and that's why it is not able to resolve the path.

I will check it out on this and will get back

Thanks

**Comment by gsharm2020** [comment]
Hi @M00nF1sh ,

Earlier all my were present directly inside the pod.
Now I have created a folder 'abcservices' inside the pod and then have kept my artifacts inside it.

now I am routing my ingress to abcdef.com/abcservices/* , but still it is not turning up and browser is giving my 500 error.

What I'm missing. Please help in this.
