### ISSUE TITLE
Changing security group on existing Ingress does not get applied to ENIs

### ISSUE THREAD

**Issue by christopher-wong** [kubernetes-sigs/aws-alb-ingress-controller#1203]
If I change the security group assigned to a given ALB (via the ingress manifest annotation), the ALB correctly detects the new SG, but the ENIs attached to the EKS nodes don't deterministically detect the new SG.

The only way I've been able to force the ENIs to pickup the new SGs is by manually updating them in the console.

**Comment by M00nF1sh** [comment]
Hi, it's the designed behavior.
* When the `alb.ingress.kubernetes.io/security-groups` absent, we will do two thing:
    1. create one security group for LB.
    2. attach the securityGroup created to worker node ENIs dynamically.
* When the `alb.ingress.kubernetes.io/security-groups` presents, we will only do one thing:
    1. attach the specified security group(s) to LB only.

We don't want to manage the security groups on worker nodes when `alb.ingress.kubernetes.io/security-groups` presents, since user is supposed to manage all security group related settings if they use it(and dynamically discovering ENI security groups is super inefficient).

**Comment by dorsany** [comment]
> Hi, it's the designed behavior.
> 
> * When the `alb.ingress.kubernetes.io/security-groups` absent, we will do two thing:
>   
>   1. create one security group for LB.
>   2. attach the securityGroup created to worker node ENIs dynamically.
> * When the `alb.ingress.kubernetes.io/security-groups` presents, we will only do one thing:
>   
>   1. attach the specified security group(s) to LB only.
> 
> We don't want to manage the security groups on worker nodes when `alb.ingress.kubernetes.io/security-groups` presents, since user is supposed to manage all security group related settings if they use it(and dynamically discovering ENI security groups is super inefficient).

Hi @M00nF1sh ,
In one hand, we want to keep the dynamic creation of the Security group by the ALB ingress (`create one security group for LB` and `attach the securityGroup created to worker node ENIs dynamically`)

In the other hand, we want to add additional **custom generic security groups** that has been created manually (like to support [github webhooks](https://developer.github.com/changes/2019-03-29-webhooks-ip-changes/)) to the alb. those **custom generic security groups** are also attached to other ELBs/instances and maintained in one place.

Any chance to add additional annotation like `alb.ingress.kubernetes.io/security-groups-unmanaged: sg_github_webhook` so with this annotation we will be able to keep the behavior of dynamic creation of the SG:
1. create one security group for LB.
2. attach the securityGroup created to worker node ENIs dynamically.
and
we will be able to add additional **custom generic security groups** to the ALB
3. attach the specified security group(s) to LB only.

so in the end we will get the result of 2 SGs attached to the ALB:
1 dynamic SG managed by the alb ingress
1 custom SG
