### ISSUE TITLE
Newline in clientID cause invalid HTTP/2 location header

### ISSUE THREAD

**Issue by forsberg** [kubernetes-sigs/aws-alb-ingress-controller#1204]
I'm configuring an Ingress using the OIDC authentication built into AWS ALB. I created my secret by creating two files in a directory:

```
$ ls -l oidc-secret/
total 8
-rw-r--r-- 1 forsberg forsberg 72 mar 24 08:58 clientId
-rw-r--r-- 1 forsberg forsberg 24 mar 24 08:59 clientSecret
```
I then ran kubectl as follows:

```
$ kubectl create secret generic -n namespace --from-file=oidc-secret  -o yaml ops-alb-oauth-client-data
```
I then referred to this secret in the `alb.ingress.kubernetes.io/auth-idp-oidc` annotation.

The result was very confusing, as curl would complain on the `location` header being invalid HTTP/2:

```
 http2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [location], value: [https://accounts.google.com/o/oauth2/v2/auth?client_id=GOOGLE-CLIENT-ID-REDACTED
&redirect_uri=https%3A%2F%2FDOMAIN REDACTED%2Foauth2%2Fidpresponse&response_type=code&scope=openid profile email&state=REDACTED]
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```
Turns out that since my files (clientId, clientSecret) contained a trailing newline, the location header returned by AWS ALB contained a newline, which was incorrect according to the HTTP/2 standard.

Now, this was incorrect user input, so I'm not sure it's a bug in the ingress controller, but for sure it was highly confusing, so at least this issue can serve as some help for future users. 

I think it would make sense for the ingress controller to strip newlines from the clientId/clientSecret and print out a warning about doing it, as the result of configuring a clientId with newline is just plain wrong. It could also be argued that AWS should not accept a clientId with newline.

**Comment by M00nF1sh** [comment]
I think this is indeed a usability issue. I'm not familiar with OIDC, will there be valid cases for clientId with newline?(seems there shouldn't from my understanding).
If not, we can indeed remove newlines if any.

**Comment by forsberg** [comment]
Well, the Client ID is defined in the [RFC6479 Section 2.2](https://tools.ietf.org/html/rfc6749#section-2.2) and doesn't really say much about the format, except that the string size is left undefined. 

However, in AWS, the Console Web UI for managing OIDC authentication, the input field for Client ID is a single line text input, so there's no way to add a newline. I think the fact that you can add a newline with the API is a bug.

In addition, I've never seen a Client ID with a newline being generated, neither from Google nor Azure AD - the two IdPs I've tried so far.

So I'd say the use case for having a Client ID with newline is nonexistent.
