### ISSUE TITLE
failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet for ALB

### ISSUE THREAD

**Issue by mnns** [kubernetes-sigs/aws-alb-ingress-controller#1230]
Hi all,

Tried following AWS guides, triple checked everything (even re-created the entire cluster and started from scratch), yet - still getting this error (must add AWS guides are disappointing).

Full error:
`E0420 10:20:55.139064       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet for ALB. Subnets must contains these tags: 'kubernetes.io/cluster/MainAPI': ['shared' or 'owned'] and 'kubernetes.io/role/elb': ['' or '1']. See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery for more details. Resolved qualified subnets: '[]'"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}`

I am bit confused about subnet creation as two different AWS guides instruct on different methods.
I have create 2 subnets as required when you create an EKS cluster. Then I also added 2 more subnets which are meant for public use. 

My goal is to create an EKS cluster that mainly serves one service (prod + staging), served by ALB.

Checked subnets tags. Attached some screenshots of configuration

![image](https://user-images.githubusercontent.com/1796080/79742816-15fd7600-830c-11ea-8fd5-90d72d8cee6f.png)
 
![image](https://user-images.githubusercontent.com/1796080/79742784-0aaa4a80-830c-11ea-95ab-b5755e2c703a.png)

Thanks!

**Comment by M00nF1sh** [comment]
Hi, from the screenshot, you tagged ALB with 
`kubernetes.io/role/internal-elb'. which means it's supposed to be used by vpc-internal ALB.
However, from the error logs, the controller is looking for `kubernetes.io/role/elb`, which means you are creating a public ALB. 
You should correct your tags or change your Ingress. (note: use kubernetes.io/role/elb for public subnets, and kubernetes.io/role/internal-elb for private subnets)
