### ISSUE TITLE
auth-idp-oidc auth LB get updated on every cycle (10 min)

### ISSUE THREAD

**Issue by catalinmer** [kubernetes-sigs/aws-alb-ingress-controller#1232]
Hi guys,
There is an issue with one of the ingresses, the one that uses auth oidc annotations is getting updated on every cycle run. any idea?
It happens with all versions i tried, from 1.1.2 to 1.1.6.
below is the log with the update sequence:

thank you.

**Comment by catalinmer** [comment]
> I0420 15:32:07.979073       1 controller.go:236] kubebuilder/controller "level"=1 "msg"="Successfully Reconciled"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"oauth-gateway"}
I0420 15:53:25.590443       1 log.go:30] default/oauth-gateway: listener defaultActions needs modification: [{
I0420 15:53:25.591214       1 log.go:30] default/oauth-gateway:     AuthenticateOidcConfig: {
I0420 15:53:25.591393       1 log.go:30] default/oauth-gateway:       AuthenticationRequestExtraParams: {
I0420 15:53:25.591483       1 log.go:30] default/oauth-gateway: 
I0420 15:53:25.591564       1 log.go:30] default/oauth-gateway:       },
I0420 15:53:25.591618       1 log.go:30] default/oauth-gateway:       AuthorizationEndpoint: "https://some.url/some_path/authorize",
I0420 15:53:25.591689       1 log.go:30] default/oauth-gateway:       ClientId: "some_clientid",
I0420 15:53:25.593519       1 log.go:30] default/oauth-gateway:       Issuer: "https://some.url",
I0420 15:53:25.593676       1 log.go:30] default/oauth-gateway:       OnUnauthenticatedRequest: "authenticate",
I0420 15:53:25.598730       1 log.go:30] default/oauth-gateway:       Scope: "openid",
I0420 15:53:25.598742       1 log.go:30] default/oauth-gateway:       SessionCookieName: "AWSELBAuthSessionCookie",
I0420 15:53:25.598746       1 log.go:30] default/oauth-gateway:       SessionTimeout: 86400,
I0420 15:53:25.598751       1 log.go:30] default/oauth-gateway:       TokenEndpoint: "https://some.url/some_path/token",
I0420 15:53:25.598756       1 log.go:30] default/oauth-gateway:       UserInfoEndpoint: "https://some.url/some_path/userinfo"
I0420 15:53:25.598760       1 log.go:30] default/oauth-gateway:     },
I0420 15:53:25.598765       1 log.go:30] default/oauth-gateway:     Order: 1,
I0420 15:53:25.598770       1 log.go:30] default/oauth-gateway:     Type: "authenticate-oidc"
I0420 15:53:25.598775       1 log.go:30] default/oauth-gateway:   },{
I0420 15:53:25.598780       1 log.go:30] default/oauth-gateway:     FixedResponseConfig: {
I0420 15:53:25.598801       1 log.go:30] default/oauth-gateway:       ContentType: "text/plain",
I0420 15:53:25.598806       1 log.go:30] default/oauth-gateway:       StatusCode: "404"
I0420 15:53:25.598811       1 log.go:30] default/oauth-gateway:     },
I0420 15:53:25.598816       1 log.go:30] default/oauth-gateway:     Order: 2,
I0420 15:53:25.598820       1 log.go:30] default/oauth-gateway:     Type: "fixed-response"
I0420 15:53:25.598825       1 log.go:30] default/oauth-gateway:   }] => [{
I0420 15:53:25.598831       1 log.go:30] default/oauth-gateway:     AuthenticateOidcConfig: {
I0420 15:53:25.598836       1 log.go:30] default/oauth-gateway:       AuthenticationRequestExtraParams: {
I0420 15:53:25.598840       1 log.go:30] default/oauth-gateway: 
I0420 15:53:25.598845       1 log.go:30] default/oauth-gateway:       },
I0420 15:53:25.598850       1 log.go:30] default/oauth-gateway:       AuthorizationEndpoint: "https://some.url/some_path/authorize",
I0420 15:53:25.598856       1 log.go:30] default/oauth-gateway:       ClientId: "some_clientid",
I0420 15:53:25.598861       1 log.go:30] default/oauth-gateway:       ClientSecret: "some_secret_clientid",
I0420 15:53:25.598883       1 log.go:30] default/oauth-gateway:       Issuer: "https://some.url",
I0420 15:53:25.598887       1 log.go:30] default/oauth-gateway:       OnUnauthenticatedRequest: "authenticate",
I0420 15:53:25.598893       1 log.go:30] default/oauth-gateway:       Scope: "openid",
I0420 15:53:25.598897       1 log.go:30] default/oauth-gateway:       SessionCookieName: "AWSELBAuthSessionCookie",
I0420 15:53:25.598902       1 log.go:30] default/oauth-gateway:       SessionTimeout: 86400,
I0420 15:53:25.598907       1 log.go:30] default/oauth-gateway:       TokenEndpoint: "https://some.url/some_path/token",
I0420 15:53:25.598911       1 log.go:30] default/oauth-gateway:       UserInfoEndpoint: "https://some.url/some_path/userinfo"
I0420 15:53:25.598915       1 log.go:30] default/oauth-gateway:     },
I0420 15:53:25.598920       1 log.go:30] default/oauth-gateway:     Order: 1,
I0420 15:53:25.598925       1 log.go:30] default/oauth-gateway:     Type: "authenticate-oidc"
I0420 15:53:25.598930       1 log.go:30] default/oauth-gateway:   },{
I0420 15:53:25.598934       1 log.go:30] default/oauth-gateway:     FixedResponseConfig: {
I0420 15:53:25.598956       1 log.go:30] default/oauth-gateway:       ContentType: "text/plain",
I0420 15:53:25.598962       1 log.go:30] default/oauth-gateway:       StatusCode: "404"
I0420 15:53:25.598967       1 log.go:30] default/oauth-gateway:     },
I0420 15:53:25.598972       1 log.go:30] default/oauth-gateway:     Order: 2,
I0420 15:53:25.598977       1 log.go:30] default/oauth-gateway:     Type: "fixed-response"
I0420 15:53:25.598983       1 log.go:30] default/oauth-gateway:   }]
I0420 15:53:25.598996       1 listener.go:127] default/oauth-gateway: modifying listener 443, arn: arn:aws:elasticloadbalancing:us-east-1:11111111111:listener/app/99999999-default-oauthgate-0000/11aaaaa111111a/9999999999999

**Comment by M00nF1sh** [comment]
Hi, 
The reason is we don't know the whether OIDC secret is been updated on AWS side (we cannot retrieve the secret using AWS API, so we have to keep updating it on every reconcile).

**Comment by catalinmer** [comment]
Hi,
Yeah, that's right but it I would think that it does not make sense to change it manually in AWS as long as the resource is managed by alb, so we shouldn't care in such scenario. The scenario to consider would be when the secret changed on the kubernetes side, in that case it needs to be updated in aws also.
