### ISSUE TITLE
[Question] NLB ingress controller

### ISSUE THREAD

**Issue by khacminh** [kubernetes-sigs/aws-alb-ingress-controller#1236]
Hello,

I have a question about the ingress controller for **NLB**. Will AWS implement an ingress controller for this kind of Load Balancer? I create an issue here because I cannot find the similar repo for NLB in [kubernetes-sigs](https://github.com/kubernetes-sigs) 

Thanks

**Comment by M00nF1sh** [comment]
Hi, the NLB. it's supported by the intree aws cloud provider for a service of LoadBalancerType.
(however the in-tree one only supports the instance mode of NLB).

we have been evaluating whether we should extend this ALB Ingress controller to support NLB Service(with IP mode) as well, (both alb & nlb share same elbv2 API)

**Comment by khacminh** [comment]
@M00nF1sh thank you for the information.
I really love the idea the ingress controller support NLB with IP mode.

**Comment by dnascimento** [comment]
@M00nF1sh It makes sense to use IP mode given EKS runs with CNI. Could you draft how you would like this to be implemented?
