### ISSUE TITLE
Apparent memory leak

### ISSUE THREAD

**Issue by albertollamaso** [kubernetes-sigs/aws-alb-ingress-controller#1242]
Hi guys,

We have been running an alb-ingress in our kubernetes cluster for long time (around 1 year) and this week we noticed an progressive increment of memory. You can see in the graph below the increase of the memory consuming progressively. 

![image](https://user-images.githubusercontent.com/5437164/80420375-4d39cd00-88a0-11ea-9b8f-62abda39cd69.png)

Our cluster specs:

cloud: AWS
K8s Framework: kops
3 Master Nodes
4 Woker nodes 16 GB RAM each.

We are wonder if this is a expected behavior and looking in how to mitigate it. I was  thinking to set resources limit via kubernetes policy to the pod.

Also if you can guide us where we can take a look to identify this progressive consuming of memory for the alb-ingress pod.

Thank you so much.

**Comment by achevuru** [comment]
@albertollamaso Can you share the controller version you are using in your cluster?

**Comment by albertollamaso** [comment]
@achevuru 
Image:         894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-alb-ingress-controller:**v1.0.0**

**Comment by achevuru** [comment]
@albertollamaso the above version might have some known issues around memory leaks. We do have some bug fixes that went in to subsequent releases to address these issues...For example, I see we're missing the below fix in 1.0.0

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/878

**Comment by albertollamaso** [comment]
Thank you so much @achevuru . Do you suggest me to upgrade to: v1.1.7 ? Is this the stable version?

Thanks again.

**Comment by achevuru** [comment]
@albertollamaso Yes, v1.1.7 should be good.
