### ISSUE TITLE
Error: NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by skuo** [kubernetes-sigs/aws-alb-ingress-controller#1258]
My question is similar to https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/929.  I looked through the comments but problem did not seem to have a final solution and was closed after it was idled.  Thus I am asking the question again.

I started a brand new EKS cluster using eksctl.  Then I followed the tutorial on [ALB Ingress Controller on Amazon EKS](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) and was able to start an ALB Ingress controller whose deployment yaml has the following section
```    
      spec:
      containers:
      - args:
        - --ingress-class=alb
        - --cluster-name=xxxx
        - --aws-vpc-id=vpc-0xxxx
        - --aws-region=us-west-2
        image: docker.io/amazon/aws-alb-ingress-controller:v1.1.4
        imagePullPolicy: IfNotPresent
        name: alb-ingress-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccount: alb-ingress-controller
      serviceAccountName: alb-ingress-controller
      terminationGracePeriodSeconds: 30
```
I then deployed the 2048-ingress.yaml listed below.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "2048-ingress"
  namespace: "2048-game"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: 2048-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service-2048"
              servicePort: 80
```
Tailing the alb-ingress-controller log showed the following error.  
```
W0510 20:58:08.282694       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0510 20:58:08.384371       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null}}}
I0510 20:58:08.384701       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
I0510 20:58:08.384807       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"=
I0510 20:58:08.385025       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
I0510 20:58:08.385107       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"=
I0510 20:58:08.385297       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null}}}
I0510 20:58:08.385587       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"","osImage":"","containerRuntimeVersion":"","kubeletVersion":"","kubeProxyVersion":"","operatingSystem":"","architecture":""}}}}
I0510 20:58:08.386013       1 leaderelection.go:205] attempting to acquire leader lease  kube-system/ingress-controller-leader-alb...
I0510 20:58:26.503158       1 leaderelection.go:214] successfully acquired lease kube-system/ingress-controller-leader-alb
I0510 20:58:26.603839       1 controller.go:134] kubebuilder/controller "level"=0 "msg"="Starting Controller"  "controller"="alb-ingress-controller"
I0510 20:58:26.704027       1 controller.go:154] kubebuilder/controller "level"=0 "msg"="Starting workers"  "controller"="alb-ingress-controller" "worker count"=1
E0510 21:00:04.555456       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to get AWS tags. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}
E0510 21:01:56.707461       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}
```
It's most likely the error was caused by wrong configuration.  Please advise.

Thanks in advance.

**Comment by skuo** [comment]
I am using EKS with Fargate.

**Comment by skuo** [comment]
I ended up recreating the cluster and followed the instructions in https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html and
https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html.

I had to do the following:
- Make sure I have eksctl version 0.19.0.  I ended up download it from https://github.com/weaveworks/eksctl/releases/download/0.19.0/eksctl_Darwin_amd64.tar.gz
- Downloaded `https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.2/docs/examples/iam-policy.json`  and then ran
`aws iam create-policy --policy-name ALBIngressControllerIAMPolicy --policy-document file://iam-policy.json1
- My coredns pods were stuck in the `pending` state and I had to do the following to patch it.
-- Follow the instruction in `Create a Fargate pod execution role` section of https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html
-- Follow the instruciton in `(Optional) Update CoreDNS` section of https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html

**Comment by gsabatini2016** [comment]
You only do what documentation says? Because i followed the documentation step by step and i got the same error.

**Comment by nareshmuruganbw** [comment]
Events:
  Type     Reason                Age    From                Message
  ----     ------                ----   ----                -------
  Normal   EnsuringLoadBalancer  6m44s  service-controller  Ensuring load balancer
  Warning  FailedBuildModel      6m41s  service             Failed build model due to NoCredentialProviders: no valid providers in chain. Deprecated.
           For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Having same issue, loadbalancer in pending state of IP allocation.  Any suggestions are welcome.

**Comment by zentavr** [comment]
Had you implemented [these recommendations](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#option-a-iam-roles-for-service-accounts-irsa)?
