### ISSUE TITLE
kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to load serviceAnnotation due to no object matching key after updating to EKS 1.16

### ISSUE THREAD

**Issue by krishna1250** [kubernetes-sigs/aws-alb-ingress-controller#1261]
Hi Team,

After updating the EKS 1.16, the ingress controller stopped working with below error, with the below error

kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to load serviceAnnotation due to no object matching key \"dvlp/servicename" in local store

Could somebody help me pls.

**Comment by Alien2150** [comment]
Having the same issue :/ My roughest guess some missing permission. Which Helm version are you running?

**Comment by M00nF1sh** [comment]
it's don't seems to be permission issue, do you really have the Service `servicename` in `dvlp` namespace?
Also, that error can appear if the service is not created before Ingress, and is handled by automatic retry.

**Comment by Alien2150** [comment]
@M00nF1sh solved for me: felt into this trap that alb at this point only supports services in the same namespace it seems. Any more information when this will be solved?

**Comment by krishna1250** [comment]
I have it but some reason it wouldn't pick up how ever redploying the alb ingress controller worked :)
