### ISSUE TITLE
failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment

### ISSUE THREAD

**Issue by jeffbehl** [kubernetes-sigs/aws-alb-ingress-controller#1263]
This is a duplicate of #1146 which was closed.  I'm running `
docker.io/amazon/aws-alb-ingress-controller:v1.1.7`:

`2020-05-12T16:39:48.585556193Z E0512 16:39:48.585439       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment: expect one securityGroup tagged with kubernetes.io/cluster/mycluster-dev1 on eni eni-0c0a9cd0a368c0388, got 2"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"myapp"}`

My cluster was created via [terraform-aws-eks module](https://github.com/terraform-aws-modules/terraform-aws-eks) which creates a separate security group for workers and tags this one as well with `kubernetes.io/cluster/mycluster-dev1:owned`.  Initially I was going to open a ticket with them, but the [AWS security group considerations](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html) (bottom of the page) seems to indicate multiple security groups is legitimate and doesn't warn of having multiple with the tag.  I've removed the tag from the cluster security group which has "fixed" the issue though I'm worried of the ramifications of not having it there (EKS uses it in some other way??)

I'm guessing there's a good for making this an error?

**Comment by simon-weber** [comment]
We hit this too by following AWS's instructions to migrate to a new worker node group: https://docs.aws.amazon.com/eks/latest/userguide/migrate-stack.html.

**Comment by dwradcliffe** [comment]
Same here.
