### ISSUE TITLE
One ALB for all ingress

### ISSUE THREAD

**Issue by ddiawara** [kubernetes-sigs/aws-alb-ingress-controller#1265]
Hello, everybody, I have a little problem.
In my EKS cluster, each ingress I create automatically creates an ALB, I want to move all my traffic to a single ALB.

**Comment by adw1n** [comment]
Duplicate of https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/688

**Comment by astrived** [comment]
Like @adw1n pointed this is duplicate of #688 please tag yourself to that issue.
