### ISSUE TITLE
Why not use a deployment's readinessProbe for healthchecks?

### ISSUE THREAD

**Issue by clayvan** [kubernetes-sigs/aws-alb-ingress-controller#1269]
I tried doing some searching and didn't find much, so forgive me if this gets asked a lot.

Is it possible to use a deployment's readinessProbe instead of defining healthcheck annotations on the Ingress object?

It seems like there's an unnecessary duplication of the healthcheck path/port when the information is already available through the K8s API.

It would be cool to see annotations something like

```yaml
alb.ingress.kubernetes.io/healthcheck-path: use-readiness-probe
alb.ingress.kubernetes.io/healthcheck-port: use-readiness-probe
```

**Comment by vnugent** [comment]
I'm also confused about the duplication of K8s health checks and those defined as annotations.
