### ISSUE TITLE
Cognito authentication for Ingress with multiple hosts-based rounting rules

### ISSUE THREAD

**Issue by olawaleadenagbe** [kubernetes-sigs/aws-alb-ingress-controller#1272]
Does the current version of aws-alb-ingress-controller allow you to create many host rules in the same Ingress that can authenticate with Cognito? From what I understand, you need to include the User Pool Client ID in annotation `alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:us-west-2:xxx:userpool/xxx", "UserPoolClientId":"xxx", "UserPoolDomain":"xxx"}'` and if I have more than one hosts, I would need to create as many App Clients in Cognito and specify different Callback URL for each. Can I specify more than 1 value in `UserPoolClientId` in the annotation above. I am aware that path-based routing can be used to achieve this but can it be done using host-based routing for the Ingress as well? I would like to have 1 ALB for several hosts authenticating against 1 Cognito User Pool to simulate SSO and would like to use host-based routing instead of path-based routing.

**Comment by chaitanyapoosapathi** [comment]
@olawaleadenagbe did you solve this? i am finding a solution for this as well
