### ISSUE TITLE
ALB ingress cognito The user pool domain 'DOMAIN' is not associated with the provided user pool

### ISSUE THREAD

**Issue by riosje** [kubernetes-sigs/aws-alb-ingress-controller#1280]
Hi guys, i'm getting this error:

E0601 02:38:38.587487       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to create listener due to InvalidLoadBalancerAction: The user pool domain xxxx.domain' is not associated with the provided user pool\n\tstatus code: 400, request id: eb7dd892-9ee7-4434-ac0e-11b2e37f4ad8"  "controller"="alb-ingress-controller" "request"={"Namespace":"onboarding","Name":"ingress-cognito"}

i'm with the ingress-controller version "1.1.7" and i'm sure that i put correctly the DOMAIN of the user pool.

**Comment by riosje** [comment]
Issue found, the user pool domain must be without "https"
this is confusing because in hte Cognito settings is with https, just make a comment in the config file about this plz.

{"UserPoolArn": "arn:aws:cognito-idp:<region>:<account-id>:userpool/<region><cognito-id>","UserPoolClientId":"<user-pool-client-id>","UserPoolDomain":"**<user-pool-authentication-domain>**"}

**Comment by M00nF1sh** [comment]
@riosje 
I think the comment is already there: 
```
If you are using Amazon Cognito Domain, the UserPoolDomain should be set to the domain prefix(xxx) instead of full domain(https://xxx.auth.us-west-2.amazoncognito.com)
```
