### ISSUE TITLE
Annotations per service 

### ISSUE THREAD

**Issue by trunal-vinerkar** [kubernetes-sigs/aws-alb-ingress-controller#1283]
Hi

As per the documentation, You can add kubernetes annotations to ingress and service objects to customize their behavior.
Link:https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#health-check

Can you please provide an example?
Specifically how do i use back end protocol and health check url for each service

**Comment by clayvan** [comment]
It's the same way as you would for an ingress object, just as an annotation.

Service annotations for ALB ingress take precedence over ingress annotations.

**Comment by M00nF1sh** [comment]
@clayvan is correct. 
You can refer the table here: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#annotations
If the "Location" column have "service", then you can add that annotation on service, which takes precedence.
