### ISSUE TITLE
Protect endpoints from public access

### ISSUE THREAD

**Issue by rdgacarvalho** [kubernetes-sigs/aws-alb-ingress-controller#1297]
Hi,
Is there a way to protect endpoints from public access and/or only a list of IPs to have access to it like on nginx-ingress-controller (NLB) with the snippet-server annotation?

Thanks

**Comment by M00nF1sh** [comment]
yes. check this annotation: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#inbound-cidrs

**Comment by rdgacarvalho** [comment]
Hi @M00nF1sh,

Thank you for the answer but that is not the expected solution. I want to add restrictions based on paths similar to:

```
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* ^/(metrics|healthy_check) {
      allow "127.0.0.0/32";
      deny all;
      }
```

**Comment by mmiranda** [comment]
Functional example in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1300#issuecomment-672774523_
