### ISSUE TITLE
Is there any annotation similar to nginx.ingress.kubernetes.io/server-snippet for alb-ingress-controller

### ISSUE THREAD

**Issue by rdgacarvalho** [kubernetes-sigs/aws-alb-ingress-controller#1300]
Hi,

Thank you for the answer but that is not the expected solution. I want to add restrictions based on paths similar to:

```
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* ^/(metrics|healthy_check) {
      allow "127.0.0.0/32";
      deny all;
      }
```

_Originally posted by @rdgacarvalho in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1297#issuecomment-644622800_

**Comment by M00nF1sh** [comment]
@rdgacarvalho 
You can achieve similar effect by `https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#conditions`
e.g. 
```
alb.ingress.kubernetes.io/conditions.service-name: >
      [{"Field":"source-ip","SourceIpConfig":{"Values":["192.168.0.0/16", "172.16.0.0/16"]}}]
```
will make rules with `service-name` be executed when sourceIP is within ["192.168.0.0/16", "172.16.0.0/16"]

**Comment by mmiranda** [comment]
@rdgacarvalho I totally feel your pain on this... I've been to the same coming from nginx ingress, and with alb ingress it's achievable but not that simple.

The only thing you need is an ingress like this:

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.my-service-metrics-allowed: >
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"my-real-service","ServicePort":"80"}]}}
    alb.ingress.kubernetes.io/actions.my-service-metrics-denied: >
      {"Type":"fixed-response","FixedResponseConfig":{"ContentType":"text/plain","StatusCode":"401","MessageBody":"Not
      Allowed"}}
    alb.ingress.kubernetes.io/conditions.my-service-metrics-allowed: >
      [{"Field":"source-ip","SourceIpConfig":{"Values":["10.0.0.0/8"]}}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health-check
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  name: my-ingress
spec:
  rules:
    - host: my-svc.tld.com
      http:
        paths:
          - backend:
              serviceName: my-service-metrics-allowed (a random name which matched the annotations)
              servicePort: use-annotation
            path: /metrics
          - backend:
              serviceName: my-service-metrics-denied (a random name which matched the annotations)
              servicePort: use-annotation
            path: /metrics
          - backend:
              serviceName: my-real-service (the original svc name you have)
              servicePort: 8080
            path: /*`

That will create the right rules inside your listener.
Pay attention to the order of your paths:

1. you allow /metrics endpoint for specifics ips
2. you deny /metrics
3. your regular route to /*

**Comment by rdgacarvalho** [comment]
Hey @mmiranda ,

Thank you for sharing I really appreciated that.

All the best guys @mmiranda and @M00nF1sh .
