### ISSUE TITLE
ALB Ingress controller is not able to resolve IP's from its asociated ALB subnets

### ISSUE THREAD

**Issue by mygit676** [kubernetes-sigs/aws-alb-ingress-controller#1301]
We have ALB subnets separately, the ALB need to get the IPS from those subnets. Would you please help us to understand why the ALB is reporting that it is not able to find IPS from its associated ALB subnets? 

We are getting the below error in the ALB ingress controller pod logs (V1.1.8),  though we have 500 + free IP's available

E0610 23:03:20.733544       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet with at least 8 free IP Addresses for ALB. Subnets must contains these tags: 'kubernetes.io/cluster/clustername': ['shared' or 'owned'] and 'kubernetes.io/role/internal-elb': ['' or '1']. See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery for more details. Resolved qualified subnets: '[]'"  "controller"="alb-ingress-controller" "request"={"Namespace":"cluster-addons","Name":"cluster-addons-eks-self-services-eksmgr-eks-self-service

**Comment by vkamlesh** [comment]
kubernetes.io/role/internal-elb use private subnet.

**Comment by M00nF1sh** [comment]
humm, are u the customer we live debugged yesterday? 

It not, it was due to the region is override to an incorrect region, is it same case for you?

**Comment by M00nF1sh** [comment]
closing this as it's same customer :D
