### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by fubar** [kubernetes-sigs/aws-alb-ingress-controller#1324]
I just lost a good chunk of time because the documentation at https://kubernetes-sigs.github.io/aws-alb-ingress-controller is out of date:

`alb.ingress.kubernetes.io/wafv2-acl-arn` is documented at https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/ingress/annotation.md (end of list), but it's missing on https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/

I would suggest automating updates of the docs, or doing away with them entirely in favour of the markdown version within the repo.

Thanks!

**Comment by M00nF1sh** [comment]
thanks, just published the latest documentation :D
