### ISSUE TITLE
[Question] What happens if multiple cluster uses same SG

### ISSUE THREAD

**Issue by fafalafafa** [kubernetes-sigs/aws-alb-ingress-controller#1328]
I would like to ask a question about any side effects of this scenario:

Supposedly I created another cluster which uses the same Security Group in ALB, **terraform output below** will it work on both Load balancers? 

```
      ...
      + tags                   = {
          + "Name"                                     = "eks-cluster-lb-sg"
          + "kubernetes.io/cluster/eks_cluster1" = "owned"
          + "kubernetes.io/cluster/eks_cluster2" = "owned"
        }
       ...
```

should I just create a separate LB security group for each Cluster??

thanks!

**Comment by M00nF1sh** [comment]
Hi, if you mean the securityGroup used on loadbalancer via the `alb.ingress.kubernetes.io/security-groups` annotation.
It's perfectly fine to reuse the same one across clusters.

**Comment by fafalafafa** [comment]
Just read it. Thanks!
