### ISSUE TITLE
managed node groups with alb.ingress.kubernetes.io/security-groups annotation

### ISSUE THREAD

**Issue by gevorg15** [kubernetes-sigs/aws-alb-ingress-controller#1346]
When using managed eks node groups, there is no option to specify the security group used by the nodes.  

When specifying the annotation `alb.ingress.kubernetes.io/security-groups` to use a pre-made security group for the ALB, the ingress-controller doesn't automatically create a rule to allow all traffic from the ALB security group.

How can I use managed node groups and a pre-defined security group so the limit of SGs per instance isn't reached.

**Comment by M00nF1sh** [comment]
Hi,
1. you can now use a custom securityGroup with managed node groups: https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-security-groups
You need to create the securityGroup for nodes and a securityGroup for LB and allow access from the LB securityGroup into the node securityGroup.
2. we'll add a support to use a managed LB sg(by the controller) and pre-made securityGroup together as well(https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1352)

**Comment by M00nF1sh** [comment]
closing this in favor of #1352 :D
