### ISSUE TITLE
[Question] Why bitnami/external-dns is used in examples/external-dns.yaml ?

### ISSUE THREAD

**Issue by tkms0106** [kubernetes-sigs/aws-alb-ingress-controller#1358]
When using with ALB Ingress Controller,  is there any advantages of `bitnami/external-dns` image to `asia(or eu or us).gcr.io/k8s-artifacts-prod/external-dns/external-dns` image?

I consider using ExternalDNS, but I have no idea which image I should use (I have already used ALB Ingress Controller).
Could you please give me any advice?

Thank you.

**Comment by M00nF1sh** [comment]
@tkms0106 
Hi, there is no advantage of using `bitnami/external-dns`.
You can use the official `gcr.io` from coreDNS release page.

**Comment by otterley** [comment]
The Helm `stable` chart is being deprecated: https://github.com/helm/charts/blob/master/stable/external-dns/README.md
