### ISSUE TITLE
Compatiblity with k8 cluster setup using kops

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kubernetes-sigs/aws-alb-ingress-controller#1367]
Hi,

I would like to know if this is compatible with a k8 cluster that has been setup using kops.

thanks

**Comment by M00nF1sh** [comment]
@kaykhancheckpoint 
Yes, it's compatible with kops as well. 
1. instance mode can be used.
1. IP mode can be used if either below is true:
    1. aws-vpc-cni plugin is used(kops supports it)
    2. you manage the securityGroups yourself via [alb.ingress.kubernetes.io/security-groups](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#security-groups) annotation
