### ISSUE TITLE
Slow Requests

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kubernetes-sigs/aws-alb-ingress-controller#1371]
i have setup kubernetes ingress which uses the aws alb ingress controller. If i try to access `staging.acme.com` via google-chrome or apache benchmark, **More often than not the requests takes a very long time to return a response**. 

The application for `staging.acme.com` is just forwarding a frontend so i don't expect it to take 2 minutes to load but this is also happening for the other hosts which are forwarding to an api.

I've ruled out it being an issue with the applications (web-data-test, auth-api-test) themselves because i have been running these in a different setup. Only after exposing them externally via kubernetes ingress have i noticed this problem.

**ingress**

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: staging-ingress
      namespace: test
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
        alb.ingress.kubernetes.io/certificate-arn: <redacted>, <redacted>
        alb.ingress.kubernetes.io/tags: Environment=prod,Team=dev
        alb.ingress.kubernetes.io/healthcheck-path: /health
    spec:
      rules:
        - host: staging.acme.com
          http:
            paths:
              - path: /*
                backend:
                  serviceName: web-data-test
                  servicePort: 8080
        - host: auth.staging.acme.com
          http:
            paths:
              - path: /*
                backend:
                  serviceName: auth-api-test
                  servicePort: 80
        - host: data.staging.acme.com
          http:
            paths:
              - path: /*
                backend:
                  serviceName: data-api-test
                  servicePort: 80
        - host: game.staging.acme.com
          http:
            paths:
              - path: /*
                backend:
                  serviceName: game-api-test
                  servicePort: 80

Also during the time its taking a long time to make the request im following the pod logs and i can see the healthcheck is firing every few seconds while my browser is still attempting to connect. 

Similarly i can make a request in apache bench mark and it will more often than not timeout because of this issue so i can rule out it being a browser issue. I can also rule out my internet connection because ive asked a colleague to try it and they are also experiencing the same. 

```
 - - [26/Aug/2020:17:53:48 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
- - [26/Aug/2020:17:53:48 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
- - [26/Aug/2020:17:53:49 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
- - [26/Aug/2020:17:53:49 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
- - [26/Aug/2020:17:53:58 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
 - - [26/Aug/2020:17:53:58 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
- - [26/Aug/2020:17:53:58 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
 - - [26/Aug/2020:17:53:58 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
- - [26/Aug/2020:17:53:59 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
 - - [26/Aug/2020:17:53:59 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
 - - [26/Aug/2020:17:54:08 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
 - - [26/Aug/2020:17:54:08 +0000] "GET /health HTTP/1.1" 200 4650 "-" "ELB-HealthChecker/2.0" "-"
```

**Comment by brianpursley** [comment]
Is there anything in your [ALB logs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html)?

**Comment by kaykhancheckpoint** [comment]
@brianpursley 

The following logs were taken this morning by me, no one else was using the system the logs were captured back to back 2-3 minutes apart. The first instance was no problems with loading, the second instance was problems with loading. 

In the first instance I loaded a fresh chrome browser navigated to the host, home-page loaded fine. I closed the browser and again navigated to the same host, this time it took a long time to connect.

Looking at the request_processing_time, target_processing_time and response_processing_time between the two logs there does not appear to be an issue and nothing really stands out to me as being a problem. 

Im hoping that you might be able to see something im overlooking.

1. No-problem: https://pastebin.com/fYU3TGkz
2. Problem: https://pastebin.com/jTayk5Ug

> Is there anything in your [ALB logs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html)?

**Comment by kaykhancheckpoint** [comment]
Oh! I think i may have spotted my problem. It's related to this section of the documentation. https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/walkthrough/echoserver/#deploy-ingress-for-echoserver

I have kubernetes setup using kops, i have a single VPC which is my kubernetes cluster and I only have 2 subnets. 1 subnet is public and the other is private subnet. 

> Edit the alb.ingress.kubernetes.io/subnets annotation to include at least two subnets. 

During the setup process of alb-ingress-controller i have attached tags to my 2 subnets that which correspond to my cluster name/ vpc. When i look at the application load balancer that has been created i can see  "Availability Zones " which contain both of these subnets. When i click "Edit subnets" i get the following warning message.

> You are creating an internet-facing Load Balancer, but there is no Internet Gateway attached to these subnets you have selected: subnet-<id>

Could this be the problem?
Should i create a 3rd subnet which is public and assign that to the alb rather than the private subnet?

**Comment by kaykhancheckpoint** [comment]
Follow up: I fixed the issue, for anyone who comes across this make sure subnets assigned to your load balancer are both public internet facing subnets.
