### ISSUE TITLE
Can I specify subnets explicitly, rather than relying on auto-discovery?

### ISSUE THREAD

**Issue by ipince** [kubernetes-sigs/aws-alb-ingress-controller#1378]
The documentation states that I _can_ tag my Subnets to allow the ingress controller to auto-discover them[0].  But do I _have_ to use auto-discovery?  I'd rather specify the subnets explicitly, if possible.

If setting them explicitly is not possible, can we update the documentation? As it stands, it's kind of misleading, since it implies auto-discovery is optional.

---

[0] https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/controller/config.md#subnet-auto-discovery
```
You can tag AWS subnets to allow ingress controller auto discover subnets used for ALBs.
```

**Comment by joneal** [comment]
Is this what you are looking for?  https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#subnets

**Comment by ipince** [comment]
I'm on my phone, so I cannot test, but from a quick glance, it does look
like what I want. Thanks!

Will report back in case it does not work.

**Comment by M00nF1sh** [comment]
yes, the subnets annotation will do the work :D.
