### ISSUE TITLE
Does iptables routing take place when using target-type: ip?

### ISSUE THREAD

**Issue by omnibs** [kubernetes-sigs/aws-alb-ingress-controller#1426]
Skipper says one of its benefits is [skipping iptables/conntrack altogether](https://opensource.zalando.com/skipper/kubernetes/ingress-controller/#why-skipper-uses-endpoints-and-not-services). I'm curious whether it's a benefit compared to aws-alb-ingress-controller when using `alb.ingress.kubernetes.io/target-type: ip`.

**Comment by M00nF1sh** [comment]
hi, target-type: ip cuts more hops. From the docs, the skipper pods acts as reverseProxy similar to iptables/DNAT. (so traffic is client->alb->skipper->pods)

in target-type:Ip, there is no reverseProxy between ALB and backend pods.(so traffic is client->alb->pods)

**Comment by omnibs** [comment]
Thanks, closing this as answered =]
