### ISSUE TITLE
Helm chart migration

### ISSUE THREAD

**Issue by OmriHarary** [kubernetes-sigs/aws-alb-ingress-controller#1429]
With the upcoming retirement of the Helm stable and incubator repos, is there any plan to move the incubator/aws-alb-ingress-controller to this repo, similar to what was done with ingress-nginx? So far I have not seen any mention of this project in the Helm tracking issues for the migration.

**Comment by M00nF1sh** [comment]
Hi @OmriHarary 
We plan to host the controller in our centralized https://github.com/aws/eks-charts. 
There will be a new major release and renaming coming. we will rename aws-alb-ingress-controller to be aws-load-balancer-controller, which will adds support for NLB-Service(with ip targeting) and service-apis in the near future.

**Comment by OmriHarary** [comment]
@M00nF1sh Thank you, I had not seen mention of this anywhere but maybe I wasn't looking in the right places. I am closing this issue.
