### ISSUE TITLE
E0918 05:03:12.927639       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to RequestError: send request failed\ncaused by: Post \"https://elasticloadbalancing.us-east-2a.amazonaws.com/\": dial tcp: lookup elasticloadbalancing.us-east-2a.amazonaws.com on 10.100.0.10:53: no such host"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"echoserver"}

### ISSUE THREAD

**Issue by mintenghung** [kubernetes-sigs/aws-alb-ingress-controller#1434]
Hi,
when I deploy  Kubernetes Cluster  on AWS ,

 create ALB  by https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/setup/

 , I am facing the issue below :    ( how to debug ?  )

E0918 05:56:43.755106       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to RequestError: send request failed\ncaused by: Post \"https://elasticloadbalancing.us-east-2a.amazonaws.com/\": dial tcp: lookup elasticloadbalancing.us-east-2a.amazonaws.com on 10.100.0.10:53: no such host"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"echoserver"}
E0918 06:02:57.959032       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to RequestError: send request failed\ncaused by: Post \"https://elasticloadbalancing.us-east-2a.amazonaws.com/\": dial tcp: lookup elasticloadbalancing.us-east-2a.amazonaws.com on 10.100.0.10:53: no such host"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"echoserver"}
E0918 06:03:40.216531       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to RequestError: send request failed\ncaused by: Post \"https://elasticloadbalancing.us-east-2a.amazonaws.com/\": dial tcp: lookup elasticloadbalancing.us-east-2a.amazonaws.com on 10.100.0.10:53: no such host"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"echoserver"}

**Comment by M00nF1sh** [comment]
Hi @mintenghung 
Seems it's talking to elasticloadbalancing.**us-east-2a**.amazonaws.com. which is not correct.
Did you manually specified region flag or environment variable for the controller pod to be "us-east-2a"? it should be specified as like "us-east-2", or just leave it unset and the controller will detect the correct region from EC2Metadata.

**Comment by mintenghung** [comment]
In the controller yaml file ( alb-ingress-controller.yaml ) , the region flag (--aws-region=us-east-2a) is in it.
I issue " describe pod alb-ingress-controller  " and the return message as belows.

ubuntu@ip-10-0-0-114:~$ kubectl apply -f alb-ingress-controller.yaml
deployment.apps/alb-ingress-controller created
ubuntu@ip-10-0-0-114:~$
ubuntu@ip-10-0-0-114:~$
ubuntu@ip-10-0-0-114:~$ kubectl describe pod alb-ingress-controller -n kube-system
Name:         alb-ingress-controller-567598c59-rkml5
Namespace:    kube-system
Priority:     0
Node:         ip-10-0-0-240.us-east-2.compute.internal/10.0.0.240
Start Time:   Sun, 20 Sep 2020 15:27:42 +0000
Labels:       app.kubernetes.io/name=alb-ingress-controller
              pod-template-hash=567598c59
Annotations:  <none>
Status:       Running
IP:           10.244.2.15
IPs:
  IP:           10.244.2.15
Controlled By:  ReplicaSet/alb-ingress-controller-567598c59
Containers:
  alb-ingress-controller:
    Container ID:  docker://f0ea632e28901503566aedffc5f26df1e3715e6ea429d48951986625bcc83646
    Image:         docker.io/amazon/aws-alb-ingress-controller:v1.1.9
    Image ID:      docker-pullable://amazon/aws-alb-ingress-controller@sha256:25f9edfbd56c2a5eed613ec44878ae554a6927b05d91d0992b6643e5e6613baf
    Port:          <none>
    Host Port:     <none>
    Args:
      --ingress-class=alb
      --cluster-name=kubernetes
      --aws-vpc-id=vpc-06879476b80dd7b3c
      --aws-region=us-east-2a
    State:          Running
      Started:      Sun, 20 Sep 2020 15:27:43 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      AWS_ACCESS_KEY_ID:      KEYVALUE
      AWS_SECRET_ACCESS_KEY:  SECRETVALUE
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from alb-ingress-controller-token-mcccc (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  alb-ingress-controller-token-mcccc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alb-ingress-controller-token-mcccc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From                                               Message
  ----    ------     ----  ----                                               -------
  Normal  Scheduled  31s   default-scheduler                                  Successfully assigned kube-system/alb-ingress-controller-567598c59-rkml5 to ip-10-0-0-240.us-east-2.compute.internal
  Normal  Pulled     30s   kubelet, ip-10-0-0-240.us-east-2.compute.internal  Container image "docker.io/amazon/aws-alb-ingress-controller:v1.1.9" already present on machine
  Normal  Created    30s   kubelet, ip-10-0-0-240.us-east-2.compute.internal  Created container alb-ingress-controller
  Normal  Started    30s   kubelet, ip-10-0-0-240.us-east-2.compute.internal  Started container alb-ingress-controller

ubuntu@ip-10-0-0-114:~$

**Comment by mintenghung** [comment]
I unset the region flag  and get another error message

E0921 06:47:49.515693       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 5dfaf570-c6f7-4cdc-a90a-0538daee9b8a"  "controller"="alb-ingress-controller" "request"={"Namespace":"kube-system","Name":"echoserver"}

**Comment by mintenghung** [comment]
I have create access key ID and secret access key from "My Security Credentials" on the top right.
and create alb successfully.

**Comment by M00nF1sh** [comment]
@mintenghung 
Have you resolved your issue?
BTW, you should use iam roles instead of static iam credentials to grant permissions to the controller for security

**Comment by mintenghung** [comment]
I have created role with policy  <<--- "https://kubernetes-sigs.github.io/aws-alb-ingress-controller/examples/iam-policy.json"
And alb-ingress-controller annotate the arn of the role , But it still have error message "The security token included in the request is invalid." 
So I  create access key ID and secret access key .
Then the alb has been created successfully.
