### ISSUE TITLE
[v2] Disable the webhooks?

### ISSUE THREAD

**Issue by florent-tails** [kubernetes-sigs/aws-alb-ingress-controller#1467]
Hi @M00nF1sh !

We've using the `aws-alb-ingress-controller` v1.2.0-alpha line in prod (for the Ingress Group feature of https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/914), and it's been really solid for us, so I'm stoked to see v2 is in the RC stages and gearing up to be the future of the alb-ingress-controller! Thank you for your work on this project 🙏 

We've been trying out v2.0.0-rc2, and we're finding the setup quite a bit more complicated than it used to be, with the new webhook setup and the dependency on cert-manager.

We first tried to just update to the v2 rc by just updating the docker image, but it quickly failed because of not finding the certificates needed for handling webhooks:
```
{"level":"error","ts":1601916612.0281,"logger":"setup","msg":"problem running manager","error":"open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nmain.main\n\t/workspace/main.go:150\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"}
```

After fiddling with the install and adding a self-signed certificate, v2.0.0-rc2 starts up properly and updates our ALBs as expected 🎉 

Am I right in thinking that the cert-manager dependency & the webhook functionality are just to present to enable support for readiness gates?

And if so, is there a way to disable these features if not needed, in order to avoid this extra dependency & operational complexity?

Thank you!

(PS: if currently not possible but you're open to contributions, please let me know!)

**Comment by M00nF1sh** [comment]
@florent-tails 
Hi, the webhooks is needed for both readinessGate and defaulting/validation for our new TargetGroupBinding CRD. 
Also, in the future, we'll add webhooks for Ingress/Service annotations as well.

We'll offer a helm chart:[aws-load-balancer-controller](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller) to install without cert-manager dependency(it's using a self-signed certificate). 
Will this suits your need? we can also have steps to generate a self-signed certificate if install via yaml is preferred :D

**Comment by florent-tails** [comment]
That's great @M00nF1sh ! The new dependency is the main issue, having it optional is perfect 👍 

Thanks for your answer, and I'll follow the chart development!
