### ISSUE TITLE
Ability to create alb in single AZ

### ISSUE THREAD

**Issue by gogineni99** [kubernetes-sigs/aws-alb-ingress-controller#1468]
New Feature Request: Ability to configure alb-ingress-controller with subnet in single AZ.

Currently we must specify at least two subnets in different AZ. However, in non-prod environment we want to limit the Networking costs by spinning instances and load balancers in single AZ.

Can this new feature be implemented or the restriction be removed ?

**Comment by M00nF1sh** [comment]
@gogineni99 it's a requirement enforced by ALB itself, we cannot support it in this controller.

**Comment by gogineni99** [comment]
Got it. Thanks for the info. Closing this request.
