### ISSUE TITLE
alb is being reused.

### ISSUE THREAD

**Issue by solidaeon** [kubernetes-sigs/aws-alb-ingress-controller#1470]
Hi,

I have 2 EKS clusters with their own respective nodegroups.  I deployed my application on both clusters using the same namespace.

example
Cluster1 **app1** on **myns** namespace
Cluster2 **app1** on **myns** namespace

The behavior I noticed is that the ingress in Cluster2 uses the same ALB as the ingress in Cluster1

My workaround is to deploy the same app in Cluster2 in a different namespace then Cluster2 ingress will create its own ALB.

I want to use the same namespace on both of my EKS clusters.  How can get the clusters to create their own ALB

**Comment by M00nF1sh** [comment]
did you specified same clusterName when install the controller?
You need to specify different clusterName in controller's yaml: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/alb-ingress-controller.yaml#L39

**Comment by solidaeon** [comment]
@M00nF1sh Thanks for your answer, i looked at my config of the alb-ingress-controller in Cluster2 and its true that the clusterName value points to Cluster1.  

Sorry if I forgot to mention, that Cluster1 and Cluster2 are in different aws account has no connection to each other.  

I am just wondering why the deployment in Cluster2 was successful despite that Cluster1 is not in the same account.

**Comment by M00nF1sh** [comment]
@solidaeon 
You need to specify different clusterName(use the real cluster name).
The clusterName is used by the controller to differentiate  resources from different clusters within same region.
Also, it's used to auto-discovery subnets using tags.

**Comment by M00nF1sh** [comment]
feel free to reopen if the above behavior is not expected or you have more questions :D
