### ISSUE TITLE
[v2] Allow ingress-class to be configured

### ISSUE THREAD

**Issue by kianjones4** [kubernetes-sigs/aws-alb-ingress-controller#1482]
In the v1 of the alb ingress controller, the `kubernetes.io/ingress.class` annotation that the controller would look for was configurable by setting the `ingress-class` flag (ref https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/e5c5d6e293e2b81167791ca9b2cea39fc5af7078/internal/ingress/controller/config/config.go#L68), and would like for this same functionality to be in v2.

**Comment by kishorj** [comment]
ACK. 
Work is in progress to add the ingress-class flag.

**Comment by M00nF1sh** [comment]
closing this since it's addressed by [v2.0.0-rc3 release](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v2.0.0-rc3) :D.
feel free to reopen if further issue exists.
