### ISSUE TITLE
[V2] Provided AWS iam policy no longer works

### ISSUE THREAD

**Issue by matt-demers** [kubernetes-sigs/aws-alb-ingress-controller#1494]
The policy provided at https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/v2_ga/docs/install/iam_policy.json is no longer valid for `amazon/aws-alb-ingress-controller:v2.0.0-rc3`

It looks like the default tags being put on the resources has changed from `ingress.k8s.aws/cluster`  to `elbv2.k8s.aws/cluster`. Changing all instances of `ingress.k8s.aws` to `elbv2.k8s.aws` in the iam policy document resolved the issue

**Comment by M00nF1sh** [comment]
sorry for the trouble caused. We missed to update this policy, will update it accordingly.
Also, `v2.0.0-rc3` supports Tagging for targetGroup at creation, so we'll make the policy more stricter for TargetGroups.

**Comment by M00nF1sh** [comment]
Fixed with https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1498
