### ISSUE TITLE
[V2] wafv2 not working

### ISSUE THREAD

**Issue by matt-demers** [kubernetes-sigs/aws-alb-ingress-controller#1496]
I created an ingress object with the annotation set `alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:us-east-1:<account>:regional/webacl/<stuff>"`. But I do not see the waf being associated with the load balancer. I think I traced it down to this line https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/v2_ga/pkg/config/addons_config.go#L25

I think this was meant to be
`fs.BoolVar(&f.WAFV2Enabled, flagWAFV2Enabled, defaultEnabled, "Enable WAF V2 addon for ALB")`

**Comment by kishorj** [comment]
Thanks. Will update the config.

**Comment by M00nF1sh** [comment]
closing this as v2.0.0-rc4 addressed it :D
