### ISSUE TITLE
CORS header should be configurable

### ISSUE THREAD

**Issue by DeadZen** [kubernetes-sigs/aws-alb-ingress-controller#1516]
Related but not solved regarding #1002 #1005
It does make sense to add an alb.ingress.kubernetes.io/cors-allow-methods/origin/credentials 

Should this be a feature request? I don't know, but people will run into this anytime they move to this controller.
You then need to make application level changes to migrate and support modern web browsers.

If this cannot be added, at minimum this caveat should be indicated on the front page. Thank you.

**Comment by M00nF1sh** [comment]
@DeadZen 
These cannot be supported before ALB itself supports request/response mutation.

I'll create a dedicated issue to track all these ALB feature requests next week,

**Comment by DeadZen** [comment]
Perfect, thank you for that.
