### ISSUE TITLE
ALB Ingress shows the wrong port

### ISSUE THREAD

**Issue by oguzhanaygn** [kubernetes-sigs/aws-alb-ingress-controller#1532]
In the output of "kubectl get ingress ...." command, it shows port 80 but my ingress is HTTPS only, so there is no port 80 to be exposed or directed.
Part of my ingress.yaml ;
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: kubernetes-dashboard-lb
 namespace: kubernetes-dashboard
 annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'`

and the output of "get ingress" 
`kubernetes-dashboard-lb   <none>   somehostname   someadress   80      1m`
Is it some sort of a bug or is it expected? Thank you.

**Comment by kishorj** [comment]
This behavior is not specific to AWS ALB ingress controller. For ingress objects, API server sends the port 80 (or 80, 443 if tls is configured) in response to kubectl queries. The listen port specified in the annotation is vendor specific. As long as the ALB gets provisioned with the configured ports, this should not be a controller issue.

For further details, here is the kubectl issue - https://github.com/kubernetes/kubectl/issues/500.
