### ISSUE TITLE
Compatible with Kube-Lego?

### ISSUE THREAD

**Issue by jwickens** [kubernetes-sigs/aws-alb-ingress-controller#168]
Hi, great work thank you very much for this project!

I was just wondering if this controller would be compatible with the kube-lego project to automate SSL certificates?

**Comment by joshrosso** [comment]
@jwickens Open to the idea. A low priority for our usage at the moment.

Backlogging it for now. Would likely need a proposal of how it would work and community contribution to make it happen.

Open to contributions.

**Comment by chrishiestand** [comment]
I'm currently using (or trying to use) cert-manager and aws-alb-ingress-controller. The missing piece seems to be automatically uploading the acme-provisioned TLS cert to AWS Cert Manager and then updating the ingress annotation `alb.ingress.kubernetes.io/certificate-arn`.

So the controller should watch the referenced secrets and automatically upload them when they change, and then update the ingress annotation.

**Comment by bigkraig** [comment]
I think the best way to do this is via something like Helm to add the annotation to your ingress that includes the certificate information from cert-manager.
