### ISSUE TITLE
Expose AWS Security Policy attribute

### ISSUE THREAD

**Issue by toanctruong** [kubernetes-sigs/aws-alb-ingress-controller#201]
Would be great to expose this attribute during ALB creation as the default SSL Policy doesn't meet PCI DSS standards.http://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies

**Comment by joshrosso** [comment]
Sounds like a good feature and doesn't seem to challenging to add.

Any interest in attempting to add this @toanctruong ?

**Comment by bhvr-fmarceau** [comment]
I'd also really like to be able to change the security policy since the default one is not very secure and doesn't allow meeting specific security standards..!

Any news on this issue?

**Comment by suneeta-mall** [comment]
+1 any update on this? Looks like the oldest is chosen by default (alb ingress controller 0.8). I can pick this up if no one is keen

**Comment by bigkraig** [comment]
@feltraco would you mind sending that in as a PR?

**Comment by feltraco** [comment]
Hi @bigkraig 
I didn't have added any tests, and I will not be able to do so in the short term. 
If it is OK without the tests, I can open the PR.
