### ISSUE TITLE
Re-work error handling in AssembleIngressesFromAWS

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-sigs/aws-alb-ingress-controller#213]
With https://github.com/coreos/alb-ingress-controller/pull/185 we introduced an AWS sync functionality that attempt to rebuild ALBIngresses based on resource known in AWS.

The `AssembleIngressesFromAWS` func has no error setup such that it can return an error upstream if something fails. Instead it calls logger.Fatal.

https://github.com/coreos/alb-ingress-controller/blob/0e1c716458fcd0fd228b1690be76e516f5699b1a/pkg/albingresses/albingresses.go#L104-L106

We certainly don't want this behavior considering on a failed `AssembleIngressesFromAWS` call the controller to die due to things like an inability to communicate with AWS.

**Comment by joshrosso** [comment]
While this is important, we can get away with it for now. Moving to 1.1 milestone.

**Comment by bigkraig** [comment]
Considering this is generally indicates a problem with communication with the AWS API, exiting is probably not a bad thing to bring awareness.
