### ISSUE TITLE
Autoupload of certs for use with (newly supported) SNI and host-based rules

### ISSUE THREAD

**Issue by donaldguy** [kubernetes-sigs/aws-alb-ingress-controller#238]
https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/

Would be an important step to kube-lego support (#168) I imagine

**Comment by donaldguy** [comment]
(The goal here being compliance/support for the [IngressTLS](https://kubernetes.io/docs/api-reference/v1.8/#ingresstls-v1beta1-extensions) subresource of an Ingress)

**Comment by FabianFrank** [comment]
Even without autoupload, it would be helpful to support a list of certificate ARNs instead of only a single ARN.
