### ISSUE TITLE
Ignoring existing ALBs

### ISSUE THREAD

**Issue by hrzbrg** [kubernetes-sigs/aws-alb-ingress-controller#255]
Hi,

we are currently running a Kubernetes trial in one of our AWS accounts. There are also other resources around that do not belong to the Kubernetes cluster. For example two ALBs. We wanted to utilise the alb-ingress-controller, but it seems that it can not just ignore existing ALBs in an account. 

It starts up and complains about missing tags on the existing ALBs. Is there any way to ignore them?

alb-ingress-controller: 1.0-alpha.5
Kubernetes: 1.8

Regards
hrzbrg

**Comment by joshrosso** [comment]
Hi @hrzbrg 

Can you paste the logs here? Thanks in advanced.

**Comment by hrzbrg** [comment]
```
I1023 14:50:44.009392       1 main.go:24] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I1023 14:50:44.009578       1 launch.go:112] &{ALB Ingress Controller 1.0.0 git-00000000 git://github.com/coreos/alb-ingress-controller}
I1023 14:50:44.009607       1 launch.go:115] Watching for ingress class: alb
I1023 14:50:44.009801       1 launch.go:282] Creating API client for https://100.64.0.1:443
I1023 14:50:44.019238       1 launch.go:295] Running in Kubernetes Cluster version v1.8 (v1.8.0) - git (clean) commit 6e937839ac04a38cac63e6a7a306c5d035fe7b0a - platform linux/amd64
I1023 14:50:44.020946       1 launch.go:134] validated util/alb-ingress-controller-default-backend as the default backend
I1023 14:50:44.025698       1 alb-controller.go:79] [ALB-INGRESS] [controller] [INFO]: Ingress class set to alb
I1023 14:50:44.025715       1 albingresses.go:85] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
F1023 14:50:44.172854       1 albingresses.go:142] [ALB-INGRESS] [ingresses] [ERROR]: The LoadBalancer sandbox-gatewayservice-lrr-lb does not have an IngressName tag, can't import
```

After that the container goes into CrashLoopBackOff

**Comment by joshrosso** [comment]
```
F1023 14:50:44.172854       1 albingresses.go:142] [ALB-INGRESS] [ingresses] [ERROR]: The LoadBalancer sandbox-gatewayservice-lrr-lb does not have an IngressName tag, can't import
```
Is expected. It's the controller's way of saying it won't attempt to manage that ALB. 

We'll change this error message to be `INFO` level and make the message sound less like an error.

However, the CrashLoopBackOff shouldn't happen subsequently. Could you paste the full logs so I can see exactly where the panic occurs?

**Comment by joshrosso** [comment]
@hrzbrg - My mistake, I see where this is stopping the controller now.

I'll knock it out in short order. Thanks for the report.

**Comment by hrzbrg** [comment]
Awesome, thanks. I almost thought I am crazy, because I did not find anything wrong on my side.

**Comment by joshrosso** [comment]
The query for what ALBs the controller should attempt to manage is done based on assuming the prefix of the ALB name will be what you set in the `CLUSTER_NAME` for the controller.

In your case, I presume, this was set to `sandbox`. So in your specific environment, this is the source of the conflict.

The ALB controller then incorrectly assumes it should manage it and in order to do so looks for the `IngressName` and `Namesapce` tags in AWS.

If you'd like to try the following build, I've patched it with a fix.

```
quay.io/coreos/alb-ingress-controller:1.0-alpha.5.1
```

**Comment by hrzbrg** [comment]
Perfect, thank you so much for the quick fix. Just deployed it and it works.

**Comment by hrzbrg** [comment]
Sorry, I gotta reopen this issue. I currently have two Clusters in two different AWS Accounts. The setup is basically the same, however one AWS account has existing ALBs.
On this account the Ingress Controller just hangs with the last log line being
```
I1112 11:16:22.838086       1 albingresses.go:86] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
```

I already tried using another `CLUSTER_NAME`, but it still hangs. When I launch the same ALB Ingress Controller setup in the account without existing ALBs, it works as expected. 

ALB Ingress Controller: 1.0-alpha.5.1
K8S Version: 1.8.0

**Comment by cbaigorri** [comment]
Same issue here. AWS account has existing ALB. Ingress controller last log line is the same:

```
I0114 21:34:54.082955       1 albingresses.go:87] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
```

ALB Ingress Controller: 1.0-alpha.8
K8S: 1.8

**Comment by bigkraig** [comment]
Hanging when building the list of existing ingresses is a different issue and is generally related to AWS APIs not responding or being throttled. If this is still an issue please open a new ticket. Thanks!
