### ISSUE TITLE
Enabling termination protection for ALB

### ISSUE THREAD

**Issue by utsav2307** [kubernetes-sigs/aws-alb-ingress-controller#270]
Is there any annotation available through which termination protection can be enabled for alb?

**Comment by joshrosso** [comment]
Can you expand on what you mean by termination protection?

**Comment by utsav2307** [comment]
There is an option in awsto enable termination protection on alb’s. Can the same be done from any ingress annotation?

**Comment by joshrosso** [comment]
I'm aware of Termination protection on EC2 instances (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html#Using_ChangingDisableAPITermination) but I've never seen this option for ALBs.

Could you point me to docs on where it describes the ability to add termination protection to an ALB?

**Comment by utsav2307** [comment]
Refer this document, it describes about the same:

http://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html

**Comment by bigkraig** [comment]
you will be able to do this with the `deletion_protection.enabled` attribute once #319 is merged
