### ISSUE TITLE
Does not take new target groups into use

### ISSUE THREAD

**Issue by vainu-arto** [kubernetes-sigs/aws-alb-ingress-controller#273]
On version 1.0-alpha.3, starting from a simple ingress with path / pointed to a backend. Edit the ingress to add a second path rule and point it to a different backend. The controller creates a new target group with the correct instances and port specified, and creates a new path rule. The new rule points to the target group of the original rule, and not to the new target group.

If I delete the new rule and let the controller recreate it I see the expected result of the new rule pointing at the new target group.

I haven't tested the latest version from git, so this may have been fixed since 1.0-alpha.3.

**Comment by vainu-arto** [comment]
After some more debugging, it seems that the point is that the controller waits for the target group to enter state "healthy" before taking it into use. This is a chickend and egg problem, since it remains in state "unused" until it's enabled somewhere..

**Comment by bhvr-fmarceau** [comment]
Same issue here! New target group gets created but ALB rules are never updated to use it...!

**Comment by bigkraig** [comment]
This should be resolved in the latest alphas `1.0-alpha.9`
