### ISSUE TITLE
Controller hangs building list of existing ingresses

### ISSUE THREAD

**Issue by santi698** [kubernetes-sigs/aws-alb-ingress-controller#292]
Hi!
I'm having a problem getting the controller to work, when I deploy it to my cluster it gets stuck at:
`I1228 18:42:47.478967       1 albingresses.go:85] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses`

I'm not sure if this is a bug or a problem related to my cluster configuration.

The complete log is:
```
I1228 18:42:47.465583       1 launch.go:112] &{ALB Ingress Controller 1.0.0 git-00000000 git://github.com/coreos/alb-ingress-controller}
I1228 18:42:47.465738       1 launch.go:282] Creating API client for https://100.64.0.1:443
I1228 18:42:47.473490       1 launch.go:295] Running in Kubernetes Cluster version v1.8 (v1.8.4) - git (clean) commit 9befc2b8928a9426501d3bf62f72849d5cbcd5a3 - platform linux/amd64
I1228 18:42:47.475181       1 launch.go:134] validated kube-system/default-http-backend as the default backend
I1228 18:42:47.478967       1 albingresses.go:85] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
```

Any help would be really appreciated

**Comment by cbaigorri** [comment]
I am getting the same result. Here are the logs with the `AWS_DEBUG` flag on the alb-ingress-controller:

```
I0109 03:08:19.573307       1 main.go:24] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0109 03:08:19.573517       1 launch.go:112] &{ALB Ingress Controller 1.0-alpha.7 git-ea34dc5d git://github.com/coreos/alb-ingress-controller}
I0109 03:08:19.573689       1 launch.go:282] Creating API client for https://100.64.0.1:443
I0109 03:08:19.583636       1 launch.go:295] Running in Kubernetes Cluster version v1.8 (v1.8.4) - git (clean) commit 9befc2b8928a9426501d3bf62f72849d5cbcd5a3 - platform linux/amd64
I0109 03:08:19.585260       1 launch.go:134] validated kube-system/default-http-backend as the default backend
I0109 03:08:19.590588       1 albingresses.go:87] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
I0109 03:08:19.590719       1 session.go:31] [ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/&{DescribeLoadBalancers POST / %!s(*request.Paginator=&{[Marker] [NextMarker]  }) %!s(func(*request.Request) error=<nil>)}, Payload: {
I0109 03:08:19.590734       1 session.go:31] [ALB-INGRESS] [session] [INFO]:
I0109 03:08:19.590738       1 session.go:31] [ALB-INGRESS] [session] [INFO]: }
```

**Comment by free8gent** [comment]
I recently had this problem but it was caused by an issue with dns resolution from the container not working.
Once fixed, it moved on and the alb was created. I just wish it error'd back that it couldn't resolve instead of looping and crashbackoff.

**Comment by rahulsen** [comment]
Has there been any progress on this issue ? I am facing the exact same problem.

**Comment by bigkraig** [comment]
the code will retry requests up to 20 times before giving up. most likely that is what is going on, there might be a network timeout happening with the api request and its being hidden by the retries.

https://github.com/coreos/alb-ingress-controller/blob/5879b682bb469e82a7ef4a395f78bb07603cb409/cmd/main.go#L34-L35

try setting the `AWS_MAX_RETRIES` environment variable to something low and seeing if you get a useful error message back

**Comment by tidowu** [comment]
I am experiencing this same issue "Request: elasticloadbalancing/&{DescribeLoadBalancers POST / %!s(*request.Paginator=&{[Marker] [NextMarker]  }) %!s(func(*request.Request) error=<nil>)}, Payload: {}". I tried changing that value @bigkraig and that did not help. Any help?

**Comment by bigkraig** [comment]
Check out the latest iam policy requirements https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/iam-policy.json and with the latest image `1.0-beta.2` and please re-open if this is still an issue. Thanks!
