### ISSUE TITLE
Scope AWS api calls to current VPC

### ISSUE THREAD

**Issue by jescarri** [kubernetes-sigs/aws-alb-ingress-controller#296]
alb-ingress version: `1.0-alpha.3`

Problem description:

Controller doesn't support multiple networks with the same name in different vpcs, I think the problem comes from

https://github.com/coreos/alb-ingress-controller/blob/master/pkg/aws/ec2/ec2.go#L477

because it gets the vpc by the subnet names and not via the ec2 metadata.

Also on describe actions there is no scope set to current vpc.

**Comment by bigkraig** [comment]
This was fixed a few months back
