### ISSUE TITLE
ARN: Certificate not found

### ISSUE THREAD

**Issue by toddams** [kubernetes-sigs/aws-alb-ingress-controller#299]
Version: 1.0,0.alpha-3

I copied IAM policy from examples folder, but controller could not find my SSL certificate with a following error message
````
error parsing annotations: ACM certificate ARN does not exist
````
Then I granted full access to acm and it worked

**Comment by bigkraig** [comment]
Latest versions of the code have IAM requirements that match the IAM example in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/iam-policy.json
