### ISSUE TITLE
Service kube-system/default-http-backend does not exist

### ISSUE THREAD

**Issue by toddams** [kubernetes-sigs/aws-alb-ingress-controller#301]
I have default-http-backend running on kybe-system namespace
````
default-http-backend             ClusterIP   100.66.119.198   <none>        80/TCP          4h
````
but I see a lot of messages that it does not exists, even though it is there:
````
W0111 16:07:37.846147 1 controller.go:631] service kube-system/default-http-backend does not exist
````

**Comment by cesartl** [comment]
Same here

**Comment by christopherhein** [comment]
https://github.com/coreos/alb-ingress-controller/pull/291/files should have added the proper permission
