### ISSUE TITLE
Subnet tags not matched when cluster name has lower and upper case characters

### ISSUE THREAD

**Issue by denniswebb** [kubernetes-sigs/aws-alb-ingress-controller#302]
While testing, I was using the clustername `devCluster` and was having issues with the system finding subnets tagged `kubernetes.io/cluster/devCluster` = `shared` were not being detected as usable subnets for ALBs.

I renamed the cluster to just `dev` and did the same for the subnet tag, and alb-ingress immediately found the subnets.

I can research this issue in more depth and submit a PR.  Just placing this here as a reminder.

**Comment by bigkraig** [comment]
I think this should be fixed in the latest versions. We originally lowercase'd the cluster name because it was used as a prefix for the AWS resource names. That is now a hash or separate parameter.
