### ISSUE TITLE
Allow the arg --default-backend-service to point to a url

### ISSUE THREAD

**Issue by sean-krail** [kubernetes-sigs/aws-alb-ingress-controller#303]
Right now the arg `--default-backend-service` has to point to a k8s service like `--default-backend-service=kube-system/default-http-backend`, but it'd be nice if it could also point to an external service like `--default-backend-service=https://our-domain.com/not-k8s/404`.

We're transitioning to k8s and currently have a hybrid of services, some running in VMs and others running in k8s. Right now we'd like the default backend to redirect to one of the services in our VMs.

**Comment by bigkraig** [comment]
This would take a change in https://github.com/kubernetes/ingress-nginx but it makes sense IMO

**Comment by bigkraig** [comment]
After looking closer this isn't possible, the default backend needs to be a target group which can only have ip:ports, and not specific URLs
