### ISSUE TITLE
It seems the cluster it is running with Authorization enabled (like RBAC) and there is no permissions for the ingress controller. Please check the configuration

### ISSUE THREAD

**Issue by rremella** [kubernetes-sigs/aws-alb-ingress-controller#305]
I am using kubernetes 1.9 version getting below issue , the alb-ingress controller is going on crashloop 

It seems the cluster it is running with Authorization enabled (like RBAC) and there is no permissions for the ingress controller. Please check the configuration

Can anyone let me how to resolve this issue ? Is there any permissions I need to set ?

**Comment by hmarcelodn** [comment]
I am experienced same issue as well.

**Comment by tyrannasaurusbanks** [comment]
I saw some issues with the controller in my 1.8 rbac-enabled cluster. I submitted a PR (https://github.com/coreos/alb-ingress-controller/pull/291) a few months  back with the change i needed to make, you could try apply thing to your instance

**Comment by christopherhein** [comment]
@tyrannasaurusbanks @rremella or @hmarcelodn did that work for you? I'm experiencing the same issues.

**Comment by raf-d** [comment]
This should solve your issue https://github.com/raf-d/aws-alb-controller/blob/master/RBAC-for-aws-controller.md

**Comment by bigkraig** [comment]
@raf-d do you mind sending in a PR with that RBAC info? it would help out to have it in the docs.

**Comment by bigkraig** [comment]
We've got RBAC docs in the examples folder now: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/rbac-role.yaml
