### ISSUE TITLE
Differnet backend per listener mix HTTP and HTTPS?

### ISSUE THREAD

**Issue by bsharitt** [kubernetes-sigs/aws-alb-ingress-controller#308]
It is possible at this time, or will it be possible in the future to create multiple backends, some HTTP and some HTTPS and specify which listener port listens to which backend? Currently it looks like I can specify multiple backends, but not specify which goes with with listener. Also, it appears that all backends are all HTTP or all HTTPS.

**Comment by adamdunkley** [comment]
This is super important to simplify how redirecting works. If you can specify different backends for the same host/path based on if it's http or https then you can put in a simple http to https redirect backend that does the 301 (like https://github.com/coreos/docker-nginx-https-redirect).

At the moment the only way to achieve this is to catch it in each application and do the redirect there.

What would be even nicer is if alb-ingress-controller paid attention to `ingress.kubernetes.io/ssl-redirect: "true"` for us. In ALB there is no native way to do this so we could automate spinning up a redirect service in k8s and point the http part to that service.

**Comment by bigkraig** [comment]
It's not possible. Would this be something that could be addressed by multiple ingress definitions?

**Comment by bigkraig** [comment]
Would #135 solve your problem?
