### ISSUE TITLE
Target group not getting updated

### ISSUE THREAD

**Issue by jkemp101** [kubernetes-sigs/aws-alb-ingress-controller#318]
I'm running `1.0-alpha.8` on k8s `1.8.7` and having issues with the controller not updating the target group.  The first issue was triggered by I think a bug in k8s that causes the node port to change when a service is updated even if nothing in the manifest changed.  Nonetheless, it seems like the alb controller should catch this condition and update the target group with the new node port, I had to update the port manually.

The second issue is when I add a new node to the cluster the new instance is not added to the target group.  Is there something broken with my installation keeping the target group from being updated?  The logs during these changes pretty much just have the following entries repeated.

```
I0202 14:02:36.523911       1 albingresses.go:87] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
I0202 14:02:36.687058       1 targetgroups.go:112] [ALB-INGRESS] [srvc1-t/srvc1-api-t] [INFO]: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-west-2:999999999999:targetgroup/k8s-30292-HTTP-2136d8e/e78895e92c08e769
I0202 14:02:36.746922       1 listeners.go:99] [ALB-INGRESS] [srvc1-t/srvc1-api-t] [INFO]: Fetching Rules for Listener arn:aws:elasticloadbalancing:us-west-2:999999999999:listener/app/k8s-srvc1t-srvc1ap-bf63/a373e6ad520781dd/20ee3314e7e0821f
I0202 14:02:36.759806       1 albingress.go:278] [ALB-INGRESS] [srvc1-t/srvc1-api-t] [INFO]: Ingress rebuilt from existing ALB in AWS
I0202 14:02:36.759830       1 albingresses.go:172] [ALB-INGRESS] [ingresses] [INFO]: Assembled 1 ingresses from existing AWS resources
I0202 14:03:30.193836       1 alb-controller.go:110] [ALB-INGRESS] [controller] [INFO]: Ingress update being attempted. (Forced from no event seen in 60 seconds).
I0202 14:03:30.194063       1 targetgroup.go:148] [ALB-INGRESS] [srvc1-t/srvc1-api-t] [INFO]: Start TargetGroup creation.
I0202 14:03:30.509586       1 targetgroup.go:153] [ALB-INGRESS] [srvc1-t/srvc1-api-t] [INFO]: Succeeded TargetGroup creation. ARN: arn:aws:elasticloadbalancing:us-west-2:999999999999:targetgroup/k8s-31804-HTTP-2136d8e/07adacff59af8ce9 | Name: k8s-31804-HTTP-2136d8e.
I0202 14:03:30.509850       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"srvc1-t", Name:"srvc1-api-t", UID:"5052d2c7-076a-11e8-ac97-020a1099e70e", APIVersion:"extensions", ResourceVersion:"1273097", FieldPath:""}): type: 'Normal' reason: 'CREATE' k8s-31804-HTTP-2136d8e target group created
```

**Comment by jkemp101** [comment]
After further testing and looking through the code I think my problem stemmed from the node port changing.  I think that confuses things because the port number is in the target group name.  I assume it doesn't realize it should delete the target group with the old port number and create a new one.  Once the node port changes it is no longer able to update the target group for other changes like new nodes joining the cluster.

**Comment by vincent6767** [comment]
So what is the solution?

**Comment by pampy** [comment]
We had this issue already a couple of times. I think this happens when the deployment is deleted and re-created. The service will get a new port then and the ALB Ingress Controller doesn't update the target group accordingly.

**Comment by bigkraig** [comment]
I've made some fixes to how the nodes for a TG are assembled and it may address this problem in #403

**Comment by bigkraig** [comment]
Please test with `1.0-alpha.9` and let me know how it goes

**Comment by bigkraig** [comment]
Should be resolved in later builds, currently `1.0-beta.2`

**Comment by smaslennikov** [comment]
It seems my targetgroups aren't being deleted on path changes. I'm using `quay.io/coreos/alb-ingress-controller:1.0-beta.6`

**Comment by gveltri** [comment]
I also experienced this issue while upgrading my cluster nodes. Controller for the alb ingress didn't update IP or node port on the associated target group.

**Comment by M00nF1sh** [comment]
@gveltri 
Hi, would you help check the logs from the alb-ingress-controller pod, there should be some error message that can point us to the cause.(most likely due to missing some iam permission, and the new complete set of iam permission can be viewed in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/iam-policy.json)

**Comment by arc113** [comment]
A simple redeployment helped in my case.

**Comment by tejas-js** [comment]
> I also experienced this issue while upgrading my cluster nodes. Controller for the alb ingress didn't update IP or node port on the associated target group.

Then what would be your solution for this issue. Even am also facing the same 🥲
