### ISSUE TITLE
How to exclude nodes from specific target groups?

### ISSUE THREAD

**Issue by blytheaw** [kubernetes-sigs/aws-alb-ingress-controller#325]
I have a use case to isolate a workload on a specific node in my cluster. This one node does work that utilizes a lot of bandwidth, and I would like to directly send requests to this node rather than proxy through the other nodes in my cluster.

By default, the alb-ingress-controller adds all nodes to all target groups (excluding masters). I haven't been able to find a way to exclude particular nodes or control which target groups send traffic to which Kubernetes nodes. Is this possible?

**Comment by colinmorelli** [comment]
Perhaps this is a separate issue, but it would be great if this controller supported the `alpha.service-controller.kubernetes.io/exclude-balancer` annotation that kubernetes uses by default to exclude certain nodes from being included in `LoadBalancer` services.

**Comment by ewbankkit** [comment]
[Virtual Kubelet](https://github.com/virtual-kubelet/virtual-kubelet) is an example of a node that [sets](https://github.com/virtual-kubelet/virtual-kubelet/blob/8f6b4b9e209c2597e844ea60b5401804f48ed621/vkubelet/vkubelet.go#L151) `alpha.service-controller.kubernetes.io/exclude-balancer` to `true`.

Currently if I run a VK and then attempt to create an Ingress I get errors like:

```
  Warning  ERROR   56s   ingress-controller  Error registering targets to target group xyz-31823-HTTP-0008dc6: ValidationError: Instance ID 'virtual-kubelet' is not valid
           status code: 400, request id: 9167a633-5525-11e8-96c0-dbae4da6c542
```

**Comment by bigkraig** [comment]
I've added support for `alpha.service-controller.kubernetes.io/exclude-balancer` in #403

**Comment by bigkraig** [comment]
Please test with `1.0-alpha.9` and let me know how it goes
