### ISSUE TITLE
Error from server (BadRequest): error when creating "alb-ingress-controller.yaml": Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment: Spec: v1beta1.DeploymentSpec: 

### ISSUE THREAD

**Issue by holoGDM** [kubernetes-sigs/aws-alb-ingress-controller#326]
Hello, when im trying to star alb controller according to your documentation im getting:

Error from server (BadRequest): error when creating "alb-ingress-controller.yaml": Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment: Spec: v1beta1.DeploymentSpec: 

What is strange default-backend started with same settings without problem

Changeing it to: apps/v1beta2 getting same error

**Comment by evilfrog** [comment]
@holoGDM 

Changing this:

```
# Maximum number of times to retry the aws calls.
# defaults to 20.
- name: AWS_MAX_RETRIES
  value: 20
```

To this:
```
# Maximum number of times to retry the aws calls.
# defaults to 20.
- name: AWS_MAX_RETRIES
  value: "20"
```
Solved the issue for me.

Note: quotes around numeric value.

**Comment by holoGDM** [comment]
Thank You very much. That solves my problem too :+1:
