### ISSUE TITLE
kubernetes-incubator: become a kubernetes incubator project

### ISSUE THREAD

**Issue by philips** [kubernetes-sigs/aws-alb-ingress-controller#34]
We need to put together a proposal and follow the steps ehre: https://github.com/kubernetes/community/blob/master/incubator.md

**Comment by joshrosso** [comment]
Still think this should be in the realm of consideration for us.

Let's make an attempt / proposal once we hit 1.0.

**Comment by pawelprazak** [comment]
As mentioned in #375 the [1.0 milestone](https://github.com/coreos/alb-ingress-controller/milestone/1) has only 4 issues from 2017 and all look abandoned.

Is there any work being done to upstream this project?
