### ISSUE TITLE
Cannot get Basic Auth to work on a UI deployed on K8 and using ALB Ingress

### ISSUE THREAD

**Issue by SRomero321** [kubernetes-sigs/aws-alb-ingress-controller#342]
I have a Spring Boot Microservice that is protected by Basic Authentication. When I run the app locally, a login prompt appears and I am able to login to see the UI. When I run the app on K8s with the ALB ingress controller, I go straight to the app and no Basic Auth is enabled. Is there a way to for ALB Ingress to allow Basic Auth for my app deployed on K8s. The Basic Auth is being provided by SPring Security.

**Comment by lareeth** [comment]
The ALB will not remove any authentication, however depending on how you set up your authentication, the app will see the requests coming from an internal IP, and might not require you to login. Checking the `X-Forwarded-For` headers might help, as this will show the end users (external) IP instead.

This is just a hunch, but without more information I cannot offer any more advice.
