### ISSUE TITLE
multiple domains on single alb?

### ISSUE THREAD

**Issue by dns-cdp** [kubernetes-sigs/aws-alb-ingress-controller#350]
Is it possible to have multiple domains in a single ingress/alb?

**Comment by bigkraig** [comment]
Yep, they just need to be defined within the same ingress resource currently.

**Comment by dns-cdp** [comment]
I've tried without success. It creates a single ALB, but a different Target Groups for each Services defined in the ingress file. But, the created ALB will associate with only one Target Group... ): is it normal?

**Comment by tillkahlbrock** [comment]
> Yep, they just need to be defined within the same ingress resource currently.

But that leads to the restriction that you must use the same certificate for all domains, correct @bigkraig?

**Comment by whithajess** [comment]
Left some suggestions for this restriction in #352 @tillkahlbrock

**Comment by bigkraig** [comment]
right, we need to implement support for SNI which is now being tracked in #238
