### ISSUE TITLE
Support for multiple TLS Certificates for single ALB?

### ISSUE THREAD

**Issue by adebasi** [kubernetes-sigs/aws-alb-ingress-controller#352]
We reached the max number of ALBs and would appreciate to merge these ALBs like this:
https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/

I can create an Ingress with multiple hosts, but only one annotation for a certificate arn. Is support for multiple TLS Certificates planned?

**Comment by whithajess** [comment]
@adebasi Inside AWS Certificate Manager it is possible to have a single certificate supporting multiple domains i.e `*.mydomain.com + *.myotherdomain.com` this may help you.

**Comment by tavisma** [comment]
Support for SNI would be amazing!

SAN certificates work, but are expensive and inflexible for dynamic environments

**Comment by bigkraig** [comment]
#238
