### ISSUE TITLE
ALB getting deleted when Master node is crashed

### ISSUE THREAD

**Issue by sujithnss** [kubernetes-sigs/aws-alb-ingress-controller#357]
Hi All

I'm a novice here and I got into a weird scenario where I have a Multi AZ Kubernetes Cluster on AWS. I have added ALB Ingress and able to access my application via the same ALB. Now while doing some chaos testing, I killed one of the Master node and post that my ALB also got killed and impacted my application.

Any thoughts on this please

Best Regards
Sujith P V

**Comment by bigkraig** [comment]
What do you mean by killed? If the ALB was impacted when the masters were offline it could be due to a number of cluster configurations. If the ALB was removed that is a more serious problem.

**Comment by bigkraig** [comment]
Please re-open if you still have this issue with later builds.
