### ISSUE TITLE
Add official chart to the kubernetes/charts repo

### ISSUE THREAD

**Issue by sean-krail** [kubernetes-sigs/aws-alb-ingress-controller#362]
Add an official chart to the [kubernetes/charts](/kubernetes/charts) repo. I'd rather install the chart the native way using `helm install stable/alb-ingress` (like `helm install `[`stable/nginx-ingress`](/kubernetes/charts/tree/master/stable/nginx-ingress)) than installing a plugin for helm.

**Comment by sstarcher** [comment]
Any chance this could happen before 1.0?

**Comment by rifelpet** [comment]
I can open a kubernetes/charts PR, I'm just not sure if there are any legal considerations that need to be taken with copying the alb-ingress-controller-helm directory over. It'll also require updates to the release process which would have to be addressed by this repo's owners.

**Comment by Jeeppler** [comment]
The AWS ALB Ingress Controller is now for two months in the [Helm Charts Incubator](https://github.com/helm/charts/tree/master/incubator/aws-alb-ingress-controller) repository. It would be nice if the AWS ALB Ingress Controller Chart could be promoted to the Helm Chart Stable repository.

**Comment by rifelpet** [comment]
It looks like its just a matter of promoting the chart using the documented process in charts repo:

https://github.com/helm/charts/blob/master/PROCESSES.md#promoting-a-chart-from-incubator-to-stable
