### ISSUE TITLE
Clean up orphaned TargetGroups

### ISSUE THREAD

**Issue by khrisrichardson** [kubernetes-sigs/aws-alb-ingress-controller#363]
Some TargetGroups become orphaned.

In the Kubernetes NLB PR, there was a [comment](https://github.com/kubernetes/kubernetes/pull/53400#discussion_r145478080) made about the potential for leaking target groups if a certain order weren't adhered to. This may be applicable to the alb-ingress-controller as well.

```bash
arns=(
    $(
        aws --profile ${profile} --region ${region} \
            elbv2 describe-target-groups | \
        jq -r '.TargetGroups[].TargetGroupArn' )
)
for arn in ${arns[@]}; do
    if [ $(
            aws --profile ${profile} --region ${region} \
                elbv2 describe-target-health --target-group-arn ${arn} | \
            jq '[.TargetHealthDescriptions[] | select(.TargetHealth.State != "unused")] | length'
        ) -eq 0 ]
    then
        echo ${arn}
    fi
done
```

**Comment by bigkraig** [comment]
This could be addressed by changing how we build the current state via AWS API calls. When the controller was written there was no way to query tags directly, so we fell back to naming conventions and large scans. Now that there is a tagging API where we can pull back all resources with specific tags, these things would be found.

**Comment by bigkraig** [comment]
The controller has since been updated to use the new API and fetches all managed targetgroups in one go, so it should be possible to write something now to discover excess TGs and purge them.
