### ISSUE TITLE
How to set ALB Security Policy to ELBSecurityPolicy-TLS-1-2-2017-01

### ISSUE THREAD

**Issue by davidweizheng** [kubernetes-sigs/aws-alb-ingress-controller#377]
By default, ALB Security Policy is set to ELBSecurityPolicy-2016-08. I want to set it to ELBSecurityPolicy-TLS-1-2-2017-01. I know I can manually set it after ALB is created. But is there a way to automatically do it?

**Comment by lareeth** [comment]
If you want to try https://github.com/lareeth/aws-alb-ingress-controller/tree/feature-ssl-policy this should work, will create a pull request so it can be reviewed properly

**Comment by bigkraig** [comment]
This is now supported with #415
