### ISSUE TITLE
Target group is not getting created

### ISSUE THREAD

**Issue by abidmasoodsc** [kubernetes-sigs/aws-alb-ingress-controller#378]
Hi,
I followed the steps from https://github.com/coreos/alb-ingress-controller/blob/master/docs/walkthrough.md and also setup RBAC using https://github.com/raf-d/aws-alb-controller/blob/master/RBAC-for-aws-controller.md.

Now the controller and services are up however I don't see any Target Group, I don't see any errors in the logs.

./kubectl logs -n kube-system po/alb-ingress-controller-56c9dd75f8-6q6zm

logs are like:

W0508 00:08:35.651826       1 reflector.go:326] github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1365: watch of *v1.Secret ended with: too old resource version: 874113 (874738)
I0508 00:09:57.261002       1 albingresses.go:85] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
I0508 00:09:57.261256       1 session.go:31] [ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/&{DescribeLoadBalancers POST / %!s(*request.Paginator=&{[Marker] [NextMarker]  }) %!s(func(*request.Request) error=<nil>)}, Payload: {
I0508 00:09:57.261271       1 session.go:31] [ALB-INGRESS] [session] [INFO]:
I0508 00:09:57.261277       1 session.go:31] [ALB-INGRESS] [session] [INFO]: }
I0508 00:09:57.296129       1 albingresses.go:150] [ALB-INGRESS] [ingresses] [INFO]: Assembled 0 ingresses from existing AWS resources
I0508 00:12:57.296324       1 albingresses.go:85] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
I0508 00:12:57.296555       1 session.go:31] [ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/&{DescribeLoadBalancers POST / %!s(*request.Paginator=&{[Marker] [NextMarker]  }) %!s(func(*request.Request) error=<nil>)}, Payload: {
I0508 00:12:57.296571       1 session.go:31] [ALB-INGRESS] [session] [INFO]:
I0508 00:12:57.296577       1 session.go:31] [ALB-INGRESS] [session] [INFO]: }
I0508 00:12:57.343737       1 albingresses.go:150] [ALB-INGRESS] [ingresses] [INFO]: Assembled 0 ingresses from existing AWS resources

the kube-system namespace looks like 

./kubectl get all -n kube-system
NAME          DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
ds/aws-node   3         3         3         3            3           <none>          11d

NAME                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/alb-ingress-controller   1         1         1            1           1h
deploy/default-http-backend     1         1         1            1           1h
deploy/kube-dns                 1         1         1            1           11d

NAME                                   DESIRED   CURRENT   READY     AGE
rs/alb-ingress-controller-56c9dd75f8   1         1         1         1h
rs/alb-ingress-controller-69f8cf4cf4   0         0         0         1h
rs/default-http-backend-5f497b585f     1         1         1         1h
rs/kube-dns-774d5484cc                 1         1         1         11d

NAME          DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
ds/aws-node   3         3         3         3            3           <none>          11d

NAME                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/alb-ingress-controller   1         1         1            1           1h
deploy/default-http-backend     1         1         1            1           1h
deploy/kube-dns                 1         1         1            1           11d

NAME                                   DESIRED   CURRENT   READY     AGE
rs/alb-ingress-controller-56c9dd75f8   1         1         1         1h
rs/alb-ingress-controller-69f8cf4cf4   0         0         0         1h
rs/default-http-backend-5f497b585f     1         1         1         1h
rs/kube-dns-774d5484cc                 1         1         1         11d

NAME                                         READY     STATUS    RESTARTS   AGE
po/alb-ingress-controller-56c9dd75f8-6q6zm   1/1       Running   0          1h
po/aws-node-2lvsn                            1/1       Running   0          11d
po/aws-node-88dph                            1/1       Running   0          11d
po/aws-node-fgv8k                            1/1       Running   0          11d
po/default-http-backend-5f497b585f-g6z55     1/1       Running   0          1h
po/kube-dns-774d5484cc-jqxrq                 3/3       Running   0          11d

NAME                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
svc/default-http-backend   ClusterIP   10.100.0.124   <none>        80/TCP          1h
svc/kube-dns               ClusterIP   10.100.0.10    <none>        53/UDP,53/TCP   11d

The ingress controller looks like

/kubectl describe ing -n hello-service
Name:             hello-service
Namespace:        hello-service
Address:
Default backend:  default-http-backend:80 (10.10.10.10:8080)
Rules:
  Host                     Path  Backends
  ----                     ----  --------
  hello-service.foodbar.com
                           /   hello-service:8051 (<none>)

I also tagged by Subnets with kubernetes.io/role/alb-ingress

**Comment by bigkraig** [comment]
I'll need to see more log lines after the `Assembled 0 ingresses from existing AWS resources` line. At that point the state is assembled from the existing AWS resources but it doesn't mean that the controller has received ingresses from Kubernetes.
