### ISSUE TITLE
Two small regressions encountered?

### ISSUE THREAD

**Issue by GeekyTex** [kubernetes-sigs/aws-alb-ingress-controller#386]
Encountered a couple issues when attempting to build master and deploy it as my ALB Ingress Controller.

I pulled master and built it because I was encountering an intermittent error with the 1.0-alpha.3 release where tags were not getting set properly to a managed security group, resulting in the security group not being found during the polling/modifying cycles. I pulled master to see if that problem had been addressed. It looks like it has.

However, I encountered a couple of issues immediately with master. I've already addressed them in a fork of the project (and have created a PR), but figured I'd open an issue as well so it's easier to track.

Environment details: I'm testing with a Kops (1.9.0) deployed cluster on top of AWS, using CNI and a private topology (Weave as my networking layer).

Both issues look to be fairly recent regressions.

Issue 1: After a recent code update, the cluster name is no longer passed explicitly to the ParseAnnotations method; rather the value is attempted to get grabbed directly from an ingress type in a nested object. In my testing, I found the clusterName was not available in that type. This broke the controller's ability to find properly tagged subnets to deploy an ALB into since the clusterName was nil.

Issue 2: In my testing, the master branch build of the controller would crash with a seg fault when attempting to deploy an ingress/ALB that did not already exist. This looks to occur because another recent commit attempts to grab a target group Arn for a target group that does not currently exist. Added some safety logic around that call.

**Comment by GeekyTex** [comment]
See #385 for code changes I made.

**Comment by bigkraig** [comment]
Resolved as of #418
