### ISSUE TITLE
Improve annotation parsing error messages

### ISSUE THREAD

**Issue by btsteve** [kubernetes-sigs/aws-alb-ingress-controller#443]
When i try and setup my ingress controller i am getting this error:

'Warning' reason: 'ERROR' Error parsing annotations: Necessary annotations missing. Must include alb.ingress.kubernetes.io/scheme (cache hit)

This is my ingress definition:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "travis-demo-ingress"
  namespace: "travis-demo"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 5
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 10
    alb.ingress.kubernetes.io/healthy-threshold-count: 2
    alb.ingress.kubernetes.io/unhealthy-threshold-count: 3
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:12345:certificate/eeba1e5d-d10a-4b29-bf36-b32
    alb.ingress.kubernetes.io/success-codes: 200
  labels:
    app: travis-demo 
spec:
  rules:
  - host: q3.dev.urjanet.net
    http:
      paths:
      - path: /
        backend:
          serviceName: "travis-demo-service"
          servicePort: 8181

I have the scheme defined. I have tried it as internal, internet-facing, and "internet-facing" all get the same error. 
I am testing this out on EKS kubernetes 1.10

**Comment by Labbs** [comment]
Hello,

Same issue, and eks too.
alb-controller : latest version (sha256:c7c6e8af9ede053078b07abc5c006114cbd296a467b8266033665e9ac557984d)
On anothers clusters (1.8.4/1.9.2) and with latest version of alb-controller, i don't have this problem.

**Comment by Labbs** [comment]
My problem is related to alb.ingress.kubernetes.io/successCodes and alb.ingress.kubernetes.io/connection-idle-timeout.

The numbers must be between quotes.

No issue for me.

**Comment by bigkraig** [comment]
I'm going to change this to a feature request, that error message should be much more specific about the problem its having.

**Comment by Labbs** [comment]
Thank you, it will prevent others from having the same problem with a more specific error message.

**Comment by bigkraig** [comment]
This is improved in master now, the next beta release will include it.
