### ISSUE TITLE
Documentation lacks required route53 iam rights

### ISSUE THREAD

**Issue by o0st** [kubernetes-sigs/aws-alb-ingress-controller#445]
I found it hard to determinate minimal set of route53 rights which controller requires.
It would be nice to have theme somewhere in the [example iam policy](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/iam-policy.json) or as separate one.

**Comment by bigkraig** [comment]
The controller doesn't manage route53, the [external-dns controller](https://github.com/kubernetes-incubator/external-dns) is the recommended method to manage DNS.

**Comment by o0st** [comment]
Why then the controller performs create/update/delete route53 requests (I'm on `alb-ingress-controller-helm-0.0.10`)?
