### ISSUE TITLE
Confusion about NodePort and target-type

### ISSUE THREAD

**Issue by cjbottaro** [kubernetes-sigs/aws-alb-ingress-controller#458]
Hello.

It seems like services _must_ be of type `NodePort`, is that correct?

I can't tell from looking at the examples when one can use `alb.ingress.kubernetes.io/target-type: pod`. One uses the annotation and one does not, but services and deployments look similar.

Thanks!

**Comment by cjbottaro** [comment]
Looks like services do need to be `NodePort`.

And `target-type: pod` seems to work for me. ¯\\\_(ツ)_/¯

**Comment by bigkraig** [comment]
The `NodePort` requirement is for `target-type: instance`.  It's not really required for `pod`, I just need to make the adjustments.

**Comment by cjbottaro** [comment]
Adjustments in the documentation/examples or code? I just tried `ClusterIP` with `target-type: pod` and got this:

```
E0715 16:15:02.301925       1 albingress.go:139] [ALB-INGRESS] [default/load-balancer] [ERROR]: Error instantiating load balancer: default/sa-api service is not of type NodePort
I0715 16:15:02.301969       1 controller.go:486] ingress backend successfully reloaded...
I0715 16:15:02.301970       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"load-balancer", UID:"39d9b5f6-884a-11e8-a69e-1254143763fe", APIVersion:"extensions", ResourceVersion:"3006074", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error instantiating load balancer: default/sa-api service is not of type NodePort
```

Using `beta3`.

**Comment by bigkraig** [comment]
In the code
