### ISSUE TITLE
CrashLoopBackOff issue

### ISSUE THREAD

**Issue by deepakpanda1** [kubernetes-sigs/aws-alb-ingress-controller#459]
kubectl describe pod/alb-ingress-controller-665468b9b5-kn6m5  -n kube-system
Name:           alb-ingress-controller-665468b9b5-kn6m5
Namespace:      kube-system
Node:           ip-10-0-2-66.ec2.internal/10.0.2.66
Start Time:     Mon, 16 Jul 2018 14:25:46 +0530
Labels:         app=alb-ingress-controller
                pod-template-hash=2210246561
Annotations:    <none>
Status:         Running
IP:             10.0.2.183
Controlled By:  ReplicaSet/alb-ingress-controller-665468b9b5
Containers:
  server:
    Container ID:  docker://9b2a885c5b05460fbfc18bba35d53a58c97684c1491fdd6139843982a656f6e5
    Image:         quay.io/coreos/alb-ingress-controller:1.0-beta.3
    Image ID:      docker-pullable://quay.io/coreos/alb-ingress-controller@sha256:7cfef34c882a14d9ecb17a4d13feae6a738230d73505fdf7f93fe102c12f36ef
    Port:          <none>
    Host Port:     <none>
    Args:
      /server
      --default-backend-service=kube-system/default-http-backend
      --ingress-class=alb
    State:          Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 16 Jul 2018 14:26:30 +0530
      Finished:     Mon, 16 Jul 2018 14:26:30 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 16 Jul 2018 14:26:03 +0530
      Finished:     Mon, 16 Jul 2018 14:26:03 +0530
    Ready:          False
    Restart Count:  3
    Environment:
      AWS_REGION:             us-east-1
      CLUSTER_NAME:           xxxxxxxxxxx
  
      AWS_DEBUG:              false
      AWS_MAX_RETRIES:        20
      POD_NAME:               alb-ingress-controller-665468b9b5-kn6m5 (v1:metadata.name)
      POD_NAMESPACE:          kube-system (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-v5k9q (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-v5k9q:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-v5k9q
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                From                                Message
  ----     ------                 ----               ----                                -------
  Normal   Scheduled              53s                default-scheduler                   Successfully assigned alb-ingress-controller-665468b9b5-kn6m5 to ip-10-0-2-66.ec2.internal
  Normal   SuccessfulMountVolume  53s                kubelet, ip-10-0-2-66.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-v5k9q"
  Normal   Pulling                10s (x4 over 53s)  kubelet, ip-10-0-2-66.ec2.internal  pulling image "quay.io/coreos/alb-ingress-controller:1.0-beta.3"
  Normal   Pulled                 10s (x4 over 52s)  kubelet, ip-10-0-2-66.ec2.internal  Successfully pulled image "quay.io/coreos/alb-ingress-controller:1.0-beta.3"
  Normal   Created                10s (x4 over 52s)  kubelet, ip-10-0-2-66.ec2.internal  Created container
  Normal   Started                9s (x4 over 52s)   kubelet, ip-10-0-2-66.ec2.internal  Started container
  Warning  BackOff                9s (x5 over 49s)   kubelet, ip-10-0-2-66.ec2.internal  Back-off restarting failed container

**Comment by bigkraig** [comment]
Can you get the pod log? Add a `-p` to get the crashed pods log.
