### ISSUE TITLE
Managed security groups do not work with target-type: pod

### ISSUE THREAD

**Issue by bigkraig** [kubernetes-sigs/aws-alb-ingress-controller#467]

**Comment by dhawani** [comment]
+1 
Infant if we manually add the ingress group created to instances and the pod restarts, it fails to start up the pod with following errors:

`I0720 06:52:10.292915       1 session.go:35] [ALB-INGRESS] [session] [INFO]: Request: ec2/DescribeSecurityGroups, Payload: {  Filters: [{      Name: "ip-permission.group-id",      Values: ["sg-*****"]    }]}
I0720 06:52:10.329699       1 albingresses.go:187] [ALB-INGRESS] [ingress] [INFO]: Failed to find related managed instance SG. Was it deleted from AWS? Error: Didn't find exactly 1 matching (managed) instance SG. Found 2`

**Comment by bigkraig** [comment]
I think the managed security group code needs to be refactored as a part of this, its spread out all over the place.
