### ISSUE TITLE
Support for default target type

### ISSUE THREAD

**Issue by dhawani** [kubernetes-sigs/aws-alb-ingress-controller#471]
In EKS, target-type = instance doesn't work. We need to add target-type=pod annotation in all ingress controller. Instead, can we add an ability to specify default target-type at controller configuration instead ? 

This is a follow-up request on #343

**Comment by bigkraig** [comment]
Makes sense to me. I am currently working on an upgrade and import of the upstream ingress library into this codebase and I can get on this after that.

**Comment by bigkraig** [comment]
@dhawani LMK how #492 looks to you
