### ISSUE TITLE
Named port doesn't work

### ISSUE THREAD

**Issue by dhawani** [kubernetes-sigs/aws-alb-ingress-controller#472]
I am running ALB Ingress Controller 1.0-beta.4 on EKS.

While installing keycloak with ingress, i get following error in controller pod:
`I0720 07:19:30.097492       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"keycloak", UID:"d0f591c7-8bec-11e8-b0fe-0e613369a9ca", APIVersion:"extensions", ResourceVersion:"2301136", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error instantiating load balancer: Unable to find a port defined in the default/keycloak-http service`

The problem is that ALB Ingress Controller is not supporting named port. Refer [L35 in keycloak helm chart](https://github.com/helm/charts/blob/master/stable/keycloak/templates/ingress.yaml#L35)

Refer this PR https://github.com/kubernetes/ingress-nginx/pull/1607

**Comment by bigkraig** [comment]
You may want to look at #529

**Comment by bigkraig** [comment]
@dhawani it was working in my testing, check with `latest`?

**Comment by masterkain** [comment]
![Screenshot 2019-11-02 at 00 51 01](https://user-images.githubusercontent.com/12844/68070918-eca85800-fd74-11e9-8452-1c255b5c0d89.png)
