### ISSUE TITLE
Session Affinity support

### ISSUE THREAD

**Issue by argeualcantara** [kubernetes-sigs/aws-alb-ingress-controller#496]
Hi, I'd like to know how is the session affinity support in the ALB ingress controller, we have some annotations for the nginx ingress controller to make session affinity work:
```
nginx.ingress.kubernetes.io/affinity: "cookie"
nginx.ingress.kubernetes.io/session-cookie-name: "my-cookie"
nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
```
Are they supported by the ALB Ingress controller? Are they on the roadmap?
Thanks

**Comment by bigkraig** [comment]
You can set up attributes using annotations. Check out https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html. I don't think that you can customize the cookie.
