### ISSUE TITLE
Inconsistency in the Walk-through.

### ISSUE THREAD

**Issue by redduck3** [kubernetes-sigs/aws-alb-ingress-controller#499]
I followed the tutorial and met the following error.
``` bash
> kubectl logs alb-ingress-controller-6569f8b94b-bmglg -n kube-system
I0730 09:24:53.099981       1 launch.go:112] &{ALB Ingress Controller 1.0-beta.4 git-385f5365 git://github.com/kubernetes-sigs/aws-alb-ingress-controller}
I0730 09:24:53.100066       1 launch.go:115] Watching for ingress class: alb
F0730 09:24:53.100108       1 launch.go:119] Please specify --default-backend-service

```
Accidentally, I found out the latest commit message of the master branch was 'further removal of the default backend'(393cb0151a23c6129545e9b4ad2c7185a6e93c3b). So I modified the file `alb-ingress-controller.yaml`, updating image to `quay.io/coreos/alb-ingress-controller:latest`. The issue was resolved in this method but there is still some inconsistency in the documentation. https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/alb-ingress-controller.yaml#L82

By the way, the `rbac-role` must be created before deploying an alb-ingress-controller. The walkthrough does not mention this step.

**Comment by bigkraig** [comment]
Resolved in #523, thanks!
