### ISSUE TITLE
Ingress Nginx Warning logs

### ISSUE THREAD

**Issue by anhpham1509** [kubernetes-sigs/aws-alb-ingress-controller#500]
I notified this line when checking the logs of the pod running ingress controller:
```
W0730 11:00:21.914240       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```
I took a look through and found out that might be related to ingress-nginx stuff.

Though it's warning logs, please clarifies this problem.

<img width="1630" alt="screen shot 2018-07-30 at 14 11 59" src="https://user-images.githubusercontent.com/9955754/43394297-e67f1932-9402-11e8-8421-65bff4c5961c.png">

**Comment by bigkraig** [comment]
This is part of the upstream Kubernetes client
