### ISSUE TITLE
Latest alb controller image does not forward to https service

### ISSUE THREAD

**Issue by blandman** [kubernetes-sigs/aws-alb-ingress-controller#501]
Using the annotation `alb.ingress.kubernetes.io/backend-protocol: HTTPS`, the server responds with the following https error:
```
The webpage at https://dns-name/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_PROTOCOL_ERROR
```

Previous builds accepted this annotation correctly and forwarded the alb to the correct port. Inspecting Target Groups, no target has been assigned.

The alb controller has this error in logs
```
I0730 16:17:03.481867       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"dashboard", UID:"ee31ddc6-8b66-11e8-8ce8-020c615fc996", APIVersion:"extensions/v1beta1", ResourceVersion:"2663343", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error creating target group 8709014d-00000-HTTP-267077f: InvalidParameter: 1 validation error(s) found.
- minimum field value of 1, CreateTargetGroupInput.Port.
```

The oldest working image is 3dab68a, 1173989 is where the issue began.

**Comment by bigkraig** [comment]
I started to look into this and so far i'm not seeing what could be causing this problem, but the healthchecks were being made with the wrong backend protocol. You may want to look at `501-fix-backend-protocol` and see if that changes anything

**Comment by blandman** [comment]
Thank you, I can confirm 1.0-beta.5 no longer has this issue.
