### ISSUE TITLE
Reconcile doesn't validate SG configurations

### ISSUE THREAD

**Issue by bigkraig** [kubernetes-sigs/aws-alb-ingress-controller#509]
SG attachments and changes are done at creation but are not tracked and managed during the reconcile process.

**Comment by bigkraig** [comment]
@argeualcantara I don't think so, what I was referring to in this issue was if someone removed the SG association manually, the controller would not detect this and re-add it.

You may want to upgrade to `1.0-beta.5` and see if your problem persists. Adding or removing the annotation to an existing ingress should be allowed.

**Comment by M00nF1sh** [comment]
@argeualcantara @bigkraig 
both issue should be resolved by https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/614
