### ISSUE TITLE
AccessDeniedException: User is not authorized to access the web ACL

### ISSUE THREAD

**Issue by kumudt** [kubernetes-sigs/aws-alb-ingress-controller#520]
Looks like there was some error in the IAM policy example. Whenever, I set a WebACL annotation on one of the ingresses, I get the following errors.
```
AccessDeniedException: User is not authorized to access the web ACL
```
The issue is that policy doesn't have access to the waf-regional resources.

ALB Ingress Controller Version: on both v1.0-beta4 and v1.0-beta5.

Issue got resolved after making some changes to the policy. Will create a PR for the same.

**Comment by anhpham1509** [comment]
@kumudt  I think the example policy had it already:

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/iam-policy.json#L70

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/iam-policy.json#L81

**Comment by kumudt** [comment]
@anhpham1509 It needs 
```
"waf-regional:GetWebACLForResource",
"waf-regional:GetWebACL",
"waf-regional:AssociateWebACL",
"waf-regional:DisassociateWebACL",
"waf:GetWebACL"
```

**Comment by kumudt** [comment]
These are invalid IAM Policy Rules
```
"waf:AssociateWebACL",
"waf:DisassociateWebACL"
```
