### ISSUE TITLE
Ingress controller crash with health check

### ISSUE THREAD

**Issue by lemonshow** [kubernetes-sigs/aws-alb-ingress-controller#526]
Below the new annotation I am trying,

alb.ingress.kubernetes.io/healthcheck-interval-seconds: 75
alb.ingress.kubernetes.io/healthcheck-path: /xyz/v1/ready
alb.ingress.kubernetes.io/healthcheck-port: 31822
alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 10
alb.ingress.kubernetes.io/healthy-threshold-count: 1
alb.ingress.kubernetes.io/unhealthy-threshold-count: 10
alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01

Log:----------------
I0802 04:41:25.806395       1 status.go:193] new leader elected: alb-ingress-controller-b994cdddc-n9gnv
I0802 04:41:25.856444       1 controller.go:486] ingress backend successfully reloaded...

I0802 04:46:06.874158       1 controller.go:1359] starting Ingress controller
I0802 04:46:06.878473       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"dev-ysuntestapp-ingress", UID:"xxx--c6", APIVersion:"extensions", ResourceVersion:"2711617", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress local/dev-ysuntestapp-ingress
I0802 04:46:07.605114       1 leaderelection.go:174] attempting to acquire leader lease...
I0802 04:46:07.605305       1 controller.go:477] backend reload required
I0802 04:46:07.610182       1 status.go:193] new leader elected: alb-ingress-controller-1114cdddc-n9gnv
E0802 04:46:07.658589       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:522
/home/travis/.gimme/versions/go/src/runtime/panic.go:513
/home/travis/.gimme/versions/go/src/runtime/panic.go:82
/home/travis/.gimme/versions/go/src/runtime/signal_unix.go:390
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/aws/albec2/ec2.go:725
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations/annotations.go:495
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations/annotations.go:154
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingress.go:99
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingresses.go:53
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller/alb-controller.go:217
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller/alb-controller.go:200
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:479
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:175
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:89
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x144dd73]

goroutine 123 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1829aa0, 0x2e2c810)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/aws/albec2.ClusterSubnets(0x0, 0xc00004004d, 0xa, 0xc000492cf0, 0x2e650a0, 0x43c8c3, 0x16f4700, 0x380, 0xc00049a900)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/aws/albec2/ec2.go:725 +0x73
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations.(*Annotations).setSubnets(0xc000409400, 0xc0002865a0, 0xc00004004d, 0xa, 0xc000492cf0, 0x1c8de80, 0x2e63fd8, 0x2e63fd8, 0x1c6d080)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations/annotations.go:495 +0x1387
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations.(*ValidatingAnnotationFactory).ParseAnnotations(0xc00032bee0, 0xc0000adbc0, 0x0, 0x0, 0x4719d2)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations/annotations.go:154 +0x774
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress.NewALBIngressFromIngress(0xc0003bf200, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingress.go:99 +0x1ec
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress.NewALBIngressesFromIngresses(0xc0004d5908, 0xc0004c4d00, 0x1, 0x1)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingresses.go:53 +0x2d1
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller.(*albController).update(0xc0002c28c0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller/alb-controller.go:217 +0x386
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller.(*albController).OnUpdate(0xc0002c28c0, 0xc000643780, 0x3, 0x3, 0xc0005a6028, 0x1, 0x1, 0x2e63fd8, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller/alb-controller.go:200 +0x2b
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress(0xc0001f4000, 0x171d760, 0xc0002947a0, 0xc0002947a0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:479 +0x7b8
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress-fm(0x171d760, 0xc0002947a0, 0xa, 0xc000729620)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:175 +0x3e
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc0003c6330)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:89 +0x115
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker-fm()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007297a8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004d5fa8, 0x3b9aca00, 0x0, 0xc00073e101, 0xc0002b62a0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0007297a8, 0x3b9aca00, 0xc0002b62a0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc0003c6330, 0x3b9aca00, 0xc0002b62a0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5d
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1390 +0x4a8
(provision-nKrhB7O9) bash-3.2$

**Comment by bigkraig** [comment]
Please update to `1.0-beta.5`
