### ISSUE TITLE
With beta.5 subnet tagging validation errors still seen with health-check

### ISSUE THREAD

**Issue by lemonshow** [kubernetes-sigs/aws-alb-ingress-controller#530]
I was hitting other permission issues with beta.5 so I closed previous issue.

Actually I am hitting this again with beta.5 now. 
With below health-check interval,
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 75
The path setting works for me, but above line together I am seeing the error.
    alb.ingress.kubernetes.io/healthcheck-path: /myapp/v1/ready

I0805 03:01:25.431286       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"dev-ysuntestapp-ingress", UID:"xxxxxxx", APIVersion:"extensions/v1beta1", ResourceVersion:"3100426", FieldPath:""}): type: 'Warning' reason: 'ERROR' error parsing annotations: Retrieval of subnets failed to resolve 2 qualified subnets. Subnets must contain the kubernetes.io/cluster/<cluster name> tag with a value of shared or owned and the kubernetes.io/role/internal-elb tag signifying it should be used for ALBs Additionally, there must be at least 2 subnets with unique availability zones as required by ALBs. Either tag subnets to meet this requirement or use the subnets annotation on the ingress resource to explicitly call out what subnets to use for ALB creation. The subnets that did resolve were [].

**Comment by lemonshow** [comment]
By the way, how do we set different health check attribute for different target groups?

**Comment by lemonshow** [comment]
Here is the  
 annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: 'subnet-06991234,subnet-6f471234'
    alb.ingress.kubernetes.io/security-groups: sg-d312345

    alb.ingress.kubernetes.io/healthcheck-path: /myapp/v1/ready

The above works, but if adding below line,
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 75
The error is seen.

thanks,

**Comment by lemonshow** [comment]
Did you test out against annotation on the services for different targets?

**Comment by bigkraig** [comment]
How are you making that change? kubectl will not even let me save `alb.ingress.kubernetes.io/healthcheck-interval-seconds: 75`, it must be `alb.ingress.kubernetes.io/healthcheck-interval-seconds: "75"`

```
$ kubectl --context sandbox3.us-east-1 -n prd354 edit ingress test                                                                                                                                error: ingresses.extensions "test" could not be patched: cannot convert int64 to string
```

**Comment by bigkraig** [comment]
Maybe it would be best to dump your entire ingress resource in here and explain how you are creating it. I am unsure how you are able to receive the `Retrieval of subnets failed to resolve 2 qualified subnets` error when you are supplying a subnets annotation. That error comes from code that is only called when the annotation is missing.

**Comment by lemonshow** [comment]
The beta.5 version is more strict for format checking which is good. Not sure why the error pointing out to subnet validation. I changed to '75' and it works.

**Comment by lemonshow** [comment]
Regarding different health check, can share an example for service annotation?
Do we need to set something in Ingress annotation as well?
I do have readinessProbe defined in service but it is not picked up after Ingress is deployed.

**Comment by lemonshow** [comment]
@bigkraig 
Regarding different health check for different target groups, can share an example for service annotation?
