### ISSUE TITLE
New target group names in beta version conflicts

### ISSUE THREAD

**Issue by pampy** [kubernetes-sigs/aws-alb-ingress-controller#533]
Hi everyone,
today we tried to update our ALB Ingress Controller from alpha.8 to beta.5.

During the update we noticed that all ALBs were re-created since the ALB name now seems to have a random prefix (by the way, is there a migration guide or changelog somewhere?)

The ALBs got created, but it failed creating the target groups.
Here's the error we got:
```
E0808 07:33:47.082310       1 albingress.go:296] xxxx-test/t-yyyy-connect-ingress: Failed to reconcile state on this ingress
E0808 07:33:47.082331       1 albingress.go:298] xxxx-test/t-yyyy-connect-ingress:  - Failed TargetGroup creation: DuplicateTargetGroupName: A target group with the same name 'e19c0169-yyyy-connect-servic' exists, but with different settings
E0808 07:33:47.082338       1 albingress.go:298] xxxx-test/t-yyyy-connect-ingress: 	status code: 400, request id: 6295bb8e-9add-11e8-b34d-fd20e85355a8.
E0808 07:33:47.082345       1 albingress.go:298] xxxx-test/t-yyyy-connect-ingress:  - Failed Listener creation: ValidationError: A target group ARN must be specified
E0808 07:33:47.082357       1 albingress.go:298] xxxx-test/t-yyyy-connect-ingress: 	status code: 400, request id: 62afd38b-9add-11e8-8930-3ff8e7c06352.
E0808 07:33:47.082365       1 albingress.go:298] xxxx-test/t-yyyy-connect-ingress:  - Failed TargetGroup creation: DuplicateTargetGroupName: A target group with the same name 'e19c0169-yyyy-connect-servic' exists, but with different settings
E0808 07:33:47.082370       1 albingress.go:298] xxxx-test/t-yyyy-connect-ingress: 	status code: 400, request id: 62b35640-9add-11e8-bd83-a1ae6621d102.
E0808 07:33:47.082416       1 albingress.go:301] xxxx-test/t-yyyy-connect-ingress: Will retry to reconcile in 2.00349479s
```

I already got an idea of why this happens:
Before it used the port as part of the target group name, like "xxxxcloud-31005-HTTP-4c47206".
Now it includes the name of the service, like "e19c0169-xmp-service-cd7994f".

The problem is, when the service name is too long, the **random string at the end is cut off** as in the error message: "e19c0169-yyyy-connect-servic".
We actually have services with the same name in different namespaces.
That means that, without the random string, the **target group names will collide**.

Is there a way to configure the length of the target group names, or to disable the random prefix or service names inside the target group names?

Thanks for your help!

**Comment by bigkraig** [comment]
The port is now part of the hash: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/internal/alb/tg/targetgroup.go#L42-L46

Still though, i am wondering if there is any value in trying to have recognizable parts of the TG name. Kubernetes doesn't try and use any recognizable words when creating ELBs and this is not the first time we have had a problem with collisions. The TG would have all of the tags to search with.

**Comment by pampy** [comment]
@bigkraig thanks a lot!
I'll give it a try as soon as I can.

**Comment by lemonshow** [comment]
Also in this case, delete ingress did not delete the ALB created.
