### ISSUE TITLE
pod -> ip documentation update

### ISSUE THREAD

**Issue by bdirito** [kubernetes-sigs/aws-alb-ingress-controller#546]
a0cd2e401d26a4bae4f8e7066be39f3b2e033fa3
It looks like you renamed the 'target-type' value of 'pod' to 'ip' 

The documentation has not been updated however.

**Comment by bigkraig** [comment]
Thanks for catching that, I didn't search for the backticks.

**Comment by bigkraig** [comment]
Fixed via #547
