### ISSUE TITLE
DuplicateTargetGroupName error with service name more than 19 chars 

### ISSUE THREAD

**Issue by lemonshow** [kubernetes-sigs/aws-alb-ingress-controller#551]
I am seeing the same issue with beta.5 as in below,
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/533

I have new installation.
It failed to create target group for one of the service.
- One service is ok,
'CREATE' 0e4422db-15char-name-ade target group created

- But the other one with 21 characters was trucked to 19 characters and failed.

I0814 03:58:50.857456 1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"dev-xyz-ingress", UID:"5980483d-9f76-11e8-b8b4-02ddb628bdb0", APIVersion:"extensions/v1beta1", ResourceVersion:"4299608", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error creating target group 0e4422db-19chars-name: DuplicateTargetGroupName: A target group with the same name '0e4422db-19chars-name' exists, but with different settings
status code: 400, request id: 5a6955ca-9f76-11e8-8e5c-111111111111

Also in this case, delete ingress did not delete the ALB created.

this looks like a bug.

**Comment by bigkraig** [comment]
Check out `1.0-beta.6` which addressed this issue by using longer hashes.

**Comment by bigkraig** [comment]
@lemonshow I am using more of the hash and less of the identifiable names in the TG names now. Since they have the full information in the tags, there didn't seem to be enough value to warrant the collision risk. 1.0-beta.6 brings a lot of stability improvements so hopefully that works out for you. 👍
