### ISSUE TITLE
Handle secondary port for health checks

### ISSUE THREAD

**Issue by Tinche** [kubernetes-sigs/aws-alb-ingress-controller#570]
Hi,

trying to port one of our backend services to Amazon EKS, and hence ALB. The pods expose several ports - one for main traffic, which I'd like to expose via the ALB, and another for internal use (including health checks). How do I make the ingress controller set up health checking on this second port?

Is just choosing a specific port and hardcoding it the only way currently? alb.ingress.kubernetes.io/healthcheck-port only takes integers or "traffic-port" it seems. Ideally the annotation (ideally on the service) could take the port name too.

**Comment by aciddude** [comment]
+1 this would be useful. 

I was trying to do exactly what @Tinche is doing..moving to Amazon EKS. 

to use a different port for the health check what I had to do was map two ports in my svc file, one for the app and one for the health check 

then in the ingress file I specified 
```
alb.ingress.kubernetes.io/healthcheck-path
alb.ingress.kubernetes.io/healthcheck-port
```
