### ISSUE TITLE
Multiple "actions" on Ingress, is it possible?

### ISSUE THREAD

**Issue by andreasottosson** [kubernetes-sigs/aws-alb-ingress-controller#574]
Is it possible to have multiple actions on one Ingress? I would like it to first redirect but also have a fixed response if nothing matches.

Something like this:

`alb.ingress.kubernetes.io/actions.myservice: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "Host": "#{host}", "Path": "/#{path}", "Query": "#{query}", "StatusCode": "HTTP_301"}}'`

and

`alb.ingress.kubernetes.io/actions.myservice: '{"Type": "fixed-response", "FixedResponseConfig": {"ContentType":"text/plain", "StatusCode":"404", "MessageBody":"404 not found."}}'`

And maybe specify "Order": 1 and "Order":2 respectively.

**Comment by mittalsuraj18** [comment]
@andreasottosson How did you solve this?
