### ISSUE TITLE
Retrieve AWS ALB with Ingress info

### ISSUE THREAD

**Issue by lemonshow** [kubernetes-sigs/aws-alb-ingress-controller#577]
Have a use case to retrieve AWS ALB after using Ingress to create it. We need a few information such as hostedzone, DNS hostname, ALB ARN, ALB name etc. The ingress status will return hostname/IP only. Using ALB SDK will need either ALB ARN or Name. However ingress controller will generate ALB name based on namespace, ingress name and hash prefix.

What is the recommendation to resolve this? thanks,

For example, in GCP ingress, additional annotation are added by ingress controller,
   ``` ingress.kubernetes.io/backends: '{"k8s-be-30389--11111":"HEALTHY","k8s-be-32649--11111":"HEALTHY"}'```

If we can add the similar annotation and add the alb name, that will be helpful,
``` ingress.kubernetes.io/ingress-lb-name: 'hash-ns-ing-name'```

**Comment by lemonshow** [comment]
Open this again since we still look for this.

**Comment by M00nF1sh** [comment]
Hi,

Can you share your use case for such information? 
Personally, I think these information are implementation details, and kube-native applications running inside k8s cluster shouldn't rely on these information.
There might be use cases like management tools outside k8s cluster utilizing such information.

**Comment by lemonshow** [comment]
We have a use case to poll ALB status once it is being created. 
1. We use AWS SDK for this purpose now. 
AWS ALB can be retrieved using either ALB ARN or Name(ingress controller will generate ALB name based on namespace, ingress name and hash prefix.). Otherwise we have to loop through all the list and find the match for hostname/IP.
We can add annotation for alb name, that will be helpful,
ingress.kubernetes.io/ingress-lb-name: 'hash-ns-ing-name'

2. If ALB Ingress controller can provide health check and update the status in annotation, we can use the ingress SDK to do this.
For example, for GCP ingress controller we used below,
```ingress.kubernetes.io/backends: '{"k8s-be-30389--11111":"HEALTHY","k8s-be-32649--11111":"HEALTHY"}'````

If you can support 2# then we do not need 1# as we can query ingress only.
If you can not support 2# then at least 1# can help to retrieve ALB.

**Comment by M00nF1sh** [comment]
Hi,
For now, you can still directly get the alb without looping through 😄 
alb created with be tagged with below tags:
- kubernetes.io/cluster/{your cluster name}:  owned
- kubernetes.io/namespace: {your namespace}
- kubernetes.io/ingress-name: {your ingress name}
So you can directly get that alb by query using resource tagging api with above tags:  https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html

BTW,
I think the above tags are not using a consistent style, i think it might be better to change to below:
- kubernetes.io/cluster:  {your cluster name}
- kubernetes.io/namespace: {your namespace}
- kubernetes.io/ingress: {your ingress name}

**Comment by lemonshow** [comment]
Cool, resource tagging API should solve the current problem. thanks,

**Comment by M00nF1sh** [comment]
BTW, it's an good idea to add alb information to ingress, i'll add it in later PR

**Comment by lemonshow** [comment]
Yes, those will be nice feature to have so user can use ingress resource to track ALB other than using cloud SDK.
