### ISSUE TITLE
ingress unable to create alb : instance Id error

### ISSUE THREAD

**Issue by sagoon** [kubernetes-sigs/aws-alb-ingress-controller#582]
hi, 
I'm getting this below error:

event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"ing-sagoon-dev1", UID:"33d137b2-b029-11e8-9911-0218c26dbc76", APIVersion:"extensions/v1beta1", ResourceVersion:"927997", FieldPath:""}): type: 'Warning' reason: 'ERROR' error instantiating load balancer: Unable to DescribeInstanceStatus on kubernetes-k8s-sagoon-worker0: InvalidInstanceID.Malformed: Invalid id: "kubernetes-k8s-sagoon-worker0"
	status code: 400, request id: 22ded198-fa9c-4a2a-a707-44ab121f5f09

**Comment by sagoon** [comment]
yes.

Best Regards,
*Govinda Giri*
*Architect of** Sagoon  *
[image: Related image] <http://www.sagoon.com/invest>
<https://play.google.com/store/apps/details?id=com.sagoon.connect.share.earn&hl=en>


CONFIDENTIALITY NOTICE: This message, including attachments, may contain
proprietary, confidential and privileged information for the sole use of
the intended recipient(s), and is protected by law. If you are not the
intended recipient, please notify the sender immediately and destroy all
copies of the original message and attachments, if any. Any unauthorized
review, use, disclosure, dissemination, forwarding, printing or copying of
this e-mail or any action taken in reliance on this e-mail is strictly
prohibited and may be unlawful.

Sagoon reserves the right to record, monitor and inspect all e-mail
communications through its internal and external networks. Your messages
can be subject to such lawful supervision as Sagoon deems necessary in
order to protect their information, interests, and reputation. Sagoon
prohibits and may take steps to prevent their information systems from
being used to view, store or forward offensive or discriminatory material.
If this message contains such material, please report it to
contactus@sagoon.com. Please ensure you have adequate virus protection
before you open or detach any documents from this transmission. Sagoon does
not accept any liability for viruses.



Please do not print this email if not necessary. Save Paper, Save Trees,
Save The Environment.

**Comment by hugohenley** [comment]
I've got a similar error several months ago when I was running Kubernetes via Rancher and, by default, it was not using instance ids to identify the nodes. It was easily fixed by changing a config there to consider the nodes as AWS nodes.

How did you deploy Kubernetes on AWS? Rancher? Kops? EKS?

**Comment by hugohenley** [comment]
> Hi @hugohenley , I think I have the same issue, my nodes (Aws ec2 instaces created by rancher) does not have the property ProviderID.
> Where can I find the mentioned configuration?
> Thanks

I was using Rancher 1.6, so it might be different depending on the version that you're using now. If I remember well, it was a select box when creating the Kubernetes cluster via Catalog in a Cattle environment. The select box is called `Cloud Provider` and you should select `aws`.

**Comment by etessari** [comment]
@hugohenley yes I forgot to post the resolution but I the problem was specifying the cluster cloud provider as you mentioned
Thanks
