### ISSUE TITLE
Latest version, fresh K8S cluster - error instantiating load balancer: InvalidInstanceID.NotFound

### ISSUE THREAD

**Issue by matthewflannery** [kubernetes-sigs/aws-alb-ingress-controller#586]
Hi guys,

We're seeing an issue with `0.1.0` from https://quay.io/application/coreos/alb-ingress-controller-helm?tab=releases 

**Log snippet**: ```I0904 23:09:50.306419       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"echoserver", UID:"9fc1b308-b097-11e8-a106-02075f0b7eb8", APIVersion:"extensions/v1beta1", ResourceVersion:"56454", FieldPath:""}): type: 'Warning' reason: 'ERROR' error instantiating load balancer: InvalidInstanceID.NotFound: The instance ID 'i-0e9e8f0ade703d464' does not exist```

I noticed in  https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/setup.md it mentions "The kubelet must be run with --cloud-provider=aws. This populates the EC2 instance ID in each node's spec."

However, I have verified on the K8S nodes that kubelet has the --cloud-provider=aws flag.

I'm really unsure how to troubleshoot this. I have tried terminating the K8S nodes and waiting for them to autoscale, and it just complains about another instance ID instead. 

**Full log output**:

``` deployment (master) ✗ kk logs calico-abalone-alb-ingress-controller-controller-5c4b7c7c4c2ppq
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    1.0-beta.6
  Build:      git-f740c293
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

I0904 23:09:00.797118       1 flags.go:132] Watching for Ingress class: alb
W0904 23:09:00.797245       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0904 23:09:00.797396       1 main.go:159] Creating API client for https://100.64.0.1:443
I0904 23:09:00.809952       1 main.go:203] Running in Kubernetes cluster version v1.10 (v1.10.3) - git (clean) commit 2bba0127d85d5a46ab4b778548be28623b32d0b0 - platform linux/amd64
I0904 23:09:00.810598       1 alb.go:85] ALB resource names will be prefixed with 655061ae
I0904 23:09:00.815622       1 alb.go:158] Starting AWS ALB Ingress controller
I0904 23:09:02.016173       1 leaderelection.go:185] attempting to acquire leader lease  default/ingress-controller-leader-alb...
I0904 23:09:02.019197       1 status.go:152] new leader elected: bilging-clownfish-alb-ingress-controller-controller-5fb5b6x6q9v
I0904 23:09:02.531596       1 albingresses.go:77] Building list of existing ALBs
I0904 23:09:02.746632       1 albingresses.go:85] Fetching information on 0 ALBs
I0904 23:09:02.786580       1 albingresses.go:101] Assembled 0 ingresses from existing AWS resources in 254.959168ms
I0904 23:09:32.874497       1 leaderelection.go:194] successfully acquired lease default/ingress-controller-leader-alb
I0904 23:09:32.874540       1 status.go:152] new leader elected: calico-abalone-alb-ingress-controller-controller-5c4b7c7c4c2ppq
E0904 23:09:50.306042       1 albingresses.go:57] default/echoserver: error instantiating load balancer: InvalidInstanceID.NotFound: The instance ID 'i-0e9e8f0ade703d464' does not exist
E0904 23:09:50.306061       1 albingresses.go:57] default/echoserver: 	status code: 400, request id: b08f3332-ad97-496f-abd4-9558dd31a2ae
E0904 23:09:50.306070       1 albingresses.go:58] default/echoserver: Will retry in 502.146284ms
I0904 23:09:50.306419       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"echoserver", UID:"9fc1b308-b097-11e8-a106-02075f0b7eb8", APIVersion:"extensions/v1beta1", ResourceVersion:"56454", FieldPath:""}): type: 'Warning' reason: 'ERROR' error instantiating load balancer: InvalidInstanceID.NotFound: The instance ID 'i-0e9e8f0ade703d464' does not exist
	status code: 400, request id: b08f3332-ad97-496f-abd4-9558dd31a2ae```

**Comment by bigkraig** [comment]
Can you check that you have the right region configured?

**Comment by ilialev** [comment]
I encounter the same issue on a kops cluster.

`I0912 22:06:47.635380       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"staging-alb", UID:"dd79ec50-b69f-11e8-9a8e-12269bb0d504", APIVersion:"extensions/v1beta1", ResourceVersion:"3262111", FieldPath:""}): type: 'Warning' reason: 'ERROR' error instantiating load balancer: InvalidInstanceID.NotFound: The instance ID 'i-0f81431b9e1b1204f' does not exist
	status code: 400, request id: 750f3fc2-d52a-4391-a8f6-3e271004c8f2`

Tried to redeploy the ingress controller with the correct cluster name and region and I still get the same error.

**Comment by pablojudd** [comment]
@matthewflannery Have you been able to resolve this issue? If so, how was it resolved?

**Comment by dalbhanj** [comment]
I ended up here as I received similar error. I had to configure awsRegion parameter because the default helm install configures for us-west-1 region. You can download values (https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/alb-ingress-controller-helm/values.yaml), update the desired region and deploy using 'helm registry install quay.io/coreos/alb-ingress-controller-helm -f values.yaml'
