### ISSUE TITLE
Add actions: authenticate-oidc and authenticate-cognito

### ISSUE THREAD

**Issue by natefox** [kubernetes-sigs/aws-alb-ingress-controller#592]
The actions annotation supports some but not all of the actions. We'd like to be able to use the authenticate actions. However, I'm not quite sure how to handle the sensitive data properly.

I'm proposing something along these lines:
```
  annotations:
    alb.ingress.kubernetes.io/actions.authenticate-oidc: >-
      [{
          "Type": "authenticate-oidc",
          "AuthenticateOidcConfig": {
              "Issuer": "https://idp-issuer.com",
              "AuthorizationEndpoint": "https://authorization-endpoint.com",
              "TokenEndpoint": "https://token-endpoint.com",
              "UserInfoEndpoint": "https://user-info-endpoint.com",
              "ClientId": "abcdefghijklmnopqrstuvwxyz123456789",
              "ClientSecret": "123456789012345678901234567890",     //  <--- this is my problem
              "SessionCookieName": "my-cookie",
              "SessionTimeout": 3600,
              "Scope": "email",
              "AuthenticationRequestExtraParams": {
                  "display": "page",
                  "prompt": "login"
              },
              "OnUnauthenticatedRequest": "deny"
          },
          "Order": 1
      },
      {
          "Type": "forward",
          "Order": 2
      }]
spec:
  rules:
    - host: www.example.com
      http:
        paths:
          - path: /auth
            backend:
              serviceName: authenticate-oidc
              servicePort: use-annotation
```

Note that the `TargetGroupArn` key is missing out of the `"Type": "forward"` object. I propose this be injected by the controller as the TG ARN is managed/known by the controller.

Ideally, the ClientSecret could be pulled from a volume or env var and not sitting in the annotation itself. Not quite sure how to best handle this as variable expansion doesn't apply to annotations (at least I dont think it does).

Additional example json for authenticate-cognito can be found on AWS site: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html

I'm keen to hear thoughts around this.

**Comment by bigkraig** [comment]
We could expand variables inside of the annotation. That might make the most sense.

The controller should also inject the ARN.

WRT those configurations not being supported, that was due to https://github.com/aws/aws-sdk-go/blob/master/service/elbv2/api.go#L3395-L3396. It shouldn't take much effort to support `authenticate-oidc` and `authenticate-cognito` though.

**Comment by JakubJecminek** [comment]
Hi is there any roadmap or plan for bringing this feature, so you can specify authenticate-oidc through annotations? 
Thanks
Jakub

**Comment by eschu21** [comment]
Would love to see this feature, we are actively blocked by not being able to setup OIDC auth on our alb.

Thanks!!

**Comment by d-nishi** [comment]
/ sig aws

**Comment by JakubJecminek** [comment]
It should also be possible to have multiple of these authentication annotations. And specify for which service should annotation be used. For example you can have multiple services and each is secured using different oidc provider. Therefore you need to somehow create mapping between authentication-oidc annotation and service.

**Comment by AdeOpe** [comment]
+1
this would be super useful to have

**Comment by sc14aec** [comment]
This would be very much appreciated - this resource would be really useful, but we're using Cognito for auth which means it's essentially unusable until this feature is implemented

**Comment by M00nF1sh** [comment]
Hi all, i have created an design proposal for possible implementation for this feature.
Would you help review it and vote for the alternatives 😄 . Implementation should be straight forward once choose

**Comment by AdeOpe** [comment]
@M00nF1sh - definitely Alternative 1.

I have smashed a 👍 on the ticket

**Comment by M00nF1sh** [comment]
resolving since it's already implemented

**Comment by yshwntsingh** [comment]
I followed same code as mentioned in 752 but  no luck.Along with that I used code as mentioned below for OIDC authentication. Deployment going through but not allowing OIDC authentication. Can see only default forwarder rule created but not for OIDC.
Can you please suggest what is missing and how to fix it.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-admin-reverse-proxy-dev
  annotations:
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: xxxxxxxxxxxxxxxxx
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.public_subnets }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.security_group }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:707026380822:certificate/666bff45-376c-4cf0-ba3c-21a421c7d81b
    alb.ingress.kubernetes.io/ssl-policy: {{ .Values.ingress.ssl_policy }}
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/tags: environment={{ .Values.environment }}
    alb.ingress.kubernetes.io/auth-type: OIDC
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"Issuer":"https://dev-23074903.okta.com/oauth2/default","AuthorizationEndpoint":"https://dev-23074903.okta.com/oauth2/default/v1/authorize","TokenEndpoint":"https://dev-23074903.okta.com/oauth2/default/v1/token","UserInfoEndpoint":"https://dev-23074903.okta.com/oauth2/default/v1/userinfo","secretName":"xxxxxxxxx"}'
    alb.ingress.kubernetes.io/auth-scope:  'openid'
    alb.ingress.kubernetes.io/auth-session-cookie: 'AWSELBAuthSessionCookie'
    alb.ingress.kubernetes.io/auth-session-timeout: '300'
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
spec:
  rules:
     - http:
        paths:
          - path: /*
            backend:
              serviceName: kibana-admin-reverse-proxy-dev
              servicePort: 80
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
