### ISSUE TITLE
Backoff not reset on new ingress resources

### ISSUE THREAD

**Issue by bdirito** [kubernetes-sigs/aws-alb-ingress-controller#599]
When trying something new that doesnt work (in my case a redirect config that is creating a loop). The alb ingress controller fails and goes into a backoff. This is good. However when you then edit the ingress resource to try something new you are still in that same backoff loop. You have to wait for the timeout of the previous backoff to finish before you can try your changes. If those then fail you increment again and will now have to wait for backoff again before checking anything again.

Current best workarround is to delete the alb ingress controller pod

This is annoying for development as it slows down the pickup of the new rules.

**Comment by NickLarsenNZ** [comment]
It seems like the Backoff times are hardcoded as described here: https://github.com/kubernetes/kubernetes/issues/57291

I'm not sure there's anything else you can do other than restarting the pod (which doesn't impact traffic except for the broken Ingress.

I think the real solution is to probably have better validation of the Ingress config to avoid panics.

**Comment by M00nF1sh** [comment]
This is already resolved by https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/674
Will close this after I do full integration tests for all use cases

**Comment by M00nF1sh** [comment]
this one was fixed in master branch(we'll release new version soon)
Closing this.
