### ISSUE TITLE
[1.0-beta.6] error parsing annotations: Retrieval of subnets failed to resolve 2 qualified subnets.

### ISSUE THREAD

**Issue by NickLarsenNZ** [kubernetes-sigs/aws-alb-ingress-controller#606]
In `1.0-beta.6`, I was receiving the following error.

```
I0912 04:45:56.361403       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"echoserver", Name:"echoserver", UID:"92ecc697-b63a-11e8-b7c1-129bc0ce9c1e", APIVersion:"extensions/v1beta1", ResourceVersion:"902067", FieldPath:""}): type: 'Warning' reason: 'ERROR' error parsing annotations: Retrieval of subnets failed to resolve 2 qualified subnets. Subnets must contain the kubernetes.io/cluster/<cluster name> tag with a value of shared or owned and the kubernetes.io/role/internal-elb tag signifying it should be used for ALBs Additionally, there must be at least 2 subnets with unique availability zones as required by ALBs. Either tag subnets to meet this requirement or use the subnets annotation on the ingress resource to explicitly call out what subnets to use for ALB creation. The subnets that did resolve were [].
```

I had followed the docs at https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/ingress-resources.md

I added the following tags to my subnets:
- `kubernetes.io/cluster/mycluster="owned"`
- `kubernetes.io/role/elb` (I tried setting it to `""`, and also `true`, figuring it can probably be anything)

I noticed someone in a totally different repo setting the same tag to "1", and now it appears to find my subnet.
https://github.com/kubernetes/kubernetes/issues/60152

I'm happy to submit a PR if that is the correct way to do it.

**Comment by argeualcantara** [comment]
It should work for either "" or 1 (1 for the default kops value) as you can see here:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/7f13876d63c35cb75a3d50d282f197f35e0f2dcb/internal/aws/albrgt/rgt.go#L82
