### ISSUE TITLE
 No subnets defined or were discoverable when setting healthcheck-port

### ISSUE THREAD

**Issue by spucman** [kubernetes-sigs/aws-alb-ingress-controller#642]
When adding the annotation for a different `healthcheck-port` no subnet can be found or defined.

Environment:
* Kuberentes v1.10.5 (1 master, 2 nodes)
* kube2iam
* aws-alb-ingress-controller 1.0-beta.6 & latest

The setup is up & running and the provided echoservice example was working like a charm.

If the echoserver-ingress.yml gets a healthcheck-port added no subnet can be auto configured nor a provided subnet (defined via `alb.ingress.kubernetes.io/subnets`) will be taken:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: websocket-test
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/healthcheck-port: 3001
spec:
  rules:
    - host: echoserver.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
```

log output for the failing ingress resource
```
E0926 07:39:02.835196       1 albingresses.go:60] websocket-test/websocket-scream-ingress: error parsing annotations: No subnets defined or were discoverable
E0926 07:39:02.835219       1 albingresses.go:61] websocket-test/websocket-scream-ingress: Will retry in 504.781765ms
I0926 07:39:02.835430       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"websocket-test", Name:"websocket-scream-ingress", UID:"b5f537dc-c103-11e8-860d-0ae04425a05c", APIVersion:"extensions/v1beta1", ResourceVersion:"234497", FieldPath:""}): type: 'Warning' reason: 'ERROR' error parsing annotations: No subnets defined or were discoverable
```

Have I misconfigured something with the healthcheck-port?

**Comment by bigkraig** [comment]
Can you try with 1.0-beta.7? we had some problems with annotations in .6

**Comment by hickey** [comment]
I was seeing the same behavior with 1.0-beta.7 even with the subnet tags being in place. Found that there are required values that need to be set in the values.yaml file. It might be good if the instructions for installing via helm showed how to pull the existing `values.yaml` file and the specific variables that need to be set. 

Unfortunately because you are using the registry plugin instead of just having standard helm charts, getting the `values.yaml` file is not intuitive so the project should really document how to do a fully configured install instead of the typical "run this one command and every thing will work perfectly for you" which only works for one environment and breaks for everyone else.

**Comment by carlosfrancia** [comment]
> I was seeing the same behavior with 1.0-beta.7 even with the subnet tags being in place. Found that there are required values that need to be set in the values.yaml file. It might be good if the instructions for installing via helm showed how to pull the existing `values.yaml` file and the specific variables that need to be set.
> 
> Unfortunately because you are using the registry plugin instead of just having standard helm charts, getting the `values.yaml` file is not intuitive so the project should really document how to do a fully configured install instead of the typical "run this one command and every thing will work perfectly for you" which only works for one environment and breaks for everyone else.

I am having a similar issue when trying to set a Health Port different than traffic-port. My Helath port is completely ignored when set it in the Service.yaml and I face the subnet issue when set it in the Ingress.yaml file. What are the required values needed to be set in the values.yaml file?
