### ISSUE TITLE
Healthcheck-interval-seconds not getting updated

### ISSUE THREAD

**Issue by disha1104** [kubernetes-sigs/aws-alb-ingress-controller#643]
Hi,
I am using the annotation : `alb.ingress.kubernetes.io/healthcheck-interval-seconds: '250'` in my ingress yaml, but when I am trying to update this to some other value, it is not getting updated on ALB.
Also, there are no logs wrt to this in alb-ingress-controller pod.

Is there any config that I am missing?

**Comment by bigkraig** [comment]
Do you have annotations on the services? There was a bug in pre 1.0-beta.7 versions that could have caused something like this.

**Comment by disha1104** [comment]
Hi @bigkraig What exactly do you mean by annotations on services? Could you point me to some example?
I am just using annotations on the ingress.

**Comment by bigkraig** [comment]
yeah that is what I meant, you can also configure healthcheck annotations on services incase you have multiple services in an ingress that need different settings.

Can you try with the `1.0-beta.7` image and see if this persists?

**Comment by disha1104** [comment]
No, we wanted to keep same settings for all services.
Also, currently I was using just a single service/host with that ingress. Should that be a problem? I am using 1.0-beta.6 right now.

**Comment by bigkraig** [comment]
Yeah its still possible AFAIK. There have been other issues raised where changing some annotations would not be respected, try the new image and LMK

**Comment by disha1104** [comment]
Sure. Let me try 1.7 then.
Are there any major changes in 1.7 that we need to take care of?

**Comment by bigkraig** [comment]
The only thing that may pose a problem is if your paths did not use wildcards and you were relying on the fallback. So check that you are using things like `/*` and not `/`

**Comment by disha1104** [comment]
Yes, we were using wildcard before as well. Cool..Thanks!!
