### ISSUE TITLE
Nil Pointer Dereference with HTTP->HTTPS Redirect Annotation

### ISSUE THREAD

**Issue by stevenpall** [kubernetes-sigs/aws-alb-ingress-controller#649]
As per my comment in #543:

> Hey there,
> 
> I've been trying to get HTTP->HTTPS redirects working and have run into this same issue with `1.0-beta.6`. This only seems to happen when the `alb.ingress.kubernetes.io/actions.redirect` annotation is added to the ingress resource. Here's the full ingress:
> 
> ```
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: test
>   annotations:
>       alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:some-cert"
>       alb.ingress.kubernetes.io/healthcheck-path: "/ping"
>       alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80,\"HTTPS\": 443}]"
>       alb.ingress.kubernetes.io/scheme: "internet-facing"
>       alb.ingress.kubernetes.io/security-groups: "sg-12345678"
>       alb.ingress.kubernetes.io/subnets: "subnet-12345678"
>       alb.ingress.kubernetes.io/actions.redirect: {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "StatusCode": "HTTP_301"}}
> spec:
>   rules:
>     - http:
>        paths:
>          - path: /*
>            backend:
>               serviceName: redirect
>               servicePort: use-annotation
>     - host: test.website.com
>       http:
>         paths:
>           - path: /*
>             backend:
>               serviceName: test
>               servicePort: 443
> ```
> And the stacktrace I'm getting:
> 
> ```
> F0926 19:21:58.254847       1 albingresses.go:167] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
> , Stack Trace:
>  goroutine 1088 [running]:
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc00659bf18, 0xc006780d80)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
> panic(0x1687b00, 0x2c25d90)
> 	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
> github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs.Rules.FindUnusedTGs(0xc005ccf560, 0x3, 0x4, 0xc00042bf18, 0x1, 0x1, 0x0, 0x1, 0xc005bf0800, 0x594bc1)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs/rules.go:190 +0xa4
> github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.(*LoadBalancer).Reconcile(0xc006213080, 0xc000097e30, 0xc006811540, 0x10, 0x10)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:314 +0x38a
> github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.(*ALBIngress).Reconcile(0xc00633b5c0, 0xc000055ea8, 0x0, 0x0)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:281 +0x12e
> github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.ALBIngresses.Reconcile.func1.1(0x1ad8720, 0xc006871320, 0x2, 0x0, 0x5b1301, 0xc000055f28)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:154 +0xce
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc006871140, 0xc006badb00, 0xc006780d80)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
> created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53
> 
> goroutine 1 [select]:
> github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc0001a1d90)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:193 +0x3ff
> main.main()
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd
> 
> goroutine 18 [chan receive]:
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c3c9a0)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
> created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203
> 
> goroutine 5 [syscall]:
> os/signal.signal_recv(0x811e33)
> 	/home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c
> os/signal.loop()
> 	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22
> created by os/signal.init.0
> 	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41
> 
> goroutine 117 [sync.Cond.Wait]:
> sync.runtime_notifyListWait(0xc00043c188, 0xc000000001)
> 	/home/travis/.gimme/versions/go/src/runtime/sema.go:510 +0xeb
> sync.(*Cond).Wait(0xc00043c178)
> 	/home/travis/.gimme/versions/go/src/sync/cond.go:56 +0x92
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc00043c160, 0xc0006c8310, 0x0, 0x0, 0x0, 0x0)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:431 +0x99
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000436080)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x40
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x2a
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000486ef0)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000486ef0, 0x3b9aca00, 0x0, 0xc0059f8001, 0xc00009c9c0)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000486ef0, 0x3b9aca00, 0xc00009c9c0)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc000436080, 0xc00009c9c0)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x299
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc0002f6000, 0xc00009c9c0)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:227 +0x40d
> created by github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/store.(*Informer).Run
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/store/store.go:173 +0x33d
> 
> goroutine 54 [select]:
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc0001a8d20)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:206 +0x34f
> created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:54 +0x1ba
> 
> goroutine 55 [chan receive]:
> github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc000426540)
> 	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
> created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.NewBroad
> ```

**Comment by bigkraig** [comment]
Can you try with the 1.0-beta.7 that was released yesterday?

**Comment by stevenpall** [comment]
Sure, I will try it with `1.0-beta.7`, though I have to convert all of my ingress paths as per #646 first.

**Comment by stevenpall** [comment]
Updated all of my ingress paths and upgraded to `1.0-beta.7`. Everything looks to be working now (with a bit of fiddling with annotations). Thanks!
