### ISSUE TITLE
IAM policy template missing NetworkInterface rights

### ISSUE THREAD

**Issue by fredsted** [kubernetes-sigs/aws-alb-ingress-controller#657]
We just set up ALB Ingress Controller today, and found out that the example IAM policy document[0] is missing some NetworkInterface rules since it couldn't attach the SecurityGroups to the specified NetworkInterface. 

What we did so far is just to add all rights containing NetworkInterface to the IAM policy.

[0] https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/iam-policy.json

**Comment by M00nF1sh** [comment]
Hi Simon, you need the ec2:ModifyNetworkInterfaceAttribute as well.

Will merge [this PR](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/659) to update the example policy

**Comment by fredsted** [comment]
@M00nF1sh Thanks for the quick response! :)
