### ISSUE TITLE
Add custom request header

### ISSUE THREAD

**Issue by JakubJecminek** [kubernetes-sigs/aws-alb-ingress-controller#669]
Hi, is their some annotation (or some other possibility) how to add custom header to request so it can be retrieved by services in cluster? Something similar to what supports nginx-ingress (https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/customization/custom-headers) 

But I am not certain even if AWS ALB allows adding custom headers (I've not found any mention about possibility to add custom header in AWS documentation).

Has anybody tried to solve similar problem? 

Thanks,
Jakub

**Comment by M00nF1sh** [comment]
@JakubJecminek 
ALB itself doesn't support adding custom headers for now 😄

**Comment by JakubJecminek** [comment]
Ok thanks. I found the same information, hopefully aws will added in the future.

**Comment by mathieujobin** [comment]
could it be added at the target group level? 
or any other level?
how about ELB ?

**Comment by ska-ibees** [comment]
Looks like an old issue. But do we have this possibility now? 
I have been scratching my head to implement a custom header to pass some value that can be used by backend application. Unfortunately couldn't find any thing in docs and elsewhere. The only solution have found is to adopt ALB+nginx-ingress.

**Comment by rampn443** [comment]
Does ALB support adding custom headers for now ?
