### ISSUE TITLE
Possible Memory Leak (v1.0-beta.7)

### ISSUE THREAD

**Issue by stevenpall** [kubernetes-sigs/aws-alb-ingress-controller#671]
Hi there,

I've been testing with version `1.0-beta.7` and have recently noticed steadily increasing memory usage of the pod. I've attached a memory usage graph for reference.

<img width="988" alt="screen shot 2018-10-11 at 12 11 33 pm" src="https://user-images.githubusercontent.com/2805687/46818419-2adc6f00-cd4f-11e8-9936-6c3f5abe78b9.png">

One theory I have about why this is happening is due to an error I'm receiving related to the number of security groups attached to a particular instance:
```
failed association of SecurityGroups due to failed to reconcile managed Instance securityGroup attachment due to SecurityGroupsPerInterfaceLimitExceeded: The maximum number of security groups per interface has been reached.
```
I'm looking into resolving this issue by statically setting security groups to avoid having new ones be created for each ingress. That said, I'm wondering if this error could somehow be causing memory usage to increase? If that's not the case, then perhaps something else is happening with this version.

**Comment by M00nF1sh** [comment]
The abnormal usage should be caused the reconcile frequency(happens too frequently, 30 secs for every ingress in cluster), and also incorrect pointer usage(golang will allocate objects on heap if pointers to it are created and basic escape analysis failed to decide it's lifetime in compile time).

Will address this issue in next release.
In the meantime, can you share how may ingress are in your cluster?

**Comment by stevenpall** [comment]
Ah, that makes sense. I've gotten around this temporarily by just setting a memory limit on the pod. There are currently 16 ingresses in my cluster. Good to hear it will be addressed in the next release. Thanks!

**Comment by hugohenley** [comment]
Same thing here!

**Comment by noahhai** [comment]
Same issue. Had not set a memory limit. Had an ingress with around 20 rules mapping to services that get updated fifo-style as a new service is deployed. After running for a month noticed memory usage was up to 2GB. Memory limit seems to be a fine work-around.

**Comment by M00nF1sh** [comment]
@noahhai
I believe the memory leak issue is solved in v1.1.2

**Comment by noahhai** [comment]
Awesome, thanks! Will upgrade and confirm.

**Comment by gveltri** [comment]
I was also experiencing this issue with v1.1.0. Upgrading seems to have fixed it.
