### ISSUE TITLE
Document AWS Permissions needed by the ingress controller

### ISSUE THREAD

**Issue by smuhit** [kubernetes-sigs/aws-alb-ingress-controller#676]
I was following the walkthrough to get the ALB ingress controller up and running, I kept getting issues like:

```
AccessDeniedException: User: <user snipped> is not authorized to perform: acm:ListCertificates
```

I've been going through the code (in the `internal/aws` directory) to figure out what permissions are actually needed, but what would be nice is having a concise list of all required permissions in the docs.

**Comment by M00nF1sh** [comment]
@smuhit the complete list is available here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/examples/iam-policy.json

**Comment by smuhit** [comment]
Thanks. That's very helpful.

**Comment by bigkraig** [comment]
@smuhit where would you expect to find that information in the walkthrough? we can add a link referencing the policy

**Comment by smuhit** [comment]
Since I was following the walkthrough, under the `Deploy the alb-ingress-controller` section, step 2 (where it's talking about the AWS access keys) would probably make the most sense.

I notice now that it's in the `kube2iam setup` portion, which I didn't read before because it wasn't relevant to me. (Since we're using EKS, our system is using instance roles on the worker nodes to define what AWS resources they can and cannot access).

**Comment by justinwalz** [comment]
Looks like this is on the main page now, https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/

Could close the ticket if that's sufficient.

**Comment by smuhit** [comment]
@justinwalz Yeah, that's sufficient for my use-case. Closing.
