### ISSUE TITLE
Implicit target groups creation

### ISSUE THREAD

**Issue by JakubJecminek** [kubernetes-sigs/aws-alb-ingress-controller#677]
Hello, is it possible (or will be) to specify that when new ingress object is created, there should be automatically created target group for every service from specific namespace? Probably using some annotation. something like:

    alb.ingress.kubernetes.io/implicit-target-group-creation: true
    alb.ingress.kubernetes.io/implicit-target-group-creation-namespace: echoserver

This would tell alb ingress controller to automatically create target groups for all services from namespace echoserver, even if ingress descriptor does not contain rules for all the services.

**Comment by M00nF1sh** [comment]
Hi,
What's your use case for this? seems it's not an ingress use case 😄

**Comment by JakubJecminek** [comment]
Hi, 
it is closely related to this issue: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/592

I am using alb ingress but i need to add authentication oidc action to secure access for specific rule. 

Now I am using ingress for creating rule and then I am using aws sdk to modify rule and add authentication action. Sadly ingress is doing update every hour and deletes this action :( 

With this capability i would just use ingress for creation/syncing target groups and manually create rules (using sdk). 
But it is just workaround for missing feature. 
By the way I saw @M00nF1sh that you have assigned this new feature, are you actively working on it or can I somehow help?
