### ISSUE TITLE
ingress controller(1.0-beta.7) fails to provision ALB whereas successfully provisions in 1.0-beta.6

### ISSUE THREAD

**Issue by gprasad84** [kubernetes-sigs/aws-alb-ingress-controller#685]
I have tried two similar ALB deployments using versions: `beta.7` and `beta.6` and from the controller logs I noticed that the ALB deployment times out in version `beta.7` whereas it seems to successfully deploy in version `beta.6`. I suspect a breaking change introduced in `beta.7`.

When using `beta.7`, there a various errors reported in the controller logs and eventually the ingress creation fails. Below are the logs:

> I1019 17:46:26.380582       1 loadbalancer.go:227] local/condor-condormobile-us-west-2-ingress: Start ELBV2 creation.
> E1019 17:46:27.025841       1 loadbalancer.go:342] local/condor-condormobile-us-west-2-ingress: Failed setting Web ACL (%!s(*string=0xc002c89500)) association: WAFUnavailableEntityException: An entity is unavailable for modification or display. Please retry.
> E1019 17:46:27.025870       1 loadbalancer.go:342] local/condor-condormobile-us-west-2-ingress: 	status code: 400, request id: e721d71f-d3c6-11e8-a67a-0f5a3dd77efd
> E1019 17:46:27.025882       1 albingress.go:291] local/condor-condormobile-us-west-2-ingress: Failed to reconcile state on this ingress
> E1019 17:46:27.025895       1 albingress.go:293] local/condor-condormobile-us-west-2-ingress:  - WAFUnavailableEntityException: An entity is unavailable for modification or display. Please retry.
> E1019 17:46:27.025901       1 albingress.go:293] local/condor-condormobile-us-west-2-ingress: 	status code: 400, request id: e721d71f-d3c6-11e8-a67a-0f5a3dd77efd
> E1019 17:46:27.025916       1 albingress.go:296] local/condor-condormobile-us-west-2-ingress: Will retry to reconcile in 497.946263ms
> I1019 17:46:27.026110       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Warning' reason: 'ERROR' 2e735cea-local-condorcondo-6d65 Web ACL (%!s(*string=0xc002c89500)) association failed: WAFUnavailableEntityException: An entity is unavailable for modification or display. Please retry.
> 	status code: 400, request id: e721d71f-d3c6-11e8-a67a-0f5a3dd77efd
> I1019 17:46:43.916135       1 loadbalancer.go:387] local/condor-condormobile-us-west-2-ingress: Modifying ELBV2 tags to [{    Key: "kubernetes.io/cluster/condormobile-us-west-2",    Value: "owned"  },{    Key: "kubernetes.io/ingress-name",    Value: "condor-condormobile-us-west-2-ingress"  },{    Key: "kubernetes.io/namespace",    Value: "local"  }].
> I1019 17:46:43.938990       1 loadbalancer.go:413] local/condor-condormobile-us-west-2-ingress: Associating f440e9f3-4398-4250-a7a2-1e2e62f6b7a8 Web ACL.
> I1019 17:46:43.939108       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'MODIFY' 2e735cea-local-condorcondo-6d65 tags modified
> I1019 17:46:44.977058       1 targetgroup.go:224] local/condor-condormobile-us-west-2-ingress: Start TargetGroup creation.
> I1019 17:46:44.977493       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'MODIFY' Web ACL association updated to f440e9f3-4398-4250-a7a2-1e2e62f6b7a8
> I1019 17:46:47.846901       1 targetgroup.go:229] local/condor-condormobile-us-west-2-ingress: Succeeded TargetGroup creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7 | Name: 2e735cea-60503346710c1cf2871.
> I1019 17:46:47.846921       1 targetgroup.go:224] local/condor-condormobile-us-west-2-ingress: Start TargetGroup creation.
> I1019 17:46:47.847322       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2e735cea-60503346710c1cf2871 target group created
> I1019 17:46:49.344171       1 targetgroup.go:229] local/condor-condormobile-us-west-2-ingress: Succeeded TargetGroup creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-c50a3b04df650dc93b3/0944c72112ad422a | Name: 2e735cea-c50a3b04df650dc93b3.
> I1019 17:46:49.344202       1 listener.go:202] local/condor-condormobile-us-west-2-ingress: Start Listener creation.
> I1019 17:46:49.344357       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2e735cea-c50a3b04df650dc93b3 target group created
> I1019 17:46:49.607906       1 listener.go:207] local/condor-condormobile-us-west-2-ingress: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:listener/app/2e735cea-local-condorcondo-6d65/adb1c93356eacd14/25e3458aa4176e65 | Port: 9000 | Proto: HTTP.
> I1019 17:46:49.607933       1 rule.go:141] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 17:46:49.608136       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 9000 listener created
> I1019 17:46:49.901302       1 rule.go:146] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "1" | Condition: [{    Field: "path-pattern",    Values: ["/sedcloudapi/*"]  }]
> I1019 17:46:49.901335       1 rule.go:141] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 17:46:49.901531       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 1 rule created
> I1019 17:46:50.011527       1 rule.go:146] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "2" | Condition: [{    Field: "path-pattern",    Values: ["/*"]  }]
> I1019 17:46:50.011552       1 listener.go:202] local/condor-condormobile-us-west-2-ingress: Start Listener creation.
> I1019 17:46:50.011770       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2 rule created
> I1019 17:46:50.367518       1 listener.go:207] local/condor-condormobile-us-west-2-ingress: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:listener/app/2e735cea-local-condorcondo-6d65/adb1c93356eacd14/12d1a29a3a366434 | Port: 9001 | Proto: HTTPS.
> I1019 17:46:50.367544       1 rule.go:141] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 17:46:50.368057       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 9001 listener created
> I1019 17:46:50.391719       1 rule.go:146] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "1" | Condition: [{    Field: "path-pattern",    Values: ["/sedcloudapi/*"]  }]
> I1019 17:46:50.391736       1 rule.go:141] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 17:46:50.391855       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 1 rule created
> I1019 17:46:50.415368       1 rule.go:146] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "2" | Condition: [{    Field: "path-pattern",    Values: ["/*"]  }]
> I1019 17:46:50.415389       1 listener.go:202] local/condor-condormobile-us-west-2-ingress: Start Listener creation.
> I1019 17:46:50.415618       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2 rule created
> I1019 17:46:50.445166       1 listener.go:207] local/condor-condormobile-us-west-2-ingress: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:listener/app/2e735cea-local-condorcondo-6d65/adb1c93356eacd14/d2938d9db4e01a37 | Port: 9099 | Proto: HTTP.
> I1019 17:46:50.445188       1 rule.go:141] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 17:46:50.445406       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 9099 listener created
> I1019 17:46:50.464871       1 rule.go:146] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "1" | Condition: [{    Field: "path-pattern",    Values: ["/sedcloudapi/*"]  }]
> I1019 17:46:50.464893       1 rule.go:141] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 17:46:50.465052       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 1 rule created
> I1019 17:46:50.525594       1 rule.go:146] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "2" | Condition: [{    Field: "path-pattern",    Values: ["/*"]  }]
> I1019 17:46:50.525624       1 targetgroup.go:208] local/condor-condormobile-us-west-2-ingress: Start TargetGroup deletion. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7 | Name: 2e735cea-60503346710c1cf2871.
> I1019 17:46:50.525819       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2 rule created
> I1019 17:48:31.877527       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error deleting 2e735cea-60503346710c1cf2871 target group: Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> I1019 17:48:31.937550       1 lb_attachment.go:50] sg.association: modify securityGroup on LoadBalancer arn:aws:elasticloadbalancing:us-west-2:049149828659:loadbalancer/app/2e735cea-local-condorcondo-6d65/adb1c93356eacd14 to be [sg-00d8a04f32d9f6f55 sg-07442218eee712533 sg-07f2e5587987311dd]
> E1019 17:48:32.154602       1 albingress.go:291] local/condor-condormobile-us-west-2-ingress: Failed to reconcile state on this ingress
> E1019 17:48:32.154623       1 albingress.go:293] local/condor-condormobile-us-west-2-ingress:  - Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:48:32.154636       1 albingress.go:296] local/condor-condormobile-us-west-2-ingress: Will retry to reconcile in 1.003204504s
> I1019 17:48:39.331687       1 targetgroup.go:208] local/condor-condormobile-us-west-2-ingress: Start TargetGroup deletion. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7 | Name: 2e735cea-60503346710c1cf2871.
> I1019 17:50:20.697894       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error deleting 2e735cea-60503346710c1cf2871 target group: Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:50:20.734928       1 albingress.go:291] local/condor-condormobile-us-west-2-ingress: Failed to reconcile state on this ingress
> E1019 17:50:20.734952       1 albingress.go:293] local/condor-condormobile-us-west-2-ingress:  - Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:50:20.734972       1 albingress.go:296] local/condor-condormobile-us-west-2-ingress: Will retry to reconcile in 1.98343977s
> I1019 17:50:27.012878       1 targetgroup.go:208] local/condor-condormobile-us-west-2-ingress: Start TargetGroup deletion. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7 | Name: 2e735cea-60503346710c1cf2871.
> I1019 17:52:08.177349       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error deleting 2e735cea-60503346710c1cf2871 target group: Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:52:08.329995       1 albingress.go:291] local/condor-condormobile-us-west-2-ingress: Failed to reconcile state on this ingress
> E1019 17:52:08.330016       1 albingress.go:293] local/condor-condormobile-us-west-2-ingress:  - Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:52:08.330029       1 albingress.go:296] local/condor-condormobile-us-west-2-ingress: Will retry to reconcile in 3.960332927s
> I1019 17:52:15.316659       1 targetgroup.go:208] local/condor-condormobile-us-west-2-ingress: Start TargetGroup deletion. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7 | Name: 2e735cea-60503346710c1cf2871.
> I1019 17:53:56.554293       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error deleting 2e735cea-60503346710c1cf2871 target group: Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:53:56.644757       1 albingress.go:291] local/condor-condormobile-us-west-2-ingress: Failed to reconcile state on this ingress
> E1019 17:53:56.644771       1 albingress.go:293] local/condor-condormobile-us-west-2-ingress:  - Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:53:56.644785       1 albingress.go:296] local/condor-condormobile-us-west-2-ingress: Will retry to reconcile in 7.921444352s
> I1019 17:54:08.212292       1 targetgroup.go:208] local/condor-condormobile-us-west-2-ingress: Start TargetGroup deletion. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7 | Name: 2e735cea-60503346710c1cf2871.
> I1019 17:55:49.531943       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error deleting 2e735cea-60503346710c1cf2871 target group: Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:55:49.569245       1 albingress.go:291] local/condor-condormobile-us-west-2-ingress: Failed to reconcile state on this ingress
> E1019 17:55:49.569267       1 albingress.go:293] local/condor-condormobile-us-west-2-ingress:  - Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:55:49.569282       1 albingress.go:296] local/condor-condormobile-us-west-2-ingress: Will retry to reconcile in 16.096579883s
> I1019 17:56:13.891803       1 targetgroup.go:208] local/condor-condormobile-us-west-2-ingress: Start TargetGroup deletion. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7 | Name: 2e735cea-60503346710c1cf2871.
> I1019 17:57:55.051551       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"e284aac4-d3c6-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"974579", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error deleting 2e735cea-60503346710c1cf2871 target group: Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:57:55.213392       1 albingress.go:291] local/condor-condormobile-us-west-2-ingress: Failed to reconcile state on this ingress
> E1019 17:57:55.213416       1 albingress.go:293] local/condor-condormobile-us-west-2-ingress:  - Timed out trying to delete target group arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-60503346710c1cf2871/f56a6ee244987ae7
> E1019 17:57:55.213438       1 albingress.go:296] local/condor-condormobile-us-west-2-ingress: Will retry to reconcile in 31.910285073s

Below are the controller logs for `beta.6` for the same ALB deployment which was successful:

> I1019 22:31:21.451475       1 loadbalancer.go:265] local/condor-condormobile-us-west-2-ingress: Start ELBV2 creation.
> E1019 22:31:22.068472       1 loadbalancer.go:432] local/condor-condormobile-us-west-2-ingress: Failed setting Web ACL (%!s(*string=0xc000ccee80)) association: WAFUnavailableEntityException: An entity is unavailable for modification or display. Please retry.
> E1019 22:31:22.068490       1 loadbalancer.go:432] local/condor-condormobile-us-west-2-ingress: 	status code: 400, request id: b493c3f3-d3ee-11e8-8086-e124633ed364
> E1019 22:31:22.068499       1 albingress.go:290] local/condor-condormobile-us-west-2-ingress: Failed to reconcile state on this ingress
> E1019 22:31:22.068507       1 albingress.go:292] local/condor-condormobile-us-west-2-ingress:  - WAFUnavailableEntityException: An entity is unavailable for modification or display. Please retry.
> E1019 22:31:22.068514       1 albingress.go:292] local/condor-condormobile-us-west-2-ingress: 	status code: 400, request id: b493c3f3-d3ee-11e8-8086-e124633ed364
> E1019 22:31:22.068529       1 albingress.go:295] local/condor-condormobile-us-west-2-ingress: Will retry to reconcile in 499.621894ms
> I1019 22:31:22.068712       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Warning' reason: 'ERROR' 2e735cea-local-condorcondo-6d65 Web ACL (%!s(*string=0xc000ccee80)) association failed: WAFUnavailableEntityException: An entity is unavailable for modification or display. Please retry.
> 	status code: 400, request id: b493c3f3-d3ee-11e8-8086-e124633ed364
> I1019 22:31:30.389879       1 loadbalancer.go:511] local/condor-condormobile-us-west-2-ingress: Modifying ELBV2 tags to [{    Key: "kubernetes.io/cluster/condormobile-us-west-2",    Value: "owned"  },{    Key: "kubernetes.io/ingress-name",    Value: "condor-condormobile-us-west-2-ingress"  },{    Key: "kubernetes.io/namespace",    Value: "local"  }].
> I1019 22:31:30.476763       1 loadbalancer.go:537] local/condor-condormobile-us-west-2-ingress: Associating 17706cf5-53a5-45ed-9c86-b47b8a1035fd Web ACL.
> I1019 22:31:30.477038       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'MODIFY' 2e735cea-local-condorcondo-6d65 tags modified
> I1019 22:31:30.547538       1 targetgroup.go:221] local/condor-condormobile-us-west-2-ingress: Start TargetGroup creation.
> I1019 22:31:30.547614       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Warning' reason: 'ERROR' 2e735cea-local-condorcondo-6d65 Web ACL (17706cf5-53a5-45ed-9c86-b47b8a1035fd) association failed: WAFUnavailableEntityException: An entity is unavailable for modification or display. Please retry.
> 	status code: 400, request id: b9a22b3b-d3ee-11e8-8086-e124633ed364
> I1019 22:31:32.476270       1 targetgroup.go:226] local/condor-condormobile-us-west-2-ingress: Succeeded TargetGroup creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-4266919f28f21e3b33b/54734c28e1c32af8 | Name: 2e735cea-4266919f28f21e3b33b.
> I1019 22:31:32.476306       1 targetgroup.go:221] local/condor-condormobile-us-west-2-ingress: Start TargetGroup creation.
> I1019 22:31:32.476565       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2e735cea-4266919f28f21e3b33b target group created
> I1019 22:31:33.932612       1 targetgroup.go:226] local/condor-condormobile-us-west-2-ingress: Succeeded TargetGroup creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:targetgroup/2e735cea-2e8e379fe0cdd148c24/6a137e16e2bb173f | Name: 2e735cea-2e8e379fe0cdd148c24.
> I1019 22:31:33.932909       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2e735cea-2e8e379fe0cdd148c24 target group created
> I1019 22:31:33.933450       1 listener.go:195] local/condor-condormobile-us-west-2-ingress: Start Listener creation.
> I1019 22:31:34.522134       1 listener.go:200] local/condor-condormobile-us-west-2-ingress: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:listener/app/2e735cea-local-condorcondo-6d65/465308fbf4585888/5cdfd458494ac0b9 | Port: 9001 | Proto: HTTPS.
> I1019 22:31:34.522157       1 rule.go:149] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 22:31:34.522248       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 9001 listener created
> I1019 22:31:34.849410       1 rule.go:154] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "1" | Condition: [{    Field: "path-pattern",    Values: ["/sedcloudapi/*"]  }]
> I1019 22:31:34.849434       1 rule.go:149] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 22:31:34.849605       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 1 rule created
> I1019 22:31:34.880994       1 rule.go:154] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "2" | Condition: [{    Field: "path-pattern",    Values: ["/*"]  }]
> I1019 22:31:34.881014       1 listener.go:195] local/condor-condormobile-us-west-2-ingress: Start Listener creation.
> I1019 22:31:34.881192       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2 rule created
> I1019 22:31:34.952312       1 listener.go:200] local/condor-condormobile-us-west-2-ingress: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:listener/app/2e735cea-local-condorcondo-6d65/465308fbf4585888/075a1ca687d4f3dc | Port: 9000 | Proto: HTTP.
> I1019 22:31:34.952342       1 rule.go:149] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 22:31:34.952558       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 9000 listener created
> I1019 22:31:34.984468       1 rule.go:154] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "1" | Condition: [{    Field: "path-pattern",    Values: ["/sedcloudapi/*"]  }]
> I1019 22:31:34.984489       1 rule.go:149] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 22:31:34.984733       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 1 rule created
> I1019 22:31:35.006380       1 rule.go:154] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "2" | Condition: [{    Field: "path-pattern",    Values: ["/*"]  }]
> I1019 22:31:35.006408       1 listener.go:195] local/condor-condormobile-us-west-2-ingress: Start Listener creation.
> I1019 22:31:35.006650       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 2 rule created
> I1019 22:31:35.032417       1 listener.go:200] local/condor-condormobile-us-west-2-ingress: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-west-2:049149828659:listener/app/2e735cea-local-condorcondo-6d65/465308fbf4585888/e863d42a5be96f68 | Port: 9099 | Proto: HTTP.
> I1019 22:31:35.032437       1 rule.go:149] local/condor-condormobile-us-west-2-ingress: Start Rule creation.
> I1019 22:31:35.032588       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"condor-condormobile-us-west-2-ingress", UID:"b02f6954-d3ee-11e8-a03d-060b8f4f62ca", APIVersion:"extensions/v1beta1", ResourceVersion:"1174023", FieldPath:""}): type: 'Normal' reason: 'CREATE' 9099 listener created
> I1019 22:31:35.058818       1 rule.go:154] local/condor-condormobile-us-west-2-ingress: Completed Rule creation. Rule Priority: "1" | Condition: [{    Field: "path-pattern",    Values: ["/sedcloudapi/*"]  }]

**Comment by d-nishi** [comment]
@M00nF1sh

**Comment by M00nF1sh** [comment]
Hi, 
are you using image: `quay.io/coreos/alb-ingress-controller:1.0-beta.7` with ` imagePullPolicy: Always`? 
I'm asking because we `re`-released the beta.7 version. (untag & re-tag) after found a bug that can cause similar problem as the log suggests (https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/648).

**Comment by gprasad84** [comment]
Hi @M00nF1sh ,

We are setting `imagePullPolicy: always` in the ingress controller deployment file.
Can you tell me what is the expected SHA256 value of the `1.0-beta.7` image ? This is what we are using: `1051de82d31df737263e5b4e290a899073322d8ec66e53c9ec5e650ca8edb7d6`

**Comment by M00nF1sh** [comment]
The hash is correct. So there should be other bug that cause this.
Would you sent me your ingress & deployment yaml so i can investigate (yyyng@amazon.com) 😄
