### ISSUE TITLE
Feature: Option to turn off continuous syncing

### ISSUE THREAD

**Issue by rmn36** [kubernetes-sigs/aws-alb-ingress-controller#690]
Currently it appears the behavior is that the controller creates the necessary AWS objects for an ALB (Security Groups, Target Groups, etc). Then as it runs it also syncs the configuration periodically so if a security group managed by the alb-ingress-controller is changed manually in the AWS console those changes are overwritten. 

This would be similar in effect to the option given by external-dns `policy=upsert-only` or `policy=sync`.

**Comment by M00nF1sh** [comment]
will take a look for this. 
Personally I like the idea of only reconcile rules managed by alb controller, maybe by adding a special description for the rules. like `[k8s.io/description]: rules to support ingress traffic`. Then any rule not prefixed with [k8s.io/description] are untouched.

**Comment by bigkraig** [comment]
The upsert annotation is about the only way I can get behind this. It's an inherently risky proposal to allow drift from the managed ALB and the ingress definition, akin to manually modifying your pods after they are deployed. For whatever reason this keeps coming up though. The users would need to understand that once they set `upsert-only` on an ingress they are signing up for an unexpected reshuffling of rules or settings when an ingress is updated.

**Comment by saket9550** [comment]
> The upsert annotation is about the only way I can get behind this. It's an inherently risky proposal to allow drift from the managed ALB and the ingress definition, akin to manually modifying your pods after they are deployed. For whatever reason this keeps coming up though. The users would need to understand that once they set `upsert-only` on an ingress they are signing up for an unexpected reshuffling of rules or settings when an ingress is updated.

can you please let me know how did you solve this issue?
I am trying to manully add some listeners as well as modifying security groups.But it gets deleted after a while.
