### ISSUE TITLE
Feature: Annotation for Default Security Group Rules

### ISSUE THREAD

**Issue by iAnomaly** [kubernetes-sigs/aws-alb-ingress-controller#691]
Currently bring your own security group(s) is supported with the annotation `alb.ingress.kubernetes.io/security-groups` and absent that, you get a default SG on the ALB AND on the target instance(s) for the configured protocols and ports.

While this is a great start, it would also be convenient to have a middle ground where the default SGs could be configured with a custom whitelist not unlike the Kubernetes Service resource LoadBalancer type's `loadBalancerSourceRanges` annotation. Perhaps something like `alb.ingress.kubernetes.io/default-security-group-source-ranges:` that accepts a list of IP CIDR or SG IDS? This avoids having to maintain the security group(s) externally but still enables custom rules. This list should override the current default 0.0.0.0/0 rule; not merge with it such that 0.0.0.0/0 could be optionally omitted.

**Comment by M00nF1sh** [comment]
Hi, what's your use case for custom rules for the default created securityGroup?
Since it's only purpose is for the alb to reach it.

**Comment by iAnomaly** [comment]
Ideally I'm just looking for the ALB Ingress Controller analog of this existing feature: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service

**Comment by M00nF1sh** [comment]
/kind feature
Sorry for the late reply. This looks like a legit use case. We can add support for this(limit access to the internet facing LB)

BTW, not sure whether you are aware of this,  if you only want your loadBalancer be accessible within your VPC, you can use `alb.ingress.kubernetes.io/scheme:internal`.

**Comment by iAnomaly** [comment]
Great finding this @M00nF1sh. I just tried it:
```
alb.ingress.kubernetes.io/security-group-inbound-cidrs:
  - 10.0.0.0/24
  - 10.0.1.0/24
```
But it fails:
`error: error validating "deploy/ingress.sbxdev.yaml": error validating data: ValidationError(Ingress.metadata.annotations.alb.ingress.kubernetes.io/security-group-inbound-cidrs): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
`

Given that it only supports type "string" the workaround for now is to use YAML's _folded style_ block scalar with the _strip_ block chomping to exclude the final newline:
```
alb.ingress.kubernetes.io/security-group-inbound-cidrs: >-
  10.0.0.0/24,
  10.0.1.0/24
```

We can make this work for now @M00nF1sh but I would love to see type "array" support added to allow additional YAML syntactic sugar such as inline comments and dropping trailing commas:
```
alb.ingress.kubernetes.io/security-group-inbound-cidrs:
  # Office CIDR
  - 10.0.0.0/24
  # Some other CIDR
  - 10.0.1.0/24
```

Thanks again for finding this.

**Comment by M00nF1sh** [comment]
@iAnomaly hi, that annotation is actually comma-separated string, you should use 10.0.0.0/24,10.0.1.0/24 instead. 😄
