### ISSUE TITLE
Possibility to disable periodic rule check/modification

### ISSUE THREAD

**Issue by JakubJecminek** [kubernetes-sigs/aws-alb-ingress-controller#704]
Hi, 
I've noticed that ingress is automatically doing rebuild/refresh of rules in ALB every hour.
Is there possibility to disable this behaviour? 

Currently I have workaround for missing feature (https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/592) that i use ingress to create rule for service, and then run script that is using aws sdk to modify created rule and add authentication-oidc action. It works but ingress is removing this modification every hour during some periodic "refresh" therefore I need to somehow disable this functionality until it is possible to specify authentication directly in ingress annotation.

**Comment by M00nF1sh** [comment]
it's more easier to support the OIDC and cognito than this one 😄, i'll start to work on OIDC and cognito support :D
