### ISSUE TITLE
Migrate from travis to Prow

### ISSUE THREAD

**Issue by M00nF1sh** [kubernetes-sigs/aws-alb-ingress-controller#706]
To align with the k8s community and also run e2e test efficiently , let's migrate from travis to Prow

pending works:
- [x] Add lint & unit test into upstream prow
- [ ] mount coveralls token & dockerhub/quay token into upstream prow
- [x] do coverage analysis on prow
- [ ] do release on prow via post-submit jobs
- [ ] Add e2e test cases into upstream prow

**Comment by Jeeppler** [comment]
What is Prow?

**Comment by M00nF1sh** [comment]
> What is Prow?

Is an centralized CI/CD tool for kubernetes projects(https://github.com/kubernetes/test-infra/tree/master/prow). (drop-in replacement of travis/jinkens)

With it, we can added integration tests for ALB ingress controller for each PR or run periodically.
