### ISSUE TITLE
Error: You cannot set the isDefault parameter for a certificate

### ISSUE THREAD

**Issue by cjbottaro** [kubernetes-sigs/aws-alb-ingress-controller#712]
```
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    1.0-beta.7
  Build:      git-438c750
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

...

E1101 22:18:56.384924       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to create listener due to ValidationError: You cannot set the isDefault parameter for a certificate.\n\tstatus code: 400, request id: 1f846854-de24-11e8-92b7-b33e3ca15102"  "Controller"="alb-ingress-controller" "Request"={"Namespace":"default","Name":"router"}
```

I'm using IAM stuffs from:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/iam-policy.json.

✌️

**Comment by JakubJecminek** [comment]
I have experienced this too. But only on master build. The beta 7 did not contain this problem. I think it is some sort of regression. When I compared rules.go in beta7 and master, it seems it was completely rewritten.

**Comment by cjbottaro** [comment]
Ahh, indeed I am using the `latest` tag for the Docker image. I think I needed it to get past a bug last time I was fiddling with this (around beta4).

**Comment by cjbottaro** [comment]
Confirmed, the `1.0-beta.7` tag works fine.
