### ISSUE TITLE
Support region without WAF

### ISSUE THREAD

**Issue by Rowern** [kubernetes-sigs/aws-alb-ingress-controller#720]
We are deploying a k8s cluster in eu-west-3 and the alb-ingress-controller is crashing with the following error.

I saw this related issue #439 but no resolution is available (a PR https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/622 was opened but never merged).

Is there any plan to support region without WAF?

**Comment by Rowern** [comment]
If anyone want it I created this image where the WAF part is commented (because I don't know enough go to correctly fix it): https://hub.docker.com/r/rowern/alb-ingress-controller-helm/
The code is here (to build it yourself): https://github.com/Rowern/aws-alb-ingress-controller/tree/remove-waf

**Comment by M00nF1sh** [comment]
@Rowern will you be able to test https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/728 in eu-west-3? I don't have a cluster at hand at test it out 😄 
The image i built is docker.io/m00nf1sh/alb-ingress-controller:pull-728, you can built it by checkout #728, and update the makefile to  
```
TAG?=pull-728
PREFIX?=dockerHubUsername/alb-ingress-controller
```
and executing `make clean && make container && make push`

**Comment by Rowern** [comment]
@M00nF1sh Sorry for the delay, I just pulled the latest version (v1.0.0) and added the feature gate waf to false and it seems to work (at least no more errors nor crashes)!

Thank you very much for your work! Looking forward to new releases :)

```
helm registry upgrade quay.io/coreos/alb-ingress-controller-helm -- \
  --set clusterName=redacted \
  --set awsRegion=eu-west-3 \
  --set 'image.pullPolicy=Always' \
  --set podAnnotations."iam\.amazonaws\.com/role"='redacted' \
  --set extraArgs."feature-gates"='waf=false' \
  alb-ingress
```

**Comment by M00nF1sh** [comment]
> @M00nF1sh Sorry for the delay, I just pulled the latest version (v1.0.0) and added the feature gate waf to false and it seems to work (at least no more errors nor crashes)!
> 
> Thank you very much for your work! Looking forward to new releases :)
> 
> ```
> helm registry upgrade quay.io/coreos/alb-ingress-controller-helm -- \
>   --set clusterName=redacted \
>   --set awsRegion=eu-west-3 \
>   --set 'image.pullPolicy=Always' \
>   --set podAnnotations."iam\.amazonaws\.com/role"='redacted' \
>   --set extraArgs."feature-gates"='waf=false' \
>   alb-ingress
> ```

You should be able to achieve same effect without specify feature-gates==false, it will be automatically detected 😄
