### ISSUE TITLE
Communication between controller and AWS broken.

### ISSUE THREAD

**Issue by stafot** [kubernetes-sigs/aws-alb-ingress-controller#722]
Trying to replace ingress resources but they are not get updated.
Release used: `1.0-beta.7`
Errors output on controller:
``` E1106 16:15:48.244685       1 checker.go:54] Controller health check failed: [acm.ListCertificates]: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E1106 16:16:31.980054       1 checker.go:54] Controller health check failed: [acm.ListCertificates]: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
W1106 16:17:15.677236       1 queue.go:130] requeuing sync aws status, err NoCredentialProviders: no valid providers in chain. Deprecated.
 ```

Last update done and worked: 31, Oct 18

**Comment by M00nF1sh** [comment]
Hi.
How do you grant permissions to alb-ingress-controller? Via `hard-coded AWS_ACCESS_KEY_ID in environment variable` or `kube2-iam` or relies on `permissions given as node instance role for worker nodes`?

**Comment by stafot** [comment]
I didn't change anything on my configuration between the period it worked and the period it is broken.

**Comment by stafot** [comment]
Now understood what happened but I still don't get why. I have an iam role policy which is attached on my kubernetes worker node. Seven days ago that I updated an ingress this setup worked. But now seems that either I need to setup a pair of aws credentials with a similar policy attached as a user policy. Or setup `kube2iam` or `kiam`.

**Comment by stafot** [comment]
@M00nF1sh I achieved to regain access using aws credentials and aws iam user policy instead of role policy. But now running into a new issue 
```APIVersion:"extensions/v1beta1", ResourceVersion:"13320894", FieldPath:""}): type: 'Warning' reason: 'ERROR' error instantiating load balancer: EC2MetadataRequestError: failed to get EC2 instance identity document caused by: RequestError: send request failed ```

**Comment by stafot** [comment]
@M00nF1sh I assume this https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/689 will solve my issue. Am I right?

**Comment by M00nF1sh** [comment]
@stafot, you should set an environment variable to the controller-pod yaml of `AWS_VPC_ID` to be VPC_ID of your cluster. It's will be required in future releases when ec2Metadata is unavailable.(it's already supported in current 1.0-beta.7 release)

**Comment by stafot** [comment]
Thanks!!!!!

**Comment by M00nF1sh** [comment]
did it work for you? 😄

**Comment by stafot** [comment]
@stafot Yes worked. Thanks for your help.
