### ISSUE TITLE
Share the single ALB 

### ISSUE THREAD

**Issue by manojbadam** [kubernetes-sigs/aws-alb-ingress-controller#724]
I'm following through getting started guide and examples `echoserver` and `2048-game`. I'm expecting the same ALB (with different rules & target groups) will be used for the both the ingress definitions in different namespaces. But I can see two different ALB's created, one for echo server and other for 2048-game. Is this expected ? or any configuration changes to make it happen ?

**Comment by M00nF1sh** [comment]
Hi, it's not supported for now.
we are going add support for this, details can be viewed in #688

**Comment by manojbadam** [comment]
Thanks @M00nF1sh also, another question - Is there a way can we assign the existing ALB (spin up outside of ingress-controller, through terraform/cloudformation) to the ingress definitions through annotations ?

**Comment by M00nF1sh** [comment]
@manojbadam It's also not supported, and haven't been planed yet. 
Can you share me your use case for this? I can only think of two scenario for it:

1. Some organization have some strict policy that requires every ALB needs to be created by their own IT infrastructure system. (But if so, how can they deal with k8s service with LoadBalancer type?)

1. You are doing migrating an existing infrastructure into k8s. e.g. for /api/products, route traffic to existing system, for /api/orders, route traffic to system powered by k8s. (For this case, it will be complicated to support since we need to know which rule are created for k8s)

**Comment by rifelpet** [comment]
for what its worth, we solve your stickyness issue by enabling deletion protection:

```
alb.ingress.kubernetes.io/attributes: deletion_protection.enabled=true
```

That way if all the services are deleted or the ingress is accidentally deleted, the ALB is not deleted and once the services or ingress are recreated, connectivity will be restored with no change in DNS. To truly delete the ALB, just remove the annotation first, then delete the ingress.

**Comment by tdmalone** [comment]
Relevant: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/914

**Comment by Giaco9** [comment]
Any news on this? I'm really interested in the support of already existent ALB in order to migrate our ECS workload to EKS. Is there any issue that I should follow? 

Thanks

**Comment by M00nF1sh** [comment]
@Giaco9 Hi, there is an alpha version to use single ALB. (And it can reuse existing external-provisioned  alb ideally by apply proper tags, but we don't plan to maintain support for that case)

**Comment by tdmalone** [comment]
@Giaco9 #914 is probably the best issue to watch currently.
There's a few though - I've listed them here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/914#issuecomment-505689241

**Comment by Giaco9** [comment]
Thank you @tdmalone I subscribed to #914

@M00nF1sh what do you mean "we don't plan to maintain support for that case"? Is it like "use it as your own risk"? 

Thank you :)

**Comment by M00nF1sh** [comment]
> Thank you @tdmalone I subscribed to #914
> 
> @M00nF1sh what do you mean "we don't plan to maintain support for that case"? Is it like "use it as your own risk"?
> 
> Thank you :)

Yes. For example, the controller will try to delete the LB when you delete the Ingress. To fully support use external LB, an new annotation like external-lb should be added. There are many edge case around external LB usage, like how to handle existing listener / rules on the LB.

**Comment by npolagani** [comment]
I was able to use one ALB for multiple Ingress Resources in Version 1.0.1. I did create a new cluster and installed Version 1.1.2, which is creating a new ALB for each Ingress Resource. Is there anyway that I can use same ALB in 1.1.2 ?

**Comment by tdmalone** [comment]
^ cross-posted at https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/984#issue-475466050, https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/228#issuecomment-517112339
