### ISSUE TITLE
ALB controller not limited to its ingressClass

### ISSUE THREAD

**Issue by AndresPineros** [kubernetes-sigs/aws-alb-ingress-controller#731]
**Versions**
Kubernetes Server v1.10.6
ALB controller 1.0-beta.7

**Issue**
The controller tries to create AWS resources for ingresses with no ingressClass annotation, even though the first line of the log says that it'll listen for ingressClass "alb".

**Comment by M00nF1sh** [comment]
@AndresPineros 
Hi， can you share some logs for this？

**Comment by M00nF1sh** [comment]
This is fixed in master branch.
If you don't specify `--ingress-class=alb`, both empty ingressClass or ingressClass alb will be targeted
If you specify `- --ingress-class=alb`, only ingressClass alb will be targeted.
We'll release a version for master branch soon

**Comment by M00nF1sh** [comment]
close this issue since the v1.0.0 release fixed this behavior 😄
