### ISSUE TITLE
Auto discovery for cluster-name

### ISSUE THREAD

**Issue by mats16** [kubernetes-sigs/aws-alb-ingress-controller#745]
AWS region can be discovered from ec2metadata, it is so cool.
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/v1.0.0/docs/examples/alb-ingress-controller.yaml#L50-L53

But we must describe the cluster name yet...

**Comment by M00nF1sh** [comment]
cluster name can be detected too 😄 
Actually i have added it into https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/726

However, most k8s distributions on aws are slightly different. I have to investigate all of them to found the best way to discover cluster name. Currently seems the tags on subnet is a good place.

**Comment by mats16** [comment]
Thank you, it is good news for me.
Is it better to close this issue?

> Currently seems the tags on subnet is a good place.
I wonder it is better use the tags on instances. (using API or metadata)

**Comment by M00nF1sh** [comment]
Yeah, we can close this issue.
some kops distribution didn't apply the kubernetes.io/cluster/cluster-name to instances.(i need to check their source code for this).

**Comment by akhilles** [comment]
Can this be reopened? https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/726 was closed but cluster name auto-detection hasn't been merged.

**Comment by bagel-dawg** [comment]
I, too would like to see this included. It's important for my use case to be as generic as possible, so automated discovery is a key feature.
