### ISSUE TITLE
Reconciler error: error getting web acl for load balancer

### ISSUE THREAD

**Issue by kumud-pe** [kubernetes-sigs/aws-alb-ingress-controller#749]
This is happening for clusters running in regions where there is no waf support.

**Comment by M00nF1sh** [comment]
Hi, the waf related functionality can be explicitly disabled by adding --feature-gates=waf=false flag 😄

Ideally it's automatically detected, but you need to specify it for this case since the client sdk thought waf is available in  ap-south-1

**Comment by kumud-pe** [comment]
Thanks for pointing this out. I will try it out.

**Comment by AndresPineros** [comment]
@M00nF1sh Hey, where should I specify this flag `--feature-gates=waf=false`, the ALB controller or somewhere in the ingress? I'm getting the same error for ca-central-1. Thanks!

**Comment by M00nF1sh** [comment]
@AndresPineros , in the yaml of the controller.
If you install it via helm, add `--set extraArgs."feature-gates"='waf=false' ` in helm upgrade command.
If you install it via kubectl, add `- --feature-gates=waf=false` to the `spec->containers->args` section, similar to the cluster-name flag 😄

**Comment by AndresPineros** [comment]
@M00nF1sh Thanks, it worked.

**Comment by kumud-pe** [comment]
@M00nF1sh Thanks. This worked.
