### ISSUE TITLE
Do I have to manually delete old ALB?

### ISSUE THREAD

**Issue by brava-vinh** [kubernetes-sigs/aws-alb-ingress-controller#755]
I'm updated from quay.io/coreos/alb-ingress-controller:1.0-alpha.3 to 894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-alb-ingress-controller:v1.0.0. 

It provision a new ALB but didn't delete the old ALB. 

Am I expected to cleanup the old ALB during this update manually myself ?

**Comment by M00nF1sh** [comment]
Hi，
I'm afraid you have to manually cleanup the old ALB for this upgrade. (from beta.6/beta.7 to v1.0.0, such manual actions are not needed).
We'll avoid such manual actions for upgrades after v1.0.0.

**Comment by brava-vinh** [comment]
Thank you @M00nF1sh Very appreciate the insight.

**Comment by sg21210** [comment]
Hi, one related question for this.
Can alb-ingress-controller(v1.1.0) detect the same ingress but different name?
I just set metadata of ingress like this,

*Before*
```
metadata:
  namespace: monitoring
  name: prometheus-operator
```
*After*
```
metadata:
  namespace: monitoring
  name: prometheus
```

As you know, it creates another alb but old alb remains. Is it able to keep track on same ingress which has different name + delete the old one?

**Comment by M00nF1sh** [comment]
@sg21210 
I believe currently it will delete the old one, otherwise it's a bug.
