### ISSUE TITLE
Let's encrypt with alb

### ISSUE THREAD

**Issue by ishaannarang** [kubernetes-sigs/aws-alb-ingress-controller#756]
can we use lets encryptvfor ssl/tls with alb-ingress controller ?

**Comment by BrianChristie** [comment]
This project is designed for use with the AWS Certificate Manager service, which performs essentially the same function as Let's Encrypt in this case. You can either get a certificate issued by Amazon, or upload your own certificate. 

See: https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html

**Comment by Nurlan199206** [comment]
AWS certificate Manager absolutely garbage...

i'm issued for my subdomain and it's shows untrusted in browser..
