### ISSUE TITLE
WAF setup error.

### ISSUE THREAD

**Issue by stafot** [kubernetes-sigs/aws-alb-ingress-controller#758]
Steps done: 
1) Upgraded controller resource to use v1.0.0 container.
2) Added     `alb.ingress.kubernetes.io/web-acl-id: "<my-id>" `
As instructed on https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/728
3) Upgraded iam-policy as instructed on https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.0.0

On step 2 tried also with unquoted and single-quoted values. 
I wonder if some permissions are missing on IAM policy. 

Getting the following error:
`Error: "E1130 11:19:22.751311       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="error fetching web acl <my-id>: WAFNonexistentItemException: The referenced item does not exist.\n\tstatus code: 400, request id: c9c49984-f491-11e8-928f-cb6290a3496d"  "Controller"="alb-ingress-controller" "Request"={"Namespace":"default","Name":"my-alb-ingress"}"`

Am I missing something @M00nF1sh ?

Also related with: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/608

**Comment by lee5i3** [comment]
I just attached mine..

`alb.ingress.kubernetes.io/web-acl-id: "<id>"

It will also require the IAM permission `waf-regional:AssociateWebACL`

Make sure you are also using ALB WAF and not CloudFront WAF they are different
`

**Comment by M00nF1sh** [comment]
@stafot sorry for the late reply. both unquoted/single quoted should work.
Did your web-acl-id exists in your region? lee5i3 is right, you should use regional WAF

**Comment by stafot** [comment]
Thanks both for your answers. Yes my problem was that I initially tried to use a non regional waf. Thanks for this clarification.
