### ISSUE TITLE
Security group conflict ALB + LoadBalancer (ELB) services

### ISSUE THREAD

**Issue by hollowimage** [kubernetes-sigs/aws-alb-ingress-controller#761]
I ran into an issue with ALB controller when also using ELB controller (running them in parallel).

ALB controller creates a second security group for ALBs, and when you reboot a node (cluster created with kops), the new node comes up with 2 security policies. nodes.clustername.com and the new alb policy, this leads to issues when creating new ELBs on the cluster when you create any ELB type service

```
Warning  CreatingLoadBalancerFailed  4m               service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service kube-system/ingress-nginx: Multiple tagged security groups found for instance i-xxxxxxxxxxx; ensure only the k8s security group is tagged
```
because of this, i think the api has issues creating new services in aws. ive yet to play more with this, but 

the solution is to amend the SG for each instance-group maybe?

**Comment by M00nF1sh** [comment]
This is introduced by the change of tagging securityGroups created by ingress controller. The core k8s(aws) also used the tags on securityGroup to discover securityGroups for ELB.

Current mitigation: 
1. manually create an securityGroup for LoadBalancers(sg-xxxx) that allow inbound traffic from internet.
2. modify node securityGroups for your k8s cluster to allow inbound traffic from sg-xxxx.
3. specify annotation `alb.ingress.kubernetes.io/security-groups: sg-xxxx` on ingress.

Short term change to fix this:
1. revert the tag changes for targetGroups(removing the 'kubernetes.io/cluster/clusterName:owned' tag on securityGroup)

Longer term changes to fix this:
1. Figure out how to play well with k8s core's securityGroups discovery mechanism and play well with it, or change k8s core.

**Comment by M00nF1sh** [comment]
@hollowimage Hi, i have cut a new release v1.0.1 that contains fix for this issue 😄

**Comment by hollowimage** [comment]
I stand corrected, this immediately resolved the ELB conflicts.

Thank you so much @M00nF1sh 👏

**Comment by dhineshbabuelango** [comment]
> This is introduced by the change of tagging securityGroups created by ingress controller. The core k8s(aws) also used the tags on securityGroup to discover securityGroups for ELB.
> 
> Current mitigation:
> 
> 1. manually create an securityGroup for LoadBalancers(sg-xxxx) that allow inbound traffic from internet.
> 2. modify node securityGroups for your k8s cluster to allow inbound traffic from sg-xxxx.
> 3. specify annotation `alb.ingress.kubernetes.io/security-groups: sg-xxxx` on ingress.
> 
> Short term change to fix this:
> 
> 1. revert the tag changes for securityGroups(removing the 'kubernetes.io/cluster/clusterName:owned' tag on securityGroup)
> 
> Longer term changes to fix this:
> 
> 1. Figure out how to play well with k8s core's securityGroups discovery mechanism, or change k8s core.

Regarding this:
modify node securityGroups for your k8s cluster to allow inbound traffic from sg-xxxx.
Is this for the port which we create service type load balancer or for all prots?
