### ISSUE TITLE
Is the v1.0.0 docker container meant to be public?

### ISSUE THREAD

**Issue by tghaas** [kubernetes-sigs/aws-alb-ingress-controller#765]
The docs and release page references a docker container available at 894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-alb-ingress-controller:v1.0.0

I get access denied when trying to pull this image. Is this intended to be public or private?

**Comment by M00nF1sh** [comment]
Hi, it's intended to be public.
However, you need to be an AWS customer to directly running `docker pull` (ECR limitations =.=) See [Instructions](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth)

For kubernetes clusters on AWS(EKS/KOPS/others), the step above is already done by k8s core.
See https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry
