### ISSUE TITLE
failed to find existing LoadBalancer due to AccessDenied

### ISSUE THREAD

**Issue by syst0m** [kubernetes-sigs/aws-alb-ingress-controller#766]
Trying to deploy the controller, by following the walkthrough.
Using kube2iam.
Controller pods are failing with:

> W1205 13:29:30.020159       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> -------------------------------------------------------------------------------
> AWS ALB Ingress controller
>   Release:    v1.0.0
>   Build:      git-c25bc6c5
>   Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
> -------------------------------------------------------------------------------
> 
> I1205 13:29:30.108091       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "Controller"="alb-ingress-controller" "Source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
> I1205 13:29:30.108451       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "Controller"="alb-ingress-controller" "Source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
> I1205 13:29:30.108947       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "Controller"="alb-ingress-controller" "Source"={"Type":{"metadata":{"creationTimestamp":null}}}
> I1205 13:29:30.109578       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "Controller"="alb-ingress-controller" "Source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"","osImage":"","containerRuntimeVersion":"","kubeletVersion":"","kubeProxyVersion":"","operatingSystem":"","architecture":""}}}}
> I1205 13:29:30.110700       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/ingress-controller-leader-alb...
> I1205 13:29:30.122455       1 leaderelection.go:194] successfully acquired lease kube-system/ingress-controller-leader-alb
> I1205 13:29:30.222858       1 :0] kubebuilder/controller "level"=0 "msg"="Starting Controller"  "Controller"="alb-ingress-controller"
> I1205 13:29:30.323166       1 :0] kubebuilder/controller "level"=0 "msg"="Starting workers"  "Controller"="alb-ingress-controller" "WorkerCount"=1
> E1205 13:29:30.413463       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to AccessDenied: User: arn:aws:sts::388030365049:assumed-role/primarybid-eks-dev-8h8xxBJJ20181128104159665200000009/i-0a70a99f9a9445b88 is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers\n\tstatus code: 403, request id: cb8e3187-f891-11e8-ac09-41e5de1e25cf"  "Controller"="alb-ingress-controller" "Request"={"Namespace":"default","Name":"alb-ingress"}

**Comment by syst0m** [comment]
I have added the following tags with terraform to all my VPC objects, subnets included:


 ```
   kubernetes.io/cluster/$CLUSTER_NAME where $CLUSTER_NAME is the same CLUSTER_NAME specified in the above step.
    kubernetes.io/role/elb should be set to 1 or an empty tag value for internet-facing load balancers.
```

**Comment by M00nF1sh** [comment]
@syst0m Hi, did you explicitly specified subnet via alb.ingress.kubernetes.io/subnets annotation on your ingress? If so, please make sure these subnets specified annotation exists in your aws region.

background:
If `alb.ingress.kubernetes.io/subnets` annotation presents, the controller will use these subnet to create LB.
If `alb.ingress.kubernetes.io/subnets` annotation didn't presents, the controller will try to discover subnets via tags on our AWS subnets.
```
kubernetes.io/cluster/mycluster = shared 
kubernetes.io/role/elb = 1
```

**Comment by syst0m** [comment]
Hi @M00nF1sh 
I'm not using annotations, I'm using the tags, which I configured in the terraform eks module.
I checked from the AWS console, I can see the tags on all of my subnets,
both private and public.

The walkthrough mentions specifying at least two subnets, why is that?
Also, does the alb-ingress-controller need to be in the same subnet as the public, private or both subnets as the ones used for the ec2 instances?

**Comment by syst0m** [comment]
I just tried adding an annotation, listing all subnets.
I still get the same error.

**Comment by M00nF1sh** [comment]
another thought is the controller by default auto-discover AWS region from ec2Metadata, which maybe messed up with kube2iam's fake ec2metadata instance. Wait me investigate whether that's correct.
In the meantime, you can add an `--aws-region` parameter to the controller's yaml. (e.g. --aws-region=us-west-2)

**Comment by syst0m** [comment]
@M00nF1sh I tried configuring the AWS key and secret, and attaching the provided policy manually to my worker node role, just to make sure it's not a kube2iam issue.
Error persists.
I also specified the region, as you suggested, error persists.

**Comment by M00nF1sh** [comment]
Hi, There are two errors above.  I think you already solved the `AccessDenied` error with manually attached policy.

For the SubnetNotFound error, would you help ensure your subnets exits in the same region with your eks cluster with `aws ec2 describe-subnets --region=${yourRegion} --subnet-ids "subnet-xxx1" "subnet-xxx2"`

**Comment by syst0m** [comment]
I found, by trial and error, that I don't need to attach the policy at all, if I specify the AWS key and secret in the values.yaml.
Also, after I specify the clusterName manually in the values.yaml, the controller starts to behave as expected.
Thanks for your help, @M00nF1sh 
It is much appreciated. :)

**Comment by syst0m** [comment]
I just foudn out from the AWS console, that two LBs get created, an alb, according to my specs,
and a classic load balancer, for which I'm not sure what the purpose is.
Is this expected behaviour?

**Comment by syst0m** [comment]
Here's my values.yaml:

`  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:388030365049:certificate/08e1b236-5e97-4ae2-9919-72f44eeeae4e
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #  alb.ingress.kubernetes.io/security-groups: sg-723a380a,sg-a6181ede,sg-a5181edd
    #  alb.ingress.kubernetes.io/subnets: subnet-a4f0098e,subnet-457ed533,subnet-95c904cd
    name: alb-ingress
  #maybe later
  #namespace: dev
  spec:
    rules:
      - host: myhost.com
        http:
          paths:
            - path: /*
              backend:
                serviceName: ssl-redirect
                servicePort: use-annotation
            - path: /*
              backend:
                serviceName: nginx
                servicePort: 80
`

**Comment by syst0m** [comment]
I enabled alb access logs and I can see the request hitting the alb.
In the alb-ingress-controller pod I can see the alb being created successfully, subnets and security groups assigned.
How can Im trace the request from the alb to my nginx lb service?

**Comment by syst0m** [comment]
@M00nF1sh 
Hey, I checked the targets health, they appear as healthy.
The port is 1, I'm not sure if that's intended.
The port under `Basic Configuration`:
`The port the load balancer uses when routing traffic to targets in this target group (1-65535).`
I went to check the listener, and there's only a default action, to return a 404 fixed response.
Looks like the ingress rules aren't being translated to actions here.
How could I troubleshoot this?

**Comment by syst0m** [comment]
I found out that if I pass the host header, fo the host defined in my ingress resource rule, I can get a reply from nginx.

`curl -IH "Host: myhost.com" dfe42e68-default-albingres-d740-1924768818.eu-west-1.elb.amazonaws.com
HTTP/1.1 200 OK`

Is this expected behaviour?

**Comment by syst0m** [comment]
I also found out that the ingress does work intermitently.
I am doing load testing with ab.
It appears that when it's not working it simply times out:
`curl -IL http://myhost.com
curl: (52) Empty reply from server`

Then, it just starts working for a while and stops again.
I'm goign to examine the nginx pod logs and enable access logs on the alb.

**Comment by syst0m** [comment]
I've now configured an external http monitor, alb . access logs and heapster, fluentd logging for the pods.
When the timeouts occur, it looks like the request doesn't reach the nginx pod.
However, in the alb access logs I can't see anything wrong during the exact timestamp (to the milisecond) during which there was a a timeout reported by the external http monitor.

**Comment by syst0m** [comment]
Will open a new issue regarding the timeouts as the initial problem here was resolved.
