### ISSUE TITLE
Helm - image moved to ECR but requires authentication

### ISSUE THREAD

**Issue by faizan82** [kubernetes-sigs/aws-alb-ingress-controller#775]
For **1.0.1** image we seem to have moved to ECR but using ECR requires authentication and image pull fails as the image cannot be found. 

` Warning  Failed                 10s (x2 over 28s)  kubelet, ip-192-168-221-180.eu-west-1.compute.internal  Failed to pull image "894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-alb-ingress-controller:1.0.1": rpc error: code = Unknown desc = Error response from daemon: manifest for 894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-alb-ingress-controller:1.0.1 not found`

Trying to pull image: 

`docker pull 894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-alb-ingress-controller:1.0.1
Pulling repository 894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-alb-ingress-controller
unauthorized: authentication required`

I am upgrading from 0.1.2 to 1.0.1 using helm upgrade as below

`helm registry upgrade quay.io/coreos/alb-ingress-controller-helm -- alb-ing -f values.yaml --tls`

**Comment by M00nF1sh** [comment]
Hi, Typically k8s cluster on aws automatically setup the ECR logins(not sure whether there is an option to enable it)

We have move the image to dockerHub : docker.io/amazon/aws-alb-ingress-controller:v1.0.1
Also, the chart is published to helm repo, see instructions in https://github.com/helm/charts/tree/master/incubator/aws-alb-ingress-controller
