### ISSUE TITLE
DNS lookup issue of waf service in Singapore region when booting alb ingress

### ISSUE THREAD

**Issue by nikosheng** [kubernetes-sigs/aws-alb-ingress-controller#785]
I have encountered an issue about the waf region lookup when booting the ingress service

`kubebuilder/controller "msg"="Reconciler error" "error"="error getting web acl for load balancer arn:aws:elasticloadbalancing:ap-southeast-1:xxx:loadbalancer/app/d597c8d0-pay-paygatewayalb-886b/097fb6826e7f9566: RequestError: send request failed\ncaused by: Post https://waf-regional.ap-southeast-1.amazonaws.com/: dial tcp: lookup waf-regional.ap-southeast-1.amazonaws.com on 172.24.0.10:53: no such host"  "Controller"="alb-ingress-controller" "Request"={"Namespace":"pay","Name":"pay-gateway-alb"}`

As I have seen that this issue will be fixed by PR #728 , however, this issue is still occurred when I put in the annotation

`alb.ingress.kubernetes.io/web-acl-id: non-exists`

Is there any workaround to bypass this issue?

**Comment by M00nF1sh** [comment]
Hi, sorry for the confusing in that PR description😄 

You should add an flag to the controller YAML: `--feature-gates=waf=true`(similar to the --cluster-name=xxx flag).
You shouldn't apply the "alb.ingress.kubernetes.io/web-acl-id: non-exists" to ingress, i just used it to test the featuregate works 😄
