### ISSUE TITLE
v1 ignore host header

### ISSUE THREAD

**Issue by jh-sz** [kubernetes-sigs/aws-alb-ingress-controller#789]
I notice that the ignore host header annotation is being removed in v1, and understand that if we want to ignore host, just not specifying it in the ingress. The problem I have with this is that I am also using external-dns, and fail to find a solution where I would like external-dns to manage the host on route 53 but would still like to ignore host for the alb

**Comment by M00nF1sh** [comment]
@jh-sz 
Hi, you can see the reason and alternative for your problem in this issue: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/776 
😄

**Comment by jh-sz** [comment]
thank you, that works, the doc on external-dns isn't update to dated
