### ISSUE TITLE
Healthcheck for service on a secondary port when using NodePort

### ISSUE THREAD

**Issue by backjo** [kubernetes-sigs/aws-alb-ingress-controller#799]
On a service, we can currently specify "alb.ingress.kubernetes.io/healthcheck-port" to have the healthcheck for the generated TargetGroup use a secondary port. It would be nice to have some way to configure this to accept a port name, so that the ALB Ingress Controller could lookup the NodePort for that name and use it

**Comment by M00nF1sh** [comment]
seems like a legitimate use case. The only troubling part i can think of is it currently support an special port called "traffic-port", if some user do have a port called "traffic-port" on their service(unlikely this will happen though), we need to be clear about the behavior in this case and document it.
/kind feature

**Comment by backjo** [comment]
Implemented in #802
