### ISSUE TITLE
Instance-based target health checks can get expensive/chatty with large clusters

### ISSUE THREAD

**Issue by backjo** [kubernetes-sigs/aws-alb-ingress-controller#806]
Right now, TGs for services that have target-type instance include all nodes in the K8s cluster. For a small service (2 pods) running in a larger cluster(let's say 50 nodes), this can result in a disproportionately large number of health checks hitting individual pods.

**Comment by M00nF1sh** [comment]
this is an interesting point 👍 .
I think ideally customers can get ride of this issue with target-type IP.
For target-type instance, the healthy check is to ensure every target(node port proxy) is healthy, which is unavoidable to overwhelming pods in cases you described above.  Customers should explicitly adjust [healthcheck-interval-seconds](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#healthcheck-interval-seconds) via annotation.

I think it's worth to add an tip section to the above annotation for this case. 😄

**Comment by backjo** [comment]
I'm wondering if it would make sense to have some kind of annotation for this case where you could only forward traffic to instances that have a pod for that service (though I wouldn't go so far as to say it should be guaranteed that pod is running on that instance since there might be delay between calculating which nodes have ready pods and which ones are ). It'd guarantee that, at most, you're running N health checks where N is the number of pods, instead of running M where M is the number of nodes. 

Definitely agree that target-type IP solves this, but for people that aren't running the aws-vpc-cni this might help - especially in larger, multi-tenant clusters.

**Comment by rifelpet** [comment]
Services already support `externalTrafficPolicy` which behaves similar to what you describe. `kube-proxy` will only forward requests for that node port to pods located on the same node. If there are no pods on that node, I believe kube-proxy will timeout, causing the ALB's healthcheck to fail on that instance.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#servicespec-v1-core

https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

It does result in potentially imbalanced traffic if pods are not evenly distributed across nodes. I haven't gotten this to work on my Kops cluster in AWS though, I've read in other GH issues that it may be related to DHCP options and an assumption in Kubernetes about the FQDN of the node, but that may be out of date.

**Comment by M00nF1sh** [comment]
Actually it's supported by services, you can set "spec.ExternalTrafficPolicy" to "local" instead of default one(cluster). which instances only forward traffic to pods on it, and simply drop the traffic if there is no pods on it. (these instances without pods on it will still be registered as ALB target, but failing healthcheck)

**Comment by M00nF1sh** [comment]
> Services already support `externalTrafficPolicy` which behaves similar to what you describe. `kube-proxy` will only forward requests for that node port to pods located on the same node. If there are no pods on that node, I believe kube-proxy will timeout, causing the ALB's healthcheck to fail on that instance.
> 
> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#servicespec-v1-core
> 
> https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport
> 
> It does result in potentially imbalanced traffic if pods are not evenly distributed across nodes. I haven't gotten this to work on my Kops cluster in AWS though, I've read in other GH issues that it may be related to DHCP options and an assumption in Kubernetes about the FQDN of the node, but that may be out of date.

at least it works on EKS clusters, i haven't tested on kops though.

**Comment by backjo** [comment]
The one potential issue I'd see with going to ExternalTrafficPolicy:local would be if other pods in the cluster are trying to access the same service.

**Comment by M00nF1sh** [comment]
> The one potential issue I'd see with going to ExternalTrafficPolicy:local would be if other pods in the cluster are trying to access the same service.

Hi，as long as other pods are accessing using clusterIP of your service, you'll be fine since these traffic are directly send to pods by iptable rules instead go through nodePort proxy. (even when your service type is nodeport :D)

**Comment by backjo** [comment]
Ah nice - I guess that's why it's ExternalTrafficPolicy and not TrafficPolicy :)
