### ISSUE TITLE
Is there a way to config inbound rules for the instance security-group generated by aws-alb-ingress-controller other than using self-managed security groups

### ISSUE THREAD

**Issue by jackzzj** [kubernetes-sigs/aws-alb-ingress-controller#817]
Hi,

While using aws-alb-ingress-controller to expose our Spinnaker, I added inbound rules for the security-group attached to ALB using annotation `alb.ingress.kubernetes.io/inbound-cidrs` and found out that the other security-group that's attached to my worker nodes instance is using `1-65536` for traffic from the ALB security-group.
I'm aware of using `alb.ingress.kubernetes.io/security-groups` for ALB and using self-managed security-group for instances. Manually attaching SG to instances whenever a new ingress gets created is just tedious and overloaded ...

Just wondering if there is any option to specify inbound rules for instance SG with annotations ? or is it possible to specify an instance security-group with annotations?

**Comment by M00nF1sh** [comment]
Hi, 
What's your use case to customize the inbound rule for the managed instance group? 
The only problem i can think of is you may think 1-65536 is too open, but it's already restricted to the ALB SG only.

For self-managed securityGroup, another way is 
1. create an shared securityGroup for instance (sg-instance) and attach it to all worker nodes. 
1. create an shared securityGroup for alb (sg-alb) and specify it as annotation on ingress.
1. modify the shared securityGroup(sg-instance) to allow incoming traffic from sg-alb.
Then you don't need to do any extra work for new ingresses 😄 .

In fact, the sg-instance for now can be omitted by using the worker node securityGroups for kubernetes(just don't add descriptions to the rule that allow sg-alb reach it, the core k8s relies on descriptions on rule to reconcile the work node securityGroups). This isn't guaranteed to work in future k8s release if we changed the behavior(like remove manually created rule in worker node sg).
