### ISSUE TITLE
v1.0.1 extraordinary memory usage

### ISSUE THREAD

**Issue by patstrom** [kubernetes-sigs/aws-alb-ingress-controller#823]
![aws-alb-memory-usage](https://user-images.githubusercontent.com/8882361/51524867-5af7db80-1e2f-11e9-96d0-b2d2222fd100.png)

I am running the alb ingress controller in a relatively small (but still production) cluster and have been happy with it so far. However, it has been slowly building up memory and not freeing it. As you can see in the graph, in about a month it has allocated around 2.14GiB memory. This seems a little excessive.

The manifest file is more or less the example one in the documentation. I've changed the `cluster-name` flag and added an `iam.amazonaws.com/role` annotation since we run kube2iam. There are only 6 ingress resources in the cluster.

Is there anything I've missed? I looked through the logs but couldn't find anything of note (just a bunch of removing/adding targets). Is there a certain keyword I should look for?

**Comment by M00nF1sh** [comment]
@patstrom 
Hi, this is abnormal.
would you help run the following script and send me output heap.bin, alloc.bin and metrics.bin.
(save the below command as alb_debug.sh, and run it 😄 )
```
podName=$(kubectl get pods -n kube-system | grep alb-ingress-controller | grep Running | awk '{print $1}')
proxyCmd="kubectl port-forward $podName 10254:10254 -n kube-system"
nohup $proxyCmd &
proxyPid=$!
trap "kill -2 $proxyPid" 2

echo "Waiting port forward on 10254"
while ! nc -z localhost 10254; do   
  sleep 0.1 # wait for 1/10 of the second before check again
done

curl -o alloc.bin "http://localhost:10254/debug/pprof/allocs?debug=1"
curl -o heap.bin "http://localhost:10254/debug/pprof/heap"
curl -o metrics.bin "http://localhost:10254/metrics"

kill $proxyPid
```

**Comment by patstrom** [comment]
Unfortunately (for debugging purposes) the pod was removed and replaced yesterday evening due to autoscaling. I will keep an eye out if memory starts to build again and get you some more information. Last time it only took about 4 days to reach 1 GiB (which is already excessive) so I suppose I'll get back to you next week.


![alb-deployment-memory-usage](https://user-images.githubusercontent.com/8882361/51671081-6fbba700-1fc8-11e9-879f-01f69d68bcee.png)

**Comment by M00nF1sh** [comment]
@patstrom 
Thanks for the help 😄 . These reconcile errors shouldn't lead to the memory usage increase.

I'll do some testings on my end too, there should be some bugs that keep go object reference. The heap.bin will help we dignose the root cause when you got one 👍

**Comment by patstrom** [comment]
I've sent you an email. Not as extreme memory usage but still (imo) a bit excessive.

**Comment by M00nF1sh** [comment]
Thanks so much for the debug file,  really helpful! 👍 

1. The root cause of the memory leak in on our cache implementation for caching AWS API calls.
We [haven't set max_cache_size](https://github.com/ticketmaster/aws-sdk-go-cache/blob/master/cache/config.go#L50), which defaults to 5000. And ccache won't free memory(obj reference) even if it's expired, as long as the count of cached items are below max_cache_size. The average memory consumed per AWS API call is around 200KB(both aws client go and our cache implementation is not efficient in memory usage), so 200KB * 5000 will make the memory consumption move towards at least 1GB gradually(and will be worse than this if we cached large API results).
An naive fix  will be limit cache size to a relativly small number like 100(I can do it in next release).
And we need to think more about how to cache aws objects for a more mature fix later.

2. Another issue i noticed is the "reconcile process" happened 1204 times for all your ingress. The reconcile should only happen when serviceEndpoints changed or ingress modified, and there are also a force reconcile per 1 hour(sync-period) per ingress. So, if your service/ingress didn't change and pods are not relocated, there should only be 120 reconcile per ingressin 5 days.
Did you have around 10 ingress in your cluster? Or have you adjusted "sync-period" via controller flags? If not, I'd like to add more logs to the controller to see what happened.

**Comment by patstrom** [comment]
We have 6 ingress specified across 4 namespaces.

Both the ingress and  around ~25 service's has been modified (added service specific healthcheck path) while the controller has been running so if I understand you correctly 1204 is not necessarily unreasonable.

The only flags I have explicitly set is `--ingress-class` and `--cluster-name`.

Our controller still managed to allocate more than 2 GiB though. Can we conclude that those were unusually large API responses? In my opinion that conclusion seems like a reach without more information.

**Comment by M00nF1sh** [comment]
@patstrom ,
Then the reconcile number make sense to me.
Would you help try using this image: m00nf1sh/aws-alb-ingress-controller:iss_823
The source code is available: https://github.com/M00nF1sh/aws-alb-ingress-controller/tree/iss_823(i just setted the cache size to 50 instead of default 5000 😄 )
The memory usage should be capped to less than 200mb if my assumptions are right 😄

**Comment by patstrom** [comment]
The source code you linked seems to be even with the master branch. Where have you applied your changes? And won't it mess up things if you apply your changes to the latest version and not base them on v1.0.1?

**Comment by M00nF1sh** [comment]
> The source code you linked seems to be even with the master branch. Where have you applied your changes? And won't it mess up things if you apply your changes to the latest version and not base them on v1.0.1?

Ha...I forget to push the changes(just pushed it).
The only change is https://github.com/M00nF1sh/aws-alb-ingress-controller/blob/iss_823/pkg/cache/config.go#L75. (Added a .MaxSize(50)), the rest of code changes is vendoring the cache code(lives in another repo) into pkg.

**Comment by patstrom** [comment]
![alb-lots-of-memory](https://user-images.githubusercontent.com/8882361/52198358-da8b9e80-2862-11e9-8dbf-64d6d2c962fc.png)

Now that a pod has been restarted a lot during the weekend the memory usage has exploded and have even reached new heights. 2.7GiB.

I've emailed you the debug data and will try your patch.

**Comment by patstrom** [comment]
![alb-memory](https://user-images.githubusercontent.com/8882361/52468763-f3a98d80-2b89-11e9-8838-ee49ed24e370.png)

I have deployed your patch (You can probably figure out when I did) and the memory usage seems to be somewhat stable but it hasn't been that long so it's hard to be sure.

A mature fix for this problem would probably involve quite aggressively cleaning up this cache. While it seems to be capped at ~500MB with the patch that's still quite a lot for a controller, especially if you'd want to run it on a smaller compute instance.

**Comment by patstrom** [comment]
![alb-memory](https://user-images.githubusercontent.com/8882361/52650573-cb53c300-2eea-11e9-96d4-3130c424db08.png)

It seems it is slowly climbing again. Not nearly as quick as before though.

**Comment by patstrom** [comment]
![alb-memory](https://user-images.githubusercontent.com/8882361/52938150-370db400-3361-11e9-9637-268eebd1f8db.png)

Nevermind, it has once again climbed to an even more unreasonable amount of memory usage. This is running the iss_823 branch that you forked from master so this is the latest version and not v1.0.1.

**Comment by M00nF1sh** [comment]
this is super strange. Did you have a large number of service/endpoints/secrets? The controller keeps an in memory copy of these objects to avoid overwhelm api server.

**Comment by patstrom** [comment]
Around ~100 secrets, ~60 services and ~50 endpoints.

Why does the alb-ingress-controller need to cache secrets? What is interesting about that behaviour though is that we are running gitlab-ci-runner in this cluster, which creates (and subsequently destroys) a secret for each job it runs. If all of these secrets are cached and never cleared that could definitely be a problem.

Is there some sort of time-based eviction in the cache?

**Comment by M00nF1sh** [comment]
Hi, 
The objects(service/endpoints/secrets) are cached locally to avoid hit APIServer when get these objects.
Ideally, only needed objects(for secret, only secret for ingress OIDC are needed) should be cached. However, currently k8s don't support watch API for individual object, so all these object are been cached. 
I need to take a look at the code to see whether there is an bug there. We are using controller-runtime which used [client-go/informers](https://godoc.org/k8s.io/client-go/informers) under the hood.

**Comment by M00nF1sh** [comment]
Update:
I just found another leaking point in our API cache implementation that should actually caused your problem.. will post the details here soon, and remove the cache soon.

**Comment by patstrom** [comment]
Have you managed to make any progress on this? :)

**Comment by M00nF1sh** [comment]
@patstrom 
Hi, the new release v1.1.2 fixed this issue 😄 , would you help try it out. There is no action required for upgrade other than update image version.

**Comment by patstrom** [comment]
Of course. I will update later this afternoon and report back metrics after a few days!

**Comment by nicholasgcoles** [comment]
@M00nF1sh I am experiencing heavy alb-ingress-controller memory usage of about 20Gb in some cases. 

This was with version v1.1.0.

Going to update to v1.1.2 and see if the issue persists.

**Comment by patstrom** [comment]
![Screenshot_2019-03-19 Kubernetes Deployment metrics - Grafana](https://user-images.githubusercontent.com/8882361/54593156-2b7bde80-4a2e-11e9-814a-e0b6a62d1a2a.png)

The memory usage seems to be stable at a reasonable when running v1.1.2. Cheers!

**Comment by gaganapplatix** [comment]
FYI the solution for this is in the PR:

https://github.com/ticketmaster/aws-sdk-go-cache/pull/2

for the cache, if you guys ever decide to start reusing it.
