### ISSUE TITLE
SG not populating instead it is default SG

### ISSUE THREAD

**Issue by AndrewMcFarren** [kubernetes-sigs/aws-alb-ingress-controller#832]
Hi Team, I am using the annotation "alb.ingress.kubernetes.io/security-groups:" with one security group I created for the ALB.  However, the ALB gets provisioned with the default security group and not the one I want.  I also have inbound-cidrs and internal set.

    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8
    alb.ingress.kubernetes.io/security-groups: sg-mine

I am running EKS 1.11.5 with ALB IC version 1.1.1.  I try different permutations of annotations but it still only provisions with default SG.

**Comment by M00nF1sh** [comment]
@AndrewMcFarren 
Hi, the ALB will be initialially provisioned with default SG, but will be changed to the "sg-mine"(that you specified via annotation) within seconds. 
Do you mean the change don't happen? If so, is there any error messages in the controller pod?
Or is the initialially provision with default SG are a problem to your situation(which can be improved if it matters)

**Comment by AndrewMcFarren** [comment]
Hello, this is working now and the SG is now populating with the one I want and not the default SG.  The only change I made was to the ALB IC IAM Policy I had, which was to allow elasticloadbalancing:DescribeListenerCertificates.  I was seeing an error in kubectl log -f alb-ingress-controller-pod-id showing that this was not authorized.

**Comment by M00nF1sh** [comment]
glad it worked out 👍 
The DescribeListenerCertificates permission is added in the new v1.1.1 release. (You will need elasticloadbalancing:AddListenerCertificates and elasticloadbalancing:RemoveListenerCertificates as well, if you plan to use multiple SSL certs).

Latest set of permissions needed will always be accessible via https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/iam-policy.json, and we plan to create an managed iam policy for it 😄

**Comment by AndrewMcFarren** [comment]
Thanks for the support.  Glad to hear about the managed policy in the roadmap.
