### ISSUE TITLE
Error: "msg"="Reconciler error" "error"="no object matching key \" ... " in local store"

### ISSUE THREAD

**Issue by hieu29791** [kubernetes-sigs/aws-alb-ingress-controller#834]
Hi, I create ALB successfully but when I execute get ingress Address not show anything, I check on AWS console and ALB doesn't create any port. I check log and it show like this picture. I do exactly same as https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/ tutorial, it doesn't work, then I create simple example with wordpress and mysql, result is the same. Can anyone help me to resolve this issue? Many thanks.
Ps: I create K8s cluster with tutorial on this page: https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html
![k8s-ingress-error](https://user-images.githubusercontent.com/10827875/51884080-58116380-23b8-11e9-96c1-b7e7f7fba62e.PNG)

**Comment by hieu29791** [comment]
Deploy on Singapore region, don't support WAF, need to add - --feature-gates=waf=false option to ingress-controller.yaml file

**Comment by M00nF1sh** [comment]
Hi, did you solve your problem after disabled WAF feature?
the "no object matching key" is an expected error(happens when you create ingress/service at the same time, and the controller get notification about ingress first, the retry mechnism handles it automatically)

**Comment by hieu29791** [comment]
> 
> 
> Hi, did you solve your problem after disabled WAF feature?
> the "no object matching key" is an expected error(happens when you create ingress/service at the same time, and the controller get notification about ingress first, the retry mechnism handles it automatically)
Yes, after disable WAF, my problem is solve. I think "no object matching key" may be relate with WAF, I'm not sure but thanks for your support.
