### ISSUE TITLE
Error deleting security group -- blocks future actions

### ISSUE THREAD

**Issue by tecnobrat** [kubernetes-sigs/aws-alb-ingress-controller#838]
Hello,

We experienced an issue where the ALB ingress controller would try to delete a security group, but its unable to because that security group is attached to an ENI:

```
I0131 18:04:40.273320       1 association.go:239] default/broadct-rest: deleting securityGroup instance-fffb5690-default-broadctre-240d:managed instance securityGroup by ALB Ingress Controller
E0131 18:53:50.064119       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to clean up securityGroups due to failed to delete managed instance securityGroups due to DependencyViolation: resource sg-06e949837944fcb1c has a dependent object\n\tstatus code: 400, request id: 5e78b0ea-5640-488b-a48e-77e9b8e65234"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"broadct-rest"}
I0131 18:53:51.577637       1 targets.go:73] default/accounts-rest: Adding targets to arn:aws:elasticloadbalancing:us-east-1:339498453354:targetgroup/fffb5690-fa422a45a798e3aa998/e1883b000d36d07f: 10.64.3.173:3000, 10.64.7.195:3000, 10.64.7.55:3000
I0131 18:53:51.857310       1 targets.go:88] default/accounts-rest: Removing targets from arn:aws:elasticloadbalancing:us-east-1:339498453354:targetgroup/fffb5690-fa422a45a798e3aa998/e1883b000d36d07f: 10.64.7.115:3000, 10.64.9.121:3000, 10.64.4.69:3000
I0131 18:53:52.293483       1 instance_attachment.go:110] default/accounts-rest: detaching securityGroup sg-036b2145e928f9e39 from ENI eni-03e93de0e8ba3f125
```

For whatever reason, `instance-fffb5690-default-broadctre-240d` never got properly removed from the ENI, and now errors out when trying to delete it.

But there is another issue as well, it takes 50 minutes to timeout. During that time, the ALB controller will not take any *OTHER* unrelated actions.

You can see how as soon as it times out, it starts dealing with another un-related ALB attachment.  We have found this multiple times in our logs.  So the SG deletion is blocking, times out after 50 minutes, and probably should ensure the SG is not attached to any ENIs before deleting it.

**Comment by M00nF1sh** [comment]
@tecnobrat 
Would you help add another "-v=1" flag to the controller yaml? By default the controller won't output information if everything went good. with "-v=1", it will output things like "reconcile succeed".

**Comment by tecnobrat** [comment]
I can tell you that this SG definitely cannot be deleted, its trying over and over and over every few hours.  And it doesn't do ANYTHING for ~50 mins between the messages like at `18:04:40.273320` and `18:53:50.064119`

**Comment by M00nF1sh** [comment]
@tecnobrat 
Yes, sample below:
```yaml
    spec:
      containers:
        - name: alb-ingress-controller
          args:
            - --ingress-class=alb
            - --cluster-name=clusterName
            - -v=1
```

There should be some bugs that prevent it cleanup the securityGroup on ENIs. (what's your controller version, and are u using mode instance or mode ip?)
When ever the controller fails an reconcile, it'll retry in exponential backoff, which might cause the "50minutes" delay you observed. Any manually chance to ingress/service will cleanup the exponential backoff delay.

**Comment by tecnobrat** [comment]
We are using `ip`.

If I make a change to another pod after it starts trying to delete that SG, it won't make add my new pod 
IPs to the LB until after the SG delete times out.  I've tested this.

**Comment by eb129** [comment]
@M00nF1sh here is some output from one of our projects. Please let me know if this is what you're looking for to assist troubleshooting.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-name
  labels:
    app: app
    env: stage
    product: product
    release: releasename
  annotations:
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: "whatever.host.name"
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:1234:certificate/foo-bar"
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: servicename
            servicePort: 443
```
```yaml
# Source: service/templates/svc-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-name
  labels:
    app: app
    env: stage
    product: product
    release: releasename
spec:
  selector:
    app: app
    release: releasename
  ports:
  - name: test-rest-svc
    port: 443
    targetPort: targetport-from-deployment-spec
```

**Comment by M00nF1sh** [comment]
The root cause is an bug of CNI plugin(https://github.com/aws/amazon-vpc-cni-k8s/issues/69), which cause leaked CNI un-attached. 
I'll provide a bypass fix by tomorrow 😄
