### ISSUE TITLE
How to create Cloudwatch alarms?

### ISSUE THREAD

**Issue by mseiwald** [kubernetes-sigs/aws-alb-ingress-controller#846]
Is there a recommended way to create CW alarms for the ALB from K8s? Is it something you would consider as a feature for the alb-ingress-controller?

**Comment by M00nF1sh** [comment]
Hi, sorry for the late reply.
The only way currently is to create these alarms from CW console.  Here is [a list of metrics](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html) you can alarm on.

Integrate it with alb-ingress-controller will be a cool idea. I haven't thought how to support it yet. Since there would be different alarm types, threshold value, etc. 
I think it's worth to be a standalone controller, and extract ALB arn from ingress objects. (similar to external-DNS), so other LBs like NLB can be supported too.

**Comment by tdmalone** [comment]
In the meantime if you wanted to automate these you could call something outside of Kubernetes to do so - AWS CLI, Terraform, etc.

**Comment by tdmalone** [comment]
@mseiwald You could do a lookup of the EC2 API to list your ALBs and filter from there.

**Comment by bryant-sharethis** [comment]
Does anybody have a good solution for this?

/remove-lifecycle stale

**Comment by Vlaaaaaaad** [comment]
We are hitting a possible bug in ALB Ingress Controller which manifests by having 0 targets registered in the Target Group, as described in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1141.

To be proactive about this we wanted to set CloudWatch Alerts based on the number of healthy targets. We use Terraform to create a SecurityGroup for the ALB, an S3 bucket for logs, SSL certificates, and so on. Having the alarms defined there seemed straightforward.

Unfortunately there is no dimension to filter on. We can only filter on `AvailabilityZone`, `LoadBalancer`, or `TargetGroup` which is pretty much useless considering we have 1) many clusters in the same region and 2) many non-k8s ALBs in there and we would get spammed with alerts.

Right now we are considering using a [Lambda datasource in Terraform to get the ALB name for the metric](https://www.terraform.io/docs/providers/aws/d/lambda_invocation.html) based on the ALB tags, but it is unclear how good that will work considering that ALB Ingress Controller may replace ALBs.

Some enhancements either here( ALB Ingress Controller putting the ALB name in a SSM Parameter like AWS already does with AMIs?) or in CloudWatch( filtering based on tags), or in CloudWatch Container Insights( custom ALB metrics with proper dimensions) are desperately needed to make this reliable for production workloads.

**Comment by dusansusic** [comment]
I am running the same issue here.

**Comment by mathieux51** [comment]
Posting my workaround here in case it helps someone:
* You will need a docker image with AWS CLI, Terraform CLI and `jq`. Personnaly I used `amazon/aws-cli:latest` image and run:
```sh
yum install -y yum-utils
yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
yum -y install terraform
yum -y install jq
```

to install `terraform` and `jq`.

* Create a bash script:
```
#!/usr/bin/env bash

# Usage:
# echo '{"ingress_name": "name-of-my-ingress"}' | sh get-load-balancers-data.sh

set -o errexit
set -o nounset
set -o pipefail

function parse_input() {
  eval "$(jq -r '@sh "export ingress_name=\(.ingress_name)"')"
}

# Returns JSON array of load balancers
getLoadBalancers() {
  aws elbv2 describe-load-balancers |
    jq -r '[.LoadBalancers[] | {"arn": .LoadBalancerArn, "name": .LoadBalancerName}]'
}

# $1: [{"arn": "", "name": ""}]
# Returns ARNs separated by spaces
getAllARNs() {
  echo $1 |
    jq -r '.[] .arn' | tr '\n' ' '
}

# $1: ARNs separated by spaces
# $2: ingress name present in load balancer tags
# Returns [{"arn": "", "ingress_name": ""}]
getARNsByIngressNameInTag() {
  aws elbv2 describe-tags --resource-arns $1 |
    jq '.TagDescriptions' |
    jq '[.[] | {"arn": .ResourceArn, "ingress_name": .Tags[] | select(.Key ==
      "kubernetes.io/ingress-name") | .Value}]' |
    jq -r "[.[] | select( .ingress_name | contains(\"$2\"))]"
}

# $1:[{"arn": "", "name": ""}]
# $2: [{"arn": "", "ingress_name": ""}]
# Returns {"load_balancers": ""}. The return value needs to be a
# map[string]string (Terraform limitations), that's why we use tostring on the
# array of load balancers.
output() {
  # https://github.com/stedolan/jq/issues/1475
  jq -n \
    --argjson lbs "$1" \
    --argjson arns "$2" \
    '{lbs: $lbs, "arns": $arns}' |
    jq '{"load_balancers": [.lbs[] as $lb | (
      .arns[] | select(
        $lb.arn == .arn
      ) as $tmp | {
       "arn": $lb.arn,
       "name": $lb.name,
       "ingress_name": $tmp.ingress_name
      }
    )] | tostring}'
}

main() {
  parse_input
  loadBalancers=$(getLoadBalancers)
  allARNs=$(getAllARNs "$loadBalancers")
  ARNs=$(getARNsByIngressNameInTag "$allARNs" "$ingress_name")
  output "$loadBalancers" "$ARNs"
}
main
```
* Create alarm and alb ingress controller with terraform:
```
resource "kubernetes_ingress" ingress {
  wait_for_load_balancer = true
  metadata {
    name = local.ingress_name
    labels = {
      app = "api"
    }

    annotations = {
      "kubernetes.io/ingress.class"                    = "alb"
      "alb.ingress.kubernetes.io/scheme"               = "internet-facing"
      "alb.ingress.kubernetes.io/certificate-arn"      = var.certificate_arn
      "alb.ingress.kubernetes.io/listen-ports"         = "[{\"HTTP\": 80}, {\"HTTPS\":443}]"
      "alb.ingress.kubernetes.io/actions.ssl-redirect" = "{\"Type\": \"redirect\", \"RedirectConfig\": { \"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
    }
  }

  spec {
    rule {
      http {
        path {
          backend {
            service_name = "ssl-redirect"
            service_port = "use-annotation"
          }
          path = "/*"
        }

        path {
          backend {
            service_name = "api"
            service_port = 80
          }
          path = "/*"
        }
      }
    }
  }
}

data "external" load_balancers {
  program = ["sh", "${path.module}/get-load-balancers-data.sh"]
  query = {
    ingress_name = local.ingress_name
  }
  depends_on = [kubernetes_ingress.ingress]
}

locals {
  load_balancers = jsondecode(data.external.ingress.result["load_balancers"])
}

data "aws_lb" ingress {
  arn  = local.load_balancers[0].arn
  name = local.load_balancers[0].name
}

resource "aws_sns_topic" cloudwatch_to_pagerduty {
  name = "cloudwatch-to-pagerduty"
}

resource "aws_sns_topic_subscription" cloudwatch_to_pagerduty {
  topic_arn = aws_sns_topic.cloudwatch_to_pagerduty.arn
  protocol  = "https"
  endpoint  = "https://events.pagerduty.com/integration/{my_integration_key}/enqueue"
  endpoint_auto_confirms = true
}

resource "aws_cloudwatch_metric_alarm" alarm {
  # Add your alarm details here
  alarm_actions       = [aws_sns_topic.cloudwatch_to_pagerduty.arn]
  dimensions = {
    LoadBalancer = aws_lb.ingress.arn_suffix
  }
}
```

It's definitely not perfect but it did the trick for me.
Cheers ✌️

**Comment by JeremieDoctrine** [comment]
I shamelessly copied your code @mathieux51 but used kubectl to get the lb.

```
eval "$(jq -r '@sh "export ingress_name=\(.ingress_name)"')"

dns=$(kubectl get ingress $ingress_name -o json | jq -r '.status.loadBalancer.ingress[0].hostname')
arn=$(aws elbv2 describe-load-balancers | jq -r '.LoadBalancers[] | select(.DNSName == "'$dns'") | .LoadBalancerArn')
jq -n --arg arn "$arn" '{"arn":$arn}'
```

Thanks !
