### ISSUE TITLE
Feature Request: Promote the AWS ALB Ingress Controller Helm Chart to Stable Repository

### ISSUE THREAD

**Issue by Jeeppler** [kubernetes-sigs/aws-alb-ingress-controller#848]
The AWS ALB Ingress Controller is now for two months in the [Helm Charts Incubator](https://github.com/helm/charts/tree/master/incubator/aws-alb-ingress-controller) repository. It would be nice if the AWS ALB Ingress Controller Chart could be promoted to the Helm Chart Stable repository.

**Comment by kivagant-ba** [comment]
Duplicates https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/362

**Comment by Jeeppler** [comment]
@kivagant-ba thanks.
