### ISSUE TITLE
Will the Controller ever recreate Target Groups?

### ISSUE THREAD

**Issue by rifelpet** [kubernetes-sigs/aws-alb-ingress-controller#850]
I'm in a situation where I'd like to share the target group created by one of my ingresses with ALBs created outside of kubernetes. I will have many ALBs configured in various ways all sharing the target group created by the aws-alb-ingress-controller. I want to reuse the target group because I know it will stay up to date with pod IPs.

My concern is if the controller ever deletes the target group (which will fail because it is still in use) and recreate it with a different ARN and start keeping this new target group up to date, eventually leading to an outage on my other ALBs.

My question is, is there a guarantee that the controller will never recreate target groups if the ingress' rules do not change? I remember pre 1.0 that the naming scheme changed which did result in target groups getting recreated, I'm just wondering if that may continue to be the case in future 1.X releases.

Alternatively, if the controller had a way for me to specify a target group to use for a particular rule (possibly defined as a service annotation just like other target group properties are), then I could create it outside of the controller and have confidence that the controller will always use this target group and keep its targets up to date. Thoughts?

**Comment by M00nF1sh** [comment]
Hi, the target groups is guaranteed to not be recreated as long as your ingress don't change. Currently We'll recreate targetGroup if you changed the backend protocol(http/https) or targetType(mode ip, mode instance), since AWS API forbids us update these settings for existing TG.

Provision an TG and only populate targets is best suited to your case(since these tg are not managed by k8s). I think an CRD is better than coded it ingress controller's logic? In my ingress group implementation, i'm leverage CRDs for targetGroups, maybe i can expose it to let it be used separatly and be able to configure existing tgARN.

**Comment by rifelpet** [comment]
For anyone that comes across this issue, I learned that AWS currently has a limit on 1 load balancer per target group, meaning we cant reuse a target group for multiple ALBs. Therefor it doesn't matter whether or not the ALB Ingress Controller ever recreates its target groups.

**Comment by sillva** [comment]
> For anyone that comes across this issue, I learned that AWS currently has a limit on 1 load balancer per target group, meaning we cant reuse a target group for multiple ALBs. Therefor it doesn't matter whether or not the ALB Ingress Controller ever recreates its target groups.

That's not correct. I managed to setup more than 2 target groups on a single load balancer.

**Comment by rifelpet** [comment]
What I was trying to accomplish was the other way around: 1 target group shared by many load balancers rather than 1 load balancer with many target groups.

**Comment by sillva** [comment]
> What I was trying to accomplish was the other way around: 1 target group shared by many load balancers rather than 1 load balancer with many target groups.

I see! Never tried that, good to know it could be an issue. Thanks 👍

**Comment by rajeevchukkapalli** [comment]
> Hi, the target groups is guaranteed to not be recreated as long as your ingress don't change. Currently We'll recreate targetGroup if you changed the backend protocol(http/https) or targetType(mode ip, mode instance), since AWS API forbids us update these settings for existing TG.
> 
> Provision an TG and only populate targets is best suited to your case(since these tg are not managed by k8s). I think an separate CRD is better than code this logic into ingress controller's? In my ingress group implementation, i'm have CRDs for targetGroups, maybe i can expose it to let it be used separatly and be able to configure existing tgARN.


> Hi, the target groups is guaranteed to not be recreated as long as your ingress don't change. Currently We'll recreate targetGroup if you changed the backend protocol(http/https) or targetType(mode ip, mode instance), since AWS API forbids us update these settings for existing TG.
> 
> Provision an TG and only populate targets is best suited to your case(since these tg are not managed by k8s). I think an separate CRD is better than code this logic into ingress controller's? In my ingress group implementation, i'm have CRDs for targetGroups, maybe i can expose it to let it be used separatly and be able to configure existing tgARN.

Why my Target groups are not recreating even after I changed the backend protocol to HTTPS from HTTP. I changed at both INgress and service.
