### ISSUE TITLE
Session stickiness all requests are sent to the same pod

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-alb-ingress-controller#855]
Hi, I start multiple new sessions and use kubetail to inspect the traffic and notice that only one of the pods (2 in this case) serve all the traffic.

This is an attribute I apply to my ingress controller:
```
alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=600
```

https://github.com/kubernetes/ingress-nginx/issues/3773

**Comment by khteh** [comment]
Brower debugger shows that all conversation sessions are using the same session cookie value....Is this application or the ingress controller? Puzzled.

**Comment by M00nF1sh** [comment]
@khteh 
I just verified the stickiness session works fine.(multiple targets can receive traffic as well).

How did your do your test cases? The stickiness relies on session cookie, so same brower(same cookie) will end up in always one pod. 

You can use chrome's anonymous mode to test it. Open an anoymous window, hit your url. Then close the window. And repeats 😄

**Comment by khteh** [comment]
@M00nF1sh, I am not sure if that's due to my application. I am still checking. I have the logs in https://github.com/kubernetes/ingress-nginx/issues/3773.

**Comment by khteh** [comment]
@M00nF1sh, what do you mean chrome anonymous mode? Do you refer to Incognito Window? I just checked with that and 2 different chat sessions are served by the same pod ;-(

**Comment by M00nF1sh** [comment]
Yes, the incognito window 😄 .
Are you using plain http or websocket? I can send u some curl example as well 😄 .
BTW If you only tried two chat, you should try more, and remeber to close the incognito window everytime.

**Comment by khteh** [comment]
It's plain HTTP. I just tried 5 *concurrent* chat sessions. They are all served by the same pod...
Why close browser?

**Comment by M00nF1sh** [comment]
@khteh If you don't close the browser, all incognito window share same cookie, which routes to same target 😄 

Here is a record i just did for shown how to do the testing via curl 😄 
https://asciinema.org/a/ePPwQLhI00qjlAanrmYcUMWNo

**Comment by khteh** [comment]
I test this using multiple browser windows/tabs. Every tab/windows will call `startSession` to start a new conversation session and I expect every `startSession` to be start a new session on new pod:

```
$ grep -in startsession <the saved session>
4:[iconverse-converse-0] 2019-02-19 07:45:19.291  INFO 1 --- [io-8080-exec-11] c.t.i.c.c.ConversationController         : ConversationController.startSession(); 
8:[iconverse-converse-0] 2019-02-19 07:45:19.309  INFO 1 --- [io-8080-exec-11] c.t.i.c.c.ConversationController         : startSession (preview false) 
9:[iconverse-converse-0] 2019-02-19 07:45:19.310  INFO 1 --- [io-8080-exec-11] c.t.i.c.c.ConversationController         : startSession (externalVariables null) 
79:[iconverse-converse-0] 2019-02-19 07:45:32.719  INFO 1 --- [nio-8080-exec-8] c.t.i.c.c.ConversationController         : ConversationController.startSession(); 
83:[iconverse-converse-0] 2019-02-19 07:45:32.726  INFO 1 --- [nio-8080-exec-8] c.t.i.c.c.ConversationController         : startSession (preview false) 
84:[iconverse-converse-0] 2019-02-19 07:45:32.726  INFO 1 --- [nio-8080-exec-8] c.t.i.c.c.ConversationController         : startSession (externalVariables null) 
```

**Comment by M00nF1sh** [comment]
@khteh 
I'm not sure what ```startSession``` is.
If you are using "normal mode" instead of "Incognito Window", even if you close all window after each test, all the window/tabs are sharing same cookie(AWSALB), thus they are treated as same session and routed to the same backend.

**Comment by khteh** [comment]
@M00nF1sh, this sounds to me like an issue at the client application side which receives, stores and relay the session back to the server. One question. If the client application clears the cookie in "startSession()" code, does it help in dispatching the requests to different pods by the ingress? Thanks.
