### ISSUE TITLE
Example deployment script does not match current container version

### ISSUE THREAD

**Issue by khyew** [kubernetes-sigs/aws-alb-ingress-controller#860]
The example deployment script here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/alb-ingress-controller.yaml#L69 uses the v1.1.1 tag of the ingress controller container

```
          # Repository location of the ALB Ingress Controller.
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.1
```

However the repository Makefile tags container builds with the "current" version, which it claims is v1.1.0: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/Makefile#L20

```
TAG?=v1.1.0
PREFIX?=amazon/aws-alb-ingress-controller
...
container: server
	docker build --pull -t $(PREFIX):$(TAG) .
```

Is the version mismatch here intentional or just an oversight?

**Comment by M00nF1sh** [comment]
Hi, 
It's an oversight. The latest version should be v1.1.1.
I didn't update the version(makefile/docs) when I release v1.1.1, should have some scripts or better mechanism to do releases.

**Comment by khyew** [comment]
Fixed in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/862

Closing.
