### ISSUE TITLE
Keeps requesting non-existent alb

### ISSUE THREAD

**Issue by jwsomis** [kubernetes-sigs/aws-alb-ingress-controller#868]
I really have two issues, both probably user caused. I don't think they're related though, but I'll include the second one in case it is. The primary one is that every now and then the ingress controller gets stuck in a loop trying to DescribeLoadBalancer with an ALB that doesn't exist. It can even happen after I have completely blown away the kubernetes infrastructure (all master and slave nodes and kubecfg) and recreate it. I'm not sure what triggers it. It seems like something is cached somewhere or it's finding some AWS resource that isn't cleaned up properly that makes it think there's an existing ALB, but I don't know the  inner workings 

My second issue is that I always see "no object matching key \"some/key\" in local store" whether I successfully get an ALB or not.
```
I0222 20:38:46.364207       1 :0] kubebuilder/controller "level"=0 "msg"="Starting Controller"  "controller"="alb-ingress-controller"
I0222 20:38:46.464468       1 :0] kubebuilder/controller "level"=0 "msg"="Starting workers"  "controller"="alb-ingress-controller" "worker count"=1
E0222 20:39:21.794716       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="no object matching key \"some/key\" in local store"  "controller"="alb-ingress-controller" "request"={"Namespace":"some","Name":"key"}
I0222 20:39:22.797562       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:39:52.831258       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:40:22.902004       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:40:53.102775       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:41:23.423532       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:41:53.984268       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:42:25.264962       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:42:58.529620       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:43:33.650314       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:44:12.355070       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:44:59.251744       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
E0222 20:45:29.252146       1 request_pagination.go:105] Failed request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}, Error: RequestError: send request failed
caused by: Post https://elasticloadbalancing.us-west-2.amazonaws.com/: dial tcp: i/o timeout
E0222 20:45:29.252235       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to RequestError: send request failed\ncaused by: Post https://elasticloadbalancing.us-west-2.amazonaws.com/: dial tcp: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"some","Name":"key"}
I0222 20:45:30.252727       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:46:00.296428       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:46:30.367130       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
I0222 20:47:00.539820       1 request_pagination.go:105] Request: elasticloadbalancing/DescribeLoadBalancers, Payload: {  Names: ["5fa06b5a-some-key-1363"]}
```

Any guidance appreciated?

**Comment by M00nF1sh** [comment]
Hi, 
actually i can see there are three issue:
1. `no object matching key "some/key" in local store". `
This one is fine and not actually an issue. It happens when you create service/ingress together, and we get notification about ingress first. The auto-retry handles it well.

2. `DescribeLoadBalancer with an ALB that doesn't exist` 
This happens because we cached resources ARN we created in controllers for 1 hours. (This actually hasn't cause any real issues beyonds confusing logs). I'll remove that cache in next patch release, since the cache hit rate is pretty low, and the cache implementation have memory leak bugs. 

3. `Post https://elasticloadbalancing.us-west-2.amazonaws.com/: dial tcp: i/o timeout`
This one from your logs should cause real issues. Did you breaked the outgoing connectivity from your pods(running our controller)? e.g. subnet network ACL / securityGroups on instances / nat gateway?

**Comment by jwsomis** [comment]
Good to know. For #3 I still have connectivity from that node to that endpoint. If I `curl -k https://elasticloadbalancing.us-west-2.amazonaws.com/` on the instance, I get a 302 response. Is there a shell for the container? It doesn't seem to have bash or shell for me to test it from the container itself.

**Comment by jwsomis** [comment]
Good to know. For #3 I still have connectivity from that node to that endpoint. If I `curl -k https://elasticloadbalancing.us-west-2.amazonaws.com/` on the instance, I get a 302 response. Is there a shell for the container? It doesn't seem to have bash or shell for me to test it from the container itself.

Edit: I killed the host the container was on, and everything worked on it's new host.

**Comment by jwsomis** [comment]
I think this is an intermittent issue with kube-dns being unable to resolve hostnames. I've opened a ticket with kops for this, https://github.com/kubernetes/kops/issues/6529.

**Comment by M00nF1sh** [comment]
Hi.
The ALB ingress controller don't have a shell avaiable. But you can debug the DNS issue by launch a container with shell into nodes.
Would you help throubleshoting in the following steps:
1. launch a pod
`kubectl run dnsutils --image=tutum/dnsutils -ti --rm=true  --restart=Never`
1. view DNS config in POD
`cat /etc/resolv.conf`
1. Test DNS resolve in POD
`dig +add +trace www.example.com`

**Comment by jwsomis** [comment]
The container's /etc/resolv.conf:
```
nameserver 100.64.0.10
search default.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```
dig +add +trace www.google.com
```
; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> +add +trace www.google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```
 dig +add +trace ns domain2.com (an aws hosted zone)
```
; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> +add +trace ns stage-vew-casdb-firecamp.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by M00nF1sh** [comment]
Can you confirm below
1. `100.64.0.10` is the clusterIP of your KubeDNS service?
2. the securityGroup rules on your worker node allow UDP 53 to other worker nodes?

**Comment by jwsomis** [comment]
That is the kubedns ip:
`kube-system   service/kube-dns     ClusterIP   100.64.0.10     <none>        53/UDP,53/TCP                3m`
and all traffic is open between nodes

**Comment by jwsomis** [comment]
@M00nF1sh you were right that it was. a communication issue. My NACLs weren't allowing communication between the subnets.
