### ISSUE TITLE
Provide human understandable target group names

### ISSUE THREAD

**Issue by sdavids13** [kubernetes-sigs/aws-alb-ingress-controller#870]
I would like to use CloudWatch to gather metrics dealing with various Target Groups behind an ELB but is very difficult to at-a-glance understand which Target Group is having issues due to the UUIDs/hashes being generated as the names currently. It would be nice to have some sort of configurable option to specify the name or at least a prefix to denote what Kubernetes service you are using (default value to a combination of servicer name + namespace would be nice).

**Comment by shankarramshivram** [comment]
one option is by using the  `--alb-name-prefix`,  we  get the option to prefix the alb and the target group with a useful name. the alb and target group then gets created with `<prefix-name>-......`

**Comment by M00nF1sh** [comment]
I have been planing to change the targetGroup name to k8s-{namespace:8}-{name:8}-{uuid:10}.
uuid is hash consisted of clusterName, targetType, protocol, etc.  Which should be good enough for general use cases.
(actually in my NLB PR https://github.com/kubernetes/kubernetes/pull/74910, i did that name change for NLB targetGroups).

For Ingress controller, the `--alb-name-prefix` have forbids me to do so, needs to figure out the real use case of such flag.

**Comment by sdavids13** [comment]
Is the {name} the name of the k8s service configured in the Ingress Controller? If so, that should be sufficient being able to identify what the target group is associated with.

**Comment by rverma-nikiai** [comment]
Do we have a solution for this?

**Comment by M00nF1sh** [comment]
@rverma-nikiai 
What's your ideal name for targetGroups?
Will ` k8s-{namespace:8}-{name:8}-{uuid:10}` be good enough for you?

**Comment by rverma-nikiai** [comment]
@M00nF1sh I would prefer k8-{ing/svc name}-{namespace}-{UUID:10}

**Comment by rverma-nikiai** [comment]
Also it would be nice that once we deploy the fix it should take care of deleting the existing random names and creating new target groups

**Comment by rverma-nikiai** [comment]
@M00nF1sh Looking forward to a release with this feature. Thanks

**Comment by threesquared** [comment]
Custom ALB names [are now](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1899) supported via annotations. Can this be provided for target group names as well? Or at least use the same custom ALB name when creating the target group?

**Comment by guillaumecle** [comment]
Should we create a dedicated issue for the ability to name the target group as well?
