### ISSUE TITLE
Hard to debug a 502 Bad gateway 

### ISSUE THREAD

**Issue by JoaquinScript** [kubernetes-sigs/aws-alb-ingress-controller#873]
Hey team!

I followed the guide and got a fully functional alb working with ingress to a test service. My problem appears when I change the backend to the actual service getting a 502. I've tried a lot of ways of debugging to find the issue but I haven't find it yet:

1. Works as expected creating a tunnel with port-forward.
2. Request didn't get to the service.
3. No error on the ingress logs except for the accepted: `failed to reconcile targetGroups due to failed to load serviceAnnotation due to no object matching key`

The only strange thing I could find is that checking the access logs on s3 i got a target ip not present in any of the private ips list of the ec2 instance of the eks cluster.

Can you guys please help me in further attempts to solve the problem?

**Comment by JoaquinScript** [comment]
It was an bug with the service code, disregard

**Comment by hardvintage** [comment]
> It was an bug with the service code, disregard

Hi, man, i ran into the same issue, keeping get 502 and can not get any logs from ingress, how did you solve it? Could you plz reply me?

**Comment by JoaquinScript** [comment]
Hi, I honestly don't remember exactly what I did, but you can paste your ingress yaml here and I will try to help.

**Comment by hardvintage** [comment]
> Hi, I honestly don't remember exactly what I did, but you can paste your ingress yaml here and I will try to help.

Thank you for your reply, now i fixed it. It because the 'selector' i defined in service.yaml is different from 'template.metadata.labels' in deployment.yaml , it seems the app pod(deployment)  can not be found. After i unified them , it works.
