### ISSUE TITLE
doc about WAF annotations?

### ISSUE THREAD

**Issue by RuBiCK** [kubernetes-sigs/aws-alb-ingress-controller#883]
I have set up an ALB controller and if I add WAF with AWS console, it gets removed automatically, which is the normal behavior:

 `disassociate WAF on arn:aws:elasticloadbalancing:eu-west-1:123454592251:loadbalancer/app/123461af-albpre-pr-04cd/1232640748b29123`

The problem is that I couldn't found any documentation or information about how to configure WAF with ALB ingress controller.

Is there any WAF annotations to configure WAF?

**Comment by M00nF1sh** [comment]
Hi， 
Thanks for reporting this issue.
You can use `alb.ingress.kubernetes.io/web-acl-id: yourWAFRegionalID` to configure it.
That annotation is missed from the docs, will add it 😄 .

**Comment by tdmalone** [comment]
Duplicates #608
