### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-alb-ingress-controller#892]
Hi;
   Does the ALB support HTTP/2? This is a concern since TCP connection would be held much longer compared to HTTP1.1. Does the load balancer send Alt-Svc: header when the original server is suffering from heavy load, too many streams in a single connection, for instance?

**Comment by M00nF1sh** [comment]
Hi, 
Currently ALB supports frontend HTTP/2(ALB terminates HTTP/2 traffic, and talk to backends via  HTTP/1). backend HTTP/2 support is in developing.

As for the 'Alt-Svc', I'd suggest open an support ticket to ALB team to ask for it 😄

**Comment by khteh** [comment]
Yes I have contacted support. Thanks!
