### ISSUE TITLE
[ Feature Request ] Support issuers other than ACM.

### ISSUE THREAD

**Issue by Typositoire** [kubernetes-sigs/aws-alb-ingress-controller#894]
ACM is cool.. But we use Vault and some other people also want to use Let's Encrypt. It's possible to import certificates to ACM.

**Comment by Typositoire** [comment]
Looking at the code `func (controller *defaultController) inferCertARNs(ctx context.Context, ingress *extensions.Ingress) ([]string, error) {` so if I got it right if I already have a cert for the ingress host and no ARN setup in annotations it will work ?

**Comment by Typositoire** [comment]
Yup after more code reading i'm 95% this is the case. I'll try to get cert-manager to send the certs to ACM.

**Comment by M00nF1sh** [comment]
actually i have an pending PR for this to work: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/836
The only issue blocks to merging it is ACM only allows to upload 20 certs per year by default.

**Comment by Typositoire** [comment]
What I ended up doing was creating a wildcard cert from vault and importing it in ACM. Which the controller find valid to assign it to the ALB. Only drawback is that now I have unused certificates in k8s secrets.

**Comment by Typositoire** [comment]
The ACM limit is also liftable. 
![image](https://user-images.githubusercontent.com/721017/54452744-426bb980-472c-11e9-9e4d-b163eca37adc.png)
