### ISSUE TITLE
Enable access logging for ALBs created with alb-ingress-controller

### ISSUE THREAD

**Issue by tudor** [kubernetes-sigs/aws-alb-ingress-controller#90]
Hello,

We'd like to enable access logging for ALBs that alb-ingress-controller create. We are currently doing this manually for long-running services, but it would be nice if we could configure that in alb-ingress-controller.

ALBs support logging to S3, see https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#enable-access-logging

**Comment by joshrosso** [comment]
Thanks @tudor sounds great.

Moving it to `1.1` milestone as it's not a top priority for us in `1.0`. However, @antoniobeyah has expressed some interest in taking it on. So if he has the cycles to knock it out, possible we'll see this in `1.0`.

**Comment by bigkraig** [comment]
Coming in #267
