### ISSUE TITLE
ALBs failing to get created with cross-account VPC sharing

### ISSUE THREAD

**Issue by rifelpet** [kubernetes-sigs/aws-alb-ingress-controller#901]
Hello,

I'm sharing my kubernetes cluster's subnets into another AWS account using AWS Resource Access Manager. For simplicity, the cluster runs in Account A and its subnets are being shared into account B. I'm running the aws-alb-ingress-controller with an IAM role from Account B.

I have created VPC security groups in Account B and referenced their IDs in the security-groups annotation of my ingress, however the controller is getting the following error: 

```
I0325 23:41:23.164516       1 loadbalancer.go:185] mynamespace/myingress: creating LoadBalancer myalbname
E0325 23:41:23.590978       1 loadbalancer.go:195] mynamespace/myingress: failed to create LoadBalancer myalbname due to ValidationError: A security group must be specified for creating a loadbalancer in a VPC not owned by the AWS account
E0325 23:41:23.591003       1 loadbalancer.go:195] mynamespace/myingress: 	status code: 400, request id: 7f878ea6-4f57-11e9-9118-5b0349fa58a4
E0325 23:41:23.591089       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to create LoadBalancer due to ValidationError: A security group must be specified for creating a loadbalancer in a VPC not owned by the AWS account\n\tstatus code: 400, request id: 7f878ea6-4f57-11e9-9118-5b0349fa58a4"  "controller"="alb-ingress-controller" "request"={"Namespace":"mynamespace","Name":"myingress"}
I0325 23:41:23.591153       1 recorder.go:53] kubebuilder/manager/events "level"=1 "msg"="Warning"  "message"="failed to create LoadBalancer myalbname due to ValidationError: A security group must be specified for creating a loadbalancer in a VPC not owned by the AWS account\n\tstatus code: 400, request id: 7f878ea6-4f57-11e9-9118-5b0349fa58a4" "object"={"kind":"Ingress","namespace":"mynamespace","name":"myingress","uid":"9e6370d2-4f51-11e9-9bae-12b04a19e8a8","apiVersion":"extensions/v1beta1","resourceVersion":"53354782"} "reason"="ERROR"
```

It looks like the [CreateLoadBalancer API Call](https://docs.aws.amazon.com/sdk-for-go/api/service/elbv2/#CreateLoadBalancerInput) can take a list of security groups, however the aws-alb-ingress-controller [is not providing it](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/c96b321f9c326f7d1b0ec0c6eb25a4bd7ee21a32/internal/alb/lb/loadbalancer.go#L186-L193) and instead relying on its own [security group reconciling](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/c96b321f9c326f7d1b0ec0c6eb25a4bd7ee21a32/internal/alb/sg/lb_attachment.go#L26) to set the security groups after the fact.

I realize that my setup is a bit unusual, but would it be possible for the list of security groups to be provided to the `CreateLoadBalancer` call in order to support cross account VPC sharing? I can open a PR if desired.

It may be as simple as using `ingressAnnos.LoadBalancer.SecurityGroups` in [buildLBConfig](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/c96b321f9c326f7d1b0ec0c6eb25a4bd7ee21a32/internal/alb/lb/loadbalancer.go#L299) though that wouldn't support the auto-detection logic used elsewhere. Would that be okay as a starting point?

**Comment by rverma-nikiai** [comment]
@rifelpet Started working on this https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/865 but left it unimplemented since couldn't understand the behavior of target groups. Maybe you can find relevant info here.

**Comment by rifelpet** [comment]
@rverma-nikiai I've tested my proposed fix and it works fine: https://github.com/rifelpet/aws-alb-ingress-controller/commits/shared-subnets

though it requires that security group IDs be defined in the ingress annotation rather than the auto-creation of security groups if they aren't specified as documented [here](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#access-control). I'm hoping I'll have time soon to look into what it would take to support both security group use-cases.

Given that shared subnets don't work at all currently, I would hope that this partial fix could be accepted in the short term. It will require additional testing, but I can open a PR if it is desired.

**Comment by mvillumsen** [comment]
I'm struggling to get this to work with v1.1.2. The ingress controller is deployed to a fresh EKS cluster running in shared subnets.

I'm deploying the simple Echoserver to the cluster with the following ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: alb_public_sg
    kubernetes.io/ingress.class: alb
  name: echoserver
spec:
  rules:
  - host: test.mydomain.com
    http: &echoserver_root
      paths:
      - backend:
          serviceName: echoserver
          servicePort: 80
        path: /
```

The output of the ALB Ingress Controller log:
```
I0812 13:06:21.653027       1 loadbalancer.go:185] default/echoserver: creating LoadBalancer a397cb0c-default-echoserve-3ea3
E0812 13:06:21.965220       1 loadbalancer.go:195] default/echoserver: failed to create LoadBalancer a397cb0c-default-echoserve-3ea3 due to ValidationError: A security group must be specified for creating a loadbalancer in a VPC not owned by the AWS account
E0812 13:06:21.965239       1 loadbalancer.go:195] default/echoserver: 	status code: 400, request id: fb164bf2-bd01-11e9-bf8e-2b4c11a3e5bd
E0812 13:06:21.965313       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to create LoadBalancer due to ValidationError: A security group must be specified for creating a loadbalancer in a VPC not owned by the AWS account\n\tstatus code: 400, request id: fb164bf2-bd01-11e9-bf8e-2b4c11a3e5bd"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"echoserver"}
```

I deploy the ALB Ingress Controller using Helm and kube2iam and the only args given is `cluster-name` and `ingress-class`.

Is there something I'm missing?

**Comment by jfdoube** [comment]
same issue here. Any update on this ?

**Comment by rifelpet** [comment]
Is your ALB Ingress Controller pod running with an IAM role in the account the VPC is being shared into rather than the account the VPC was initially created in?

**Comment by jfdoube** [comment]
IAM role are in the account where the cluster is deployed. So yes inside the account where the vpc is being shared

**Comment by mvillumsen** [comment]
@rifelpet Yes, iam role and security group are both in the same account as the cluster, i.e. the account the subnets are being shared with.

**Comment by jfdoube** [comment]
is this suppose to fix the issue `alb.ingress.kubernetes.io/security-groups` ?

I tried it with no luck.

**Comment by mvillumsen** [comment]
Oh wait, it looks like the PR was merged after release v1.1.2. That explains it why it's not working. 

@bigkraig @M00nF1sh Do you plan to make a new release that includes this feature before v2? If so, do you have any idea when?

**Comment by jfdoube** [comment]
@mvillumsen how did you build the new container ?

**Comment by mvillumsen** [comment]
@jfdoube Just follow the link in the readme to the instructions for building https://kubernetes-sigs.github.io/aws-alb-ingress-controller/BUILDING/

**Comment by jfdoube** [comment]
yeah did that, but had to modify makefile 😄 thanks
