### ISSUE TITLE
websocket annotation

### ISSUE THREAD

**Issue by renperez** [kubernetes-sigs/aws-alb-ingress-controller#906]
Is there a way to enable the web-socket service for this? Like an annotation? Getting an error

time="2019-04-01T19:31:09Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-04-01T19:31:09Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

**Comment by renperez** [comment]
or add a listen port to use TCP? I only see http and https

**Comment by M00nF1sh** [comment]
Hi, would you help try use mode ip by adding `alb.ingress.kubernetes.io/target-type: ip` to your ingress object? It will register pod IP as target instead of nodePort.
I haven't tested websocket yet, but i assume it requires routing traffic to same pod

**Comment by renperez** [comment]
@M00nF1sh I already have this annotation inside my manifest and it's set to IP

**Comment by moruikang** [comment]
@M00nF1sh  i have the same problem,  how can i use websocket with alb?

**Comment by garfbradaz** [comment]
@renperez : Does this help?

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/189

**Comment by angelcos** [comment]
i have the same problem.. :(

**Comment by renperez** [comment]
> @renperez : Does this help?
> 
> #189
I'm going to close this since I switched my ingress back to nginx

**Comment by vrathore18** [comment]
@renperez : are you able to fix the issue? could you please share the solution.

**Comment by renperez** [comment]
@vrathore18 nope. I ended up using nginx ingress for this particular app that requires websocket.

**Comment by vrathore18** [comment]
@renperez : could you share how you defined the ngnix ingress for websocket. I am stuck on this issue for so long

**Comment by gs-offcl** [comment]
Hi,

Below is nginx ingress annotation which does reverse proxy to external service( ( running outside k8s cluster)) with web socket connection. Are there any similar capabilities supported in alb ingress ?

**ingress.yaml**

...
nginx.org/server-snippets: |
       location /somepath/ {
          proxy_set_header Host $http_host;
          proxy_pass https://ip:port/somepath/;
          proxy_read_timeout 60m;
          client_max_body_size 0;

          # Enable websocket support
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
       }

Would really appreciate any help provided. 
Thanks.
