### ISSUE TITLE
Upgrading from 1.1.1 to 1.1.2 results in 504 response to all endpoints

### ISSUE THREAD

**Issue by sciffer** [kubernetes-sigs/aws-alb-ingress-controller#911]
I tried in-place replacement of 1.1.1 image with the 1.1.2 version and it seems like it is not working(replies with 504).
My suspicion is that it can't reach the endpoint for whatever reason (as it is waiting for a while before returning the 504 - so timeout of some sort I'm guessing).
No errors or any indication of an issues via logs/events.
On the other hand it could be that I missed something, some sort of change that will cause that.
The ingress I have looks like that:
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-xxxxxxx:xxxxxx-xxxxxxxxxxxxxxxxxxxx"
    alb.ingress.kubernetes.io/healthcheck-path: "/ping"
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/inbound-cidrs: "x.x.x.x/32,x.x.x.x/32"
spec:
  rules:
    - http:
        paths:
        - path: /*
          backend:
            serviceName: app-service
            servicePort: web

**Comment by M00nF1sh** [comment]
Hi,
One of the missing part from 1.1.2 is that there should be new iam permission needed: ec2:DescribeNetworkInterfaces. But i don't think it caused it(since there will be errors if the permission is not set).

Can you share your aws console screenshot with me? like the targets registered in targetgroup.
You can reach me on slack via @M00nF1sh  or yyyng@amazon.com

**Comment by skinney6** [comment]
I am having this same issue on alb 1.1.2. My prometheus ingress is not working but my echoserver example is. Both show:
```
HTTP :  | N/A | N/A | default: returning fixed response 404 View/edit rules
```
An all target groups use Port: 1. I don't know if that's bad but seems unusual.
