### ISSUE TITLE
`failed to reconcile securityGroup associations due to failed to get ENIs attached`, new iam policy "ec2:DescribeNetworkInterfaces" needs to be added for v1.1.2

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes-sigs/aws-alb-ingress-controller#912]
Testing v1.1.2, looks like we need to add a new iam policy for `ec2:DescribeNetworkInterfaces`
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/v1.1.2/docs/examples/iam-policy.json#L266

Otherwise I am getting 403:
```
E0404 19:22:20.909752       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to get ENIs attached to sg-072dbb6c84f6e32a8 due to UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 605ff5cb-d7a5-4d4f-a5f9-7ffd2311c9ae"  "controller"="alb-ingress-controller" "request"={"Namespace":"team-test","Name":"envoy-admin"}
```

Maybe worth mentioning this as `Action Required` in the release notes? @M00nF1sh

**Comment by M00nF1sh** [comment]
Hi, thanks for reporting this issue 😄 
This  should be in action required section and just added it in release notes 😄
