### ISSUE TITLE
Reg. HTTP Method based routing

### ISSUE THREAD

**Issue by kannananandan** [kubernetes-sigs/aws-alb-ingress-controller#916]
We have a requirement to route the same path to different targets based on the HTTP method.
On AWS ALB, there is an option to choose the HTTP method and route the request and the same works fine.
We have Ingress from where we are adding the paths and mentioning the targets, we were not able to add any http method based routing in the ingress file, however after applying the ingresses.yaml file ALB was created and we were able to add another condition for http method.
But within 10 minutes of addition of http method condition, it was removed.
Can you please advise as to what needs to be done to ensure it persists or redirect me to any material with this info.

Thank you!!

**Comment by M00nF1sh** [comment]
Hi,
The reason is that the alb ingress controller will drive the rule configuration on ALB to match k8s specification via ingress. So it cannot be supported without support it via annotation.

Would you help comment on https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/909 for your desired configuration mechanism?

**Comment by kannananandan** [comment]
Thanks a lot for the help @M00nF1sh , it worked fine
Used the second alternative mentioned with the combination of comment from Rowern, will add a comment in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/909 and close this issue

    alb.ingress.kubernetes.io/actions.api-rule-cfg-get: '{"Type": "AdvancedRouting","AdvancedRoutingConfig": {"Conditions": {"Verbs": ["get"]},"Backend": {"serviceName:app1", "servicePort":80}}}'
    alb.ingress.kubernetes.io/actions.api-rule-cfg-post: '{"Type": "AdvancedRouting","AdvancedRoutingConfig": {"Conditions": {"Verbs": ["post"]},"Backend": {"serviceName:app2", "servicePort":80}}}'
          - path: /api/*
            backend:
              serviceName: api-rule-cfg-post
              servicePort: use-annotation
          - path: /api/*
            backend:
              serviceName: api-rule-cfg-get
              servicePort: use-annotation

One additional step was to manually add the GET and POST methods as additional rules on the AWS side after deploying the Ingress file, but this time the methods stayed, thanks to the annotation
