### ISSUE TITLE
AWS rules created by aws-alb-ingress-controller are not deleted on hem delete

### ISSUE THREAD

**Issue by Heshma** [kubernetes-sigs/aws-alb-ingress-controller#921]
We are using helm packaging manager to install our application which has dependency chart of aws-alb-ingress-controller. The AWS ALB Ingress controller is a controller triggers the creation of an ALB and the necessary supporting AWS resources whenever we declare an Ingress resource on the eks cluster.

When I performed a helm delete <release>, aws alb ingress controller was removed but all AWS rules created by alb ingress controller are not deleted. The reason being that helm doesn't manage the ingress resources created by it, thus upon helm delete it doesn't remove the ingress resource.

This is adding a manual step in our infrastructure pipeline to delete the aws rules created by aws-alb-ingress-controller on declaring an ingress object. 

Expectation is that upon helm delete, all the AWS rules created by aws ingress controller should also be deleted.

**Comment by M00nF1sh** [comment]
This will be hard to implement. Since we don't have control via controller pod deletion.  
Also, it's not ideal to implement such cleanup in the controller, e.g. you can still get dangling LoadBalancers if you used service with LoadBalancerType.

Instead the automation infrastructure should explicitly delete all resources(services/ingress/namespaces) before deleting the cluster. After we added support for finalizers, the deletion on ingress will be blocked by aws resource cleanup performed by this controller.

**Comment by stevenoctopus** [comment]
I run into this issue often as we tear down our EKS cluster each night.

Do you have any suggestions on how to automate this?

When we don't use the helm chart, deleting the ingress controller deployment correctly cleans up all resources.

**Comment by M00nF1sh** [comment]
@stevenoctopus 
Deleting the ingress controller itself won't delete these resources, the ingress resources need to be deleted first.

After we add Finalizer support, the automation workflow should be like below:
1. delete all ingresses first and pull for status that all ingresses are deleted.
2. delete the ingress controller after all ingress deleted.

**Comment by stevenoctopus** [comment]
Are you sure that deleting the deployment won't clean up resources? I could have sworn before I was using the helm chart, `kubectl delete -f alb-ingress-controller.yaml` (deployment spec file) cleaned up any created resources.

Either way, with Finalizer support, will using helm delete cleanup created resources? Or will we still need to delete those manually?

**Comment by M00nF1sh** [comment]
@stevenoctopus 
Hi, i'm 100% sure that simply delete the alb-ingress-controller won't clean up any created resources 😄 .
With Finalizer support, you still need to delete Ingress resources too. But the benefit is the Ingress resource won't be deleted by APIServer unless alb-ingress-controller finished clean up resources for it.
Currently without finalizer support, when u delete the Ingress resource, it will be deleted immediately, and the clean up aws resources for that Ingress is happening asynchronously. And if you deleted the aws-alb-controller immediately after that, these resources will be left in aws account.

**Comment by stevenoctopus** [comment]
Ahh! Sorry, I was mistaken. I looked back into a previous bug that we were on together to see what I was thinking. (https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/889#issuecomment-483420004)

Deleting the ingresses themselves, not the alb-ingress-controller deployment spec. That cleans up the additional AWS resources (LoadBalancer, TargetGroups).

However, when using the helm chart, deleting the ingresses does not clean them up.

**Comment by M00nF1sh** [comment]
@stevenoctopus Would you help check the aws alb ingress controller logs when you delete the ingress? There should be something prevented it from clean up aws resources.

**Comment by stevenoctopus** [comment]
```
I0617 13:42:00.149033       1 instance_attachment.go:110] default/sws: detaching securityGroup sg-07973a8160fa0dee1 from ENI eni-0fb3e036203f768a2
rpc error: code = Unknown desc = Error: No such container: abe136f9bed1c756c1c660a4046a8c295f79302aeb7efe0e258572b7b31a4c8
```

@M00nF1sh Looks like the container gets killed while attempting cleaning up?

**Comment by stevenoctopus** [comment]
So, that was with MY helm chart (which includes alb-ingress-controller). I just tried again using the official alb-ingress-controller helm chart and saw even worse results.

I didn't even see an attempt to clean up before the container was deleted.

**Comment by stevenoctopus** [comment]
Scratch that. Don't think I was giving things enough time to cleanup and my nodes were just shutting down.

I now sleep for ~15-20 seconds after I destroy my ingress for everything to be cleaned up and seems like it's all working correctly on my end.
