### ISSUE TITLE
Additional rule features.

### ISSUE THREAD

**Issue by echoboomer** [kubernetes-sigs/aws-alb-ingress-controller#925]
Is it possible at this time, or would it be possible to add rule conditions for things like `source IP` or other features in this list?
![image](https://user-images.githubusercontent.com/19732751/56387944-b3066a00-61f3-11e9-8b20-027540042653.png)

The use case is that we have a master rule for Cognito auth and we'd like to disable auth for a specific IP address, but I don't see a way to do this as configured. Thoughts?

**Comment by M00nF1sh** [comment]
Hi, It's not supported for now.
These are three alternative design for add support for this feature, would you help vote one in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/909?

**Comment by clhlc** [comment]
+1
