### ISSUE TITLE
Health Checks do not work if using multiple pods on routes

### ISSUE THREAD

**Issue by owenhaynes** [kubernetes-sigs/aws-alb-ingress-controller#93]
e.g

  - host: test.com
    http:
      paths:
      - path: "/api/*"
        backend:
          serviceName: api
          servicePort: 80
      - path: "/*"
        backend:
          serviceName: frontend
          servicePort: 80

You can only set one health-check on the ingress so if service api does not have the same route for a health check as frontend you get a unable system

**Comment by owenhaynes** [comment]
Maybe do what the google ingress controller does and use the health checks of the pods?

**Comment by bigkraig** [comment]
Do you have any ideas of how you would like to see it configured?

**Comment by gauravarora** [comment]
@bigkraig I believe annotations on the service would be the easiest way.

**Comment by sundryp** [comment]
All annotations to configure a listener should be done on the service the k8s way.

See SSL support on AWS here:  https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws

**Comment by bigkraig** [comment]
@sundryp I've got this covered for the annotations that would effect a TG. Some of the other annotations in your list didn't apply on service resources.

@owenhaynes hopefully this helps!
```
alb.ingress.kubernetes.io/backend-protocol
alb.ingress.kubernetes.io/healthcheck-interval-seconds
alb.ingress.kubernetes.io/healthcheck-path
alb.ingress.kubernetes.io/healthcheck-port
alb.ingress.kubernetes.io/healthcheck-protocol
alb.ingress.kubernetes.io/healthcheck-timeout-seconds
alb.ingress.kubernetes.io/healthy-threshold-count
alb.ingress.kubernetes.io/unhealthy-threshold-count
alb.ingress.kubernetes.io/successCodes
```

**Comment by pperzyna** [comment]
@joshrosso 
Can we expect a solution?

**Comment by bigkraig** [comment]
Supported as of #423, please use `1.0-beta.2` or later. thanks!

**Comment by AdeOpe** [comment]
Works brilliantly 
All i needed to do was move the following from my ingress to my Service definition of the app

    alb.ingress.kubernetes.io/healthcheck-path: "/svc/status"
    alb.ingress.kubernetes.io/successCodes: "200"
