### ISSUE TITLE
Conflict when create NLB or ELB

### ISSUE THREAD

**Issue by hieu29791** [kubernetes-sigs/aws-alb-ingress-controller#933]
Hi,
I follow with topic https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/761. But in my case still have error when I create NLB LoadBalancer. 
Step I reproduce:
1. Change image in controller yaml file from **v1.0.0** to **docker.io/amazon/aws-alb-ingress-controller:v1.1.2**
2. Apply service with **nlb** type
Error show as following:

> Normal   EnsuringLoadBalancer        2m (x16 over 52m)  service-controller  Ensuring load balancer
>   Warning  CreatingLoadBalancerFailed  2m (x2 over 17m)   service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service orderer/orderer0-nlb: Multiple tagged security groups found for instance i-0d88ace8226ab8535; ensure only the k8s security group is tagged; the tagged groups were sg-0e733ae14051d3209(instance-1c4539a7-utop-utopexplorer-8e38) sg-0f45fd1a625bb2d8c(instance-1c4539a7-akc-loyalstardapp-e14b) sg-03ae04bb851644f55(instance-1c4539a7-aia-aiadappingres-6d11) sg-057d9d4cc45535f19(instance-1c4539a7-fsoft-fsoftdappin-ba5c) sg-08030b76d6f6ed45c(instance-1c4539a7-grafana-grafanain-6d45) sg-0b0439880e625c158(instance-1c4539a7-ctc-ctcdappingres-a518) sg-04cd2f2b83f1cc4b8(instance-1c4539a7-utop-utopdappingr-2945) sg-0b1d920752e05ad1b(instance-1c4539a7-frt-frtdappingres-de4f) sg-0bc5cb17f0951d754
>

**Comment by M00nF1sh** [comment]
hi,
The v1.1.2 controllers need more IAM permissions that v1.1.0. You need to grant [these IAM permissions](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/iam-policy.json) to your worker node's instance role.
You can view the controller logs via
```
kubectl logs -f $(kubectl get pods -n kube-system | grep alb-ingress-controller | grep Running | awk '{print $1}') -n kube-system
```
If there are no error message shown after you granted these IAM permissions, it will automatically solve the tag conflict for you.

BTW, you can check the tags on one of the securityGroup, e.g. `instance-1c4539a7-utop-utopexplorer-8e38`. (aws console->ec2->securityGroups-> tags)

**Comment by hieu29791** [comment]
> hi,
> The v1.1.2 controllers need more IAM permissions that v1.1.0. You need to grant [these IAM permissions](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/iam-policy.json) to your worker node's instance role.
> You can view the controller logs via
> 
> ```
> kubectl logs -f $(kubectl get pods -n kube-system | grep alb-ingress-controller | grep Running | awk '{print $1}') -n kube-system
> ```
> 
> If there are no error message shown after you granted these IAM permissions, it will automatically solve the tag conflict for you.
> 
> BTW, you can check the tags on one of the securityGroup, e.g. `instance-1c4539a7-utop-utopexplorer-8e38`. (aws console->ec2->securityGroups-> tags)

I try it and work like a charm, thank you.
BTW, you have any documents or Q&A about new version release, so I can check on it before asking new question

**Comment by M00nF1sh** [comment]
@hieu29791 
Hi, you can find all required actions for upgrades in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases 😄.
However, we do missing a centralized upgrade instructions, will create one 😄
