### ISSUE TITLE
single node/master failure with failed to reconcile securityGroup associations due to failed to get cluster ENIs due to failed to get instances within cluster due to MissingParameter: The request must contain the parameter InstanceId

### ISSUE THREAD

**Issue by barshow** [kubernetes-sigs/aws-alb-ingress-controller#934]
with a single master node running as a dev server the ingress controller wont consider the master node.

This is what it looks like in the logs

```I0510 22:25:30.492000       1 request_pagination.go:105] Request: ec2/DescribeInstances, Payload: {  InstanceIds: []}
E0510 22:25:30.502902       1 request_pagination.go:105] Failed request: ec2/DescribeInstances, Payload: {  InstanceIds: []}, Error: MissingParameter: The request must contain the parameter InstanceId
	status code: 400, request id: cbd69f87-0b09-4530-9056-63bd61385f3c
E0510 22:25:30.502981       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to get cluster ENIs due to failed to get instances within cluster due to MissingParameter: The request must contain the parameter InstanceId\n\tstatus code: 400, request id: cbd69f87-0b09-4530-9056-63bd61385f3c"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"dr-ingress"}
```

And this is the problem line
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/internal/ingress/annotations/class/main.go#L35

Deleting that master tag check fixes the issue for me, but I'm not sure if there are any unintended consequences by doing that.

**Comment by M00nF1sh** [comment]
Hi, this is intentionally to keep in-sync with how k8s handles LB node pool: 
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L602
Ideally single master nodes can be changed to be able to registered as LB node as well. But why use an LB if there is only an worker node 😄
