### ISSUE TITLE
ALB is not created on aws console.

### ISSUE THREAD

**Issue by hardvintage** [kubernetes-sigs/aws-alb-ingress-controller#939]
Hello, I am using iam role to provision alb. This is the log:

-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    v1.1.2
  Build:      git-cc1c5971
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller.git
-------------------------------------------------------------------------------

W0519 16:27:13.686085       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0519 16:27:13.728732       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null}}}
I0519 16:27:13.729001       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
I0519 16:27:13.729084       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"=
I0519 16:27:13.729289       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
I0519 16:27:13.729332       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"=
I0519 16:27:13.729528       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null}}}
I0519 16:27:13.729771       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"","osImage":"","containerRuntimeVersion":"","kubeletVersion":"","kubeProxyVersion":"","operatingSystem":"","architecture":""}}}}
I0519 16:27:13.730794       1 leaderelection.go:205] attempting to acquire leader lease  kube-system/ingress-controller-leader-alb...
I0519 16:27:29.852655       1 leaderelection.go:214] successfully acquired lease kube-system/ingress-controller-leader-alb
I0519 16:27:29.953214       1 :0] kubebuilder/controller "level"=0 "msg"="Starting Controller"  "controller"="alb-ingress-controller"
I0519 16:27:30.053530       1 :0] kubebuilder/controller "level"=0 "msg"="Starting workers"  "controller"="alb-ingress-controller" "worker count"=1

Plz help take a look. Thanks

**Comment by M00nF1sh** [comment]
Hi, can u check whether the ingress contains the "kubernetes.io/ingress.class: alb" annotation?
u should use `kubectl get ingress/youringress -n namespace`. If your yaml file have some syntax(e.g. unquoted number) errors, kubectl apply will lose annotations.

**Comment by hardvintage** [comment]
Thanks for your reply man!

The reason why alb can not be created is because my nodes ec2 is t3.micro which only supports 4 pods.

I have two nodes and already set up 8 pods, so the alb can not be created…..

Descibe pods

Events:

  Type     Reason            Age                 From               Message

  ----     ------            ----                ----               -------

  Warning  FailedScheduling  17s (x18 over 14m)  default-scheduler  0/2 nodes are available: 2 Insufficient pods.Capacity:

Descibe nodes

cpu:                2

 ephemeral-storage:  20959212Ki

 hugepages-1Gi:      0

 hugepages-2Mi:      0

 memory:             982504Ki

 pods:               4


Have a good day!

 原始邮件
发件人: M00nF1sh<notifications@github.com>
收件人: kubernetes-sigs/aws-alb-ingress-controller<aws-alb-ingress-controller@noreply.github.com>
抄送: jizheng<hardvintage@hotmail.com>; Author<author@noreply.github.com>
发送时间: 2019年5月24日(周五) 15:51
主题: Re: [kubernetes-sigs/aws-alb-ingress-controller] ALB is not createdon aws console. (#939)


Hi, can u check whether the ingress contains the "kubernetes.io/ingress.class: alb" annotation?
u should use kubectl get ingress/youringress -n namespace. If your yaml file have some syntax(e.g. unquoted number) errors, kubectl apply will lose annotations.

**Comment by hardvintage** [comment]
Hi, after i added a new node, the capacity issue was solved. But i still got the same log from "kubectl -n kube-system logs -f alb-ingress-controller-586f59cc6-q97fq". I am sure i have no syntax error in the config. When i run "kubectl describe ing/inventory-ingress -n kube-system" , i got this log:

> Name:             inventory-ingress
Namespace:        kube-system
Address:
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host              Path  Backends
  ----              ----  --------
  inventory.mte.io
                    /   aws-inventory:80 (<none>)
Annotations:
  alb.ingress.kubernetes.io/listen-ports:            [{"HTTP": 80}]
  alb.ingress.kubernetes.io/scheme:                  internet-facing
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/listen-ports":"[{\"HTTP\": 80}]","alb.ingress.kubernetes.io/scheme":"internet-facing","kubernetetes.io/ingress.class":"alb"},"labels":{"app":"inventory-ingress"},"name":"inventory-ingress","namespace":"kube-system"},"spec":{"rules":[{"host":"inventory.mte.io","http":{"paths":[{"backend":{"serviceName":"aws-inventory","servicePort":80},"path":"/"}]}}]}}

  kubernetetes.io/ingress.class:  alb
Events:                           <none>

> 
And there is no pod created for ingress inventory-ingress, can you take a look for me plz?

**Comment by hardvintage** [comment]
> Hi, can u check whether the ingress contains the "kubernetes.io/ingress.class: alb" annotation?
> u should use `kubectl get ingress/youringress -n namespace`. If your yaml file have some syntax(e.g. unquoted number) errors, kubectl apply will lose annotations.

Hi, after i added a new node, the capacity issue was solved. But i still got the same log from "kubectl -n kube-system logs -f alb-ingress-controller-586f59cc6-q97fq". I am sure i have no syntax error in the config. When i run "kubectl describe ing/inventory-ingress -n kube-system" , i got this log:


Name: inventory-ingress
Namespace: kube-system
Address:
Default backend: default-http-backend:80 ()
Rules:
Host Path Backends

inventory.mte.io
/ aws-inventory:80 ()
Annotations:
alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}]
alb.ingress.kubernetes.io/scheme: internet-facing
kubectl.kubernetes.io/last-applied-configuration: {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/listen-ports":"[{"HTTP": 80}]","alb.ingress.kubernetes.io/scheme":"internet-facing","kubernetetes.io/ingress.class":"alb"},"labels":{"app":"inventory-ingress"},"name":"inventory-ingress","namespace":"kube-system"},"spec":{"rules":[{"host":"inventory.mte.io","http":{"paths":[{"backend":{"serviceName":"aws-inventory","servicePort":80},"path":"/"}]}}]}}

kubernetetes.io/ingress.class: alb
Events:

And there is no pod created for ingress inventory-ingress, can you take a look for me plz?

**Comment by hardvintage** [comment]
> Hi, can u check whether the ingress contains the "kubernetes.io/ingress.class: alb" annotation?
> u should use `kubectl get ingress/youringress -n namespace`. If your yaml file have some syntax(e.g. unquoted number) errors, kubectl apply will lose annotations.

Hi, after i added a new node, the capacity issue was solved. But i still got the same log from "kubectl -n kube-system logs -f alb-ingress-controller-586f59cc6-q97fq". I am sure i have no syntax error in the config. When i run "kubectl describe ing/inventory-ingress -n kube-system" , i got this log:
`Name: inventory-ingress
Namespace: kube-system
Address:
Default backend: default-http-backend:80 ()
Rules:
Host Path Backends

inventory.mte.io
/ aws-inventory:80 ()
Annotations:
alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}]
alb.ingress.kubernetes.io/scheme: internet-facing
kubectl.kubernetes.io/last-applied-configuration: {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/listen-ports":"[{"HTTP": 80}]","alb.ingress.kubernetes.io/scheme":"internet-facing","kubernetetes.io/ingress.class":"alb"},"labels":{"app":"inventory-ingress"},"name":"inventory-ingress","namespace":"kube-system"},"spec":{"rules":[{"host":"inventory.mte.io","http":{"paths":[{"backend":{"serviceName":"aws-inventory","servicePort":80},"path":"/"}]}}]}}

kubernetetes.io/ingress.class: alb
Events: <none>
`

And there is no pod created for ingress inventory-ingress, can you take a look for me plz?

**Comment by hardvintage** [comment]
> Hi, can u check whether the ingress contains the "kubernetes.io/ingress.class: alb" annotation?
> u should use `kubectl get ingress/youringress -n namespace`. If your yaml file have some syntax(e.g. unquoted number) errors, kubectl apply will lose annotations.

Hi, after i added a new node, the capacity issue was solved. But i still got the same log from "kubectl -n kube-system logs -f alb-ingress-controller-586f59cc6-q97fq". I am sure i have no syntax error in the config. When i run "kubectl describe ing/inventory-ingress -n kube-system" , i got this log:
···
Name: inventory-ingress
Namespace: kube-system
Address:
Default backend: default-http-backend:80 ()
Rules:
Host Path Backends

inventory.mte.io
/ aws-inventory:80 ()
Annotations:
alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}]
alb.ingress.kubernetes.io/scheme: internet-facing
kubectl.kubernetes.io/last-applied-configuration: {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/listen-ports":"[{"HTTP": 80}]","alb.ingress.kubernetes.io/scheme":"internet-facing","kubernetetes.io/ingress.class":"alb"},"labels":{"app":"inventory-ingress"},"name":"inventory-ingress","namespace":"kube-system"},"spec":{"rules":[{"host":"inventory.mte.io","http":{"paths":[{"backend":{"serviceName":"aws-inventory","servicePort":80},"path":"/"}]}}]}}

kubernetetes.io/ingress.class: alb
Events: 
···

And there is no pod created for ingress inventory-ingress, can you take a look for me plz?

**Comment by hardvintage** [comment]
> Hi, can u check whether the ingress contains the "kubernetes.io/ingress.class: alb" annotation?
> u should use `kubectl get ingress/youringress -n namespace`. If your yaml file have some syntax(e.g. unquoted number) errors, kubectl apply will lose annotations.

Hi, after i added a new node, the capacity issue was solved. But i still got the same log from "kubectl -n kube-system logs -f alb-ingress-controller-586f59cc6-q97fq". I am sure i have no syntax error in the config. When i run "kubectl describe ing/inventory-ingress -n kube-system" , i got this log:
```
Name: inventory-ingress
Namespace: kube-system
Address:
Default backend: default-http-backend:80 ()
Rules:
Host Path Backends

inventory.mte.io
/ aws-inventory:80 ()
Annotations:
alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}]
alb.ingress.kubernetes.io/scheme: internet-facing
kubectl.kubernetes.io/last-applied-configuration: {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/listen-ports":"[{"HTTP": 80}]","alb.ingress.kubernetes.io/scheme":"internet-facing","kubernetetes.io/ingress.class":"alb"},"labels":{"app":"inventory-ingress"},"name":"inventory-ingress","namespace":"kube-system"},"spec":{"rules":[{"host":"inventory.mte.io","http":{"paths":[{"backend":{"serviceName":"aws-inventory","servicePort":80},"path":"/"}]}}]}}

kubernetetes.io/ingress.class: alb
Events: <none>
```

And there is no pod created for ingress inventory-ingress, can you take a look for me plz?

**Comment by philtrep** [comment]
@hardvintage did you ever figure it out?

**Comment by hardvintage** [comment]
Yes i did, my friend. The reason was told in my last mail.

 原始邮件
发件人: Philippe Trépanier<notifications@github.com>
收件人: kubernetes-sigs/aws-alb-ingress-controller<aws-alb-ingress-controller@noreply.github.com>
抄送: jizheng<hardvintage@hotmail.com>; Mention<mention@noreply.github.com>
发送时间: 2019年7月23日(周二) 04:25
主题: Re: [kubernetes-sigs/aws-alb-ingress-controller] ALB is not createdon aws console. (#939)


@hardvintage<https://github.com/hardvintage> did you ever figure it out?
