### ISSUE TITLE
Add support for security group auto discovery

### ISSUE THREAD

**Issue by precompiler** [kubernetes-sigs/aws-alb-ingress-controller#940]
Currently, tagged subnets can be auto discovered - https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery

Is it possible to auto discover tagged security groups?

**Comment by errordeveloper** [comment]
/kind feature

At the moment there is not such functionality, but lookup by name is possible. So if you use deterministic security names, you can avoid having to pass IDs around. But perhaps auto-discovery would be still a good idea to implement.

**Comment by precompiler** [comment]
> /kind feature
> 
> At the moment there is not such functionality, but lookup by name is possible. So if you use deterministic security names, you can avoid having to pass IDs around. But perhaps auto-discovery would be still a good idea to implement.

Thanks a lot Ilya @errordeveloper
