### ISSUE TITLE
Naming prefix for alb resources

### ISSUE THREAD

**Issue by rdubya16** [kubernetes-sigs/aws-alb-ingress-controller#941]
Is it possible to support a naming prefix or custom name for created alb resources? This would allow us to lock down the IAM permissions given to the container to a specific namespace with wildcards.

**Comment by M00nF1sh** [comment]
Hi, Is it possible to use tag-based iam permission for your use case? 
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_iam-tags.html

we have planed to tag resources with standard set of tags starting from next release(v1.1.3)

**Comment by cameronattard** [comment]
We would also like to set predictable ALB names so we can do Terraform data source lookups against the ALBs.

**Comment by patrickdean** [comment]
Does this not already exist? 

It doesn't seem documented, but there is an option in the code for "[alb-name-prefix](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/15dba892b51115f59e79a1815e29fbd89c6acfe6/internal/ingress/controller/config/config.go#L75)"

I added it to my alb-ingress-controller deployment and it seems to do the trick.

**Comment by maur1th** [comment]
`alb-name-prefix` appears to be an option on the controller. I think it should be an annotation instead so it's possible to change it depending on the service the ingress gives access to.
