### ISSUE TITLE
IP mode load balancing

### ISSUE THREAD

**Issue by syst0m** [kubernetes-sigs/aws-alb-ingress-controller#946]
How does load balancing actually work when using the IP mode for the traffic mode?
Where do you define the IPs of the pods for the controller to direct traffic to?

**Comment by M00nF1sh** [comment]
Hi, when you use IP mode. The pod IP will be registered directly as targets.
So if you are using AWS_EKS_CNI, pod IPs are powered by ENI on worker nodes, the traffic will be routed to ENIs on worker nodes(where pod is located) directly, and then routed to the pod(container).

If you are using kubenet(only works with custom-managed securityGroup under IP mode currently), pod IP is virtual IP powered by VPC routetable. The traffic will be routed to the primary ENI on worker nodes(where pod is located) directly, and then routed to the pod(container)

**Comment by syst0m** [comment]
Right, that all makes sense.
However, I'm wondering where do you specify to which pods is the traffic routed to?
How does the controller know to which pod IPs it's supposed to direct traffic?
I couldn't find an example or a related annotation in the documentation.

**Comment by M00nF1sh** [comment]
hi, sorry for the late reply.
for every service object, there is an corresponding `endpoint` object(with same name as service) that contains all backend pod IP & ports 😄

**Comment by syst0m** [comment]
Ok, thanks for the clarification. :)

**Comment by tibin-mfl** [comment]
Hi @M00nF1sh , In this case, when we use IP mode, when a request comes from the client through the ALB will that not hit the service?
