### ISSUE TITLE
Error with targetgroup targets

### ISSUE THREAD

**Issue by Erokos** [kubernetes-sigs/aws-alb-ingress-controller#951]
Hi,
we're having a similar issue as described by jitesh-prajapati123. Similar in a way that we have an EKS cluster (created and described using Terraform as is the rest of our infrastructure) and wanted to set up an ALB using the aws alb ingress controller. We were following the steps carefully as described by the documentation and our public and private subnets have the necessary tags specified for deploying an external (internet facing) ALB.

Our worker nodes are in private subnets and security groups have been setup correctly in order for the cluster to successfully deploy our services. This has been verified. We've also created the ingressController-iam-policy and attched it to the worker nodes.

When executing this command:

    kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o "alb-ingress[a-zA-Z0-9-]+")

the first line from the logs:

    client_config.go:549] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.

The last lines where any errors are:

    kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to reconcile targetGroup targets due to Unable to find the default/echo service: no object matching key "default/echo" in local store" "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"api"}

we've deployed the following ingress:

`
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: api
annotations:
kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/scheme: internet-facing
alb.ingress.kubernetes.io/target-type: instance
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
alb.ingress.kubernetes.io/success-codes: '200,404'
spec:
tls:

    hosts:
        <my_host_domain>
        rules:
    host: <my_host_domain>
    http:
    paths:
        path: /echo
        backend:
        serviceName: echo
        servicePort: 80`

the following deployment and NodePort type service:

`
apiVersion: apps/v1
kind: Deployment
metadata:
name: echo
labels:
app: echo
spec:
replicas: 2
selector:
matchLabels:
app: echo
template:
metadata:
labels:
app: echo
spec:
containers:
- name: echo
image: 064211542743.dkr.ecr.eu-west-1.amazonaws.com/echo-api:1.0
ports:
- containerPort: 8080

apiVersion: v1
kind: Service
metadata:
name: echo
spec:
type: NodePort
selector:
app: echo
ports:

    port: 80
    targetPort: 8080
    protocol: TCP`

We're testing this using this command:
curl -XPOST 'http://<my_host_domain>/echo/echo' -d '{"data": {"Hello": "World"}}' but it keeps hanging.
It also hangs when using
curl -XPOST 'http://<cluster-ip>:<nodeport>/echo/echo' -d '{"data": {"Hello": "World"}}'

Does anyone have a suggestion? Any help would be greatly appreciated

**Comment by Erokos** [comment]
We've also set the environment variable AWS_VPC_K8S_CNI_EXTERNALSNAT to true on the aws-node DaemonSet since our workers are running in a private subnet and use a NAT gateway in a private subnet to access the internet. 

Now we don't see that error anymore but our services are still unreachable becauste the command still hangs when executed.

We can see in the aws dashboard, the load balancer successfully created and the registered targets now. Is it somehow related to the fact that our service doesn't have a different namespace and it therefore uses the default?
It seems as though the load balancer is configured correctly and somehow the problem happens inside the cluster...Help? :)

**Comment by M00nF1sh** [comment]
Hi, have you setup DNS that map the <my_host_domain> to the <ALB_DNS>?
You can find the ALB_DNS by using `kubectl get ingress/api`.

Currently, the ALB_DNS won't configure the DNS mapping above, you can [use controllers like 'external-dns' to configure it for you](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/external-dns/setup/)


BTW, if you access ALB_DNS directly, you will get 404 page since you specified ingress.spec.host, which enforces you to access the LB that hostname specifed.

**Comment by Erokos** [comment]
Hi,
thanks for the reply, I executed this command:

**nslookup <my_host_domain>**

and get this output:

`Non-authoritative answer:
<my_host_domain>	canonical name = ALB_DNS.
Name:	738f35ae-default-api-518c-745805557.eu-west-1.elb.amazonaws.com ...`

it looks to me that it's configured correctly.
Executing the command you suggested also confirms it. I don't know what's wrong...

**Comment by M00nF1sh** [comment]
@Erokos 
Hi, would you share your accountId/region/clusterName to me(yyyng@amazon.com)? I can take a look.
it's doesn't matter if it's route53 or other domain provider.

**Comment by Erokos** [comment]
Hi,
thanks for the offer, I've sent you the requested info along with my configuration files, any help is much appreciated.
BR

**Comment by Erokos** [comment]
Hi,

we've been messing around with this issue and managed to have some progress. We relied on the subnet autodiscovery through the use of tags as I've already mentioned.

Poking around the ALB on the AWS dashboard we noticed that under availability zones it had two subnets listed, both of them private. By deleting the ingress yaml file and thus deleting the ALB and then applying the edited ingress in which we hardcoded the public subnets in the annotations, the newly created ALB seems to work. We'll run further tests but what bothers me is why was it created in the private subnets in the first place and why did it not work?

**Comment by Erokos** [comment]
Hi,
I think we can close this issue, the remaining problem is specifiying the routing rules, as you could've seen in the files I've sent you, in the api ingress yaml file I'm trying to do something like this:

`
spec:
 rules:
 - host: <my.domain.com>
   http:
     paths:
       - path: /echo/*
         backend:
           serviceName: echo
           servicePort: 80
`
we have a service called echo for which we want our requests to get to whenever we send them to <my.domain.com>/echo/* , the star represents everything after the echo prefix that we want to get into our pod of the service.
The mentioned example doesn't work but does anyone have suggestion on how to make it work? :)

**Comment by M00nF1sh** [comment]
Hi,
I tested via the dns in your ingress, and it works. 
When you specified host: <my.domain.com>, you have to access your ALB via <my.domain.com> instead of directly access the ALB_generated_Domain. This can be achieved by
* setup DNS to point my.domain.com to ALB_generated_Domain(via cname or alias in route53), and can be automated via controllers like external-dns.
* manually modify /etc/hosts to point <my.domain.com> to ip address behind ALB_generated_Domain
* mutate the HOST header to <my.domain.com> send to ALB_generated_Domain via brower plugins.

BTW, in your application, i got "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", that error message is came from your app, make sure your app can deal with traffic with path "/echo/", since ALB currently doesn't do path-rewrite.

**Comment by Erokos** [comment]
Hi,
thanks for your time, much appreciated :)

BR
