### ISSUE TITLE
ALB is not created in aws 

### ISSUE THREAD

**Issue by anup1384** [kubernetes-sigs/aws-alb-ingress-controller#956]
I'm getting an error while running below command-
#kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o "alb-ingress[a-zA-Z0-9-]+")**
 
1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to retrieval of subnets failed to resolve 2 qualified subnets. Subnets must contain the kubernetes.io/cluster/\u003ccluster name\u003e tag with a value of shared or owned and the kubernetes.io/role/internal-elb tag signifying it should be used for ALBs Additionally, there must be at least 2 subnets with unique availability zones as required by ALBs. Either tag subnets to meet this requirement or use the subnets annotation on the ingress resource to explicitly call out what subnets to use for ALB creation. The subnets that did resolve were []"  "Controller"="alb-ingress-controller" "Request"={"Namespace":"2048-game","Name":"2048-ingress"}

#kubectl get ingress/2048-ingress -n 2048-game
NAME           HOSTS   ADDRESS   PORTS   AGE
2048-ingress   *                                     80      81s

**Comment by karancode** [comment]
Does you subnets have below tags for your subnet : 
```
kubernetes.io/cluster/{cluster_name} : shared/owned
kubernetes.io/role/internal-elb   : 1 (or ``)  (for internal)
kubernetes.io/role/elb  : 1 (or ``) (for internet-facing)
```
You can use ingress annotation as well.
Reference : https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery
