### ISSUE TITLE
Allow wildcard routing in host

### ISSUE THREAD

**Issue by ashish4github** [kubernetes-sigs/aws-alb-ingress-controller#960]
We are implementing a SaaS based solution and need service calls for all subdomains to be routed to a same service.  For example, both below service calls from browser should be touted to service.

tenanta.example.com/service1, 
tenantb.example.com/ service1

How can I achieve this with single ingress resource? We tried using the host entry as *.example.com but that did not work.

As per the https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md this feature is supported in most of teh ingress controller and widely used; and thus proposed to be added to spec.

Is there any plan to support this for alb-ingress controller?

**Comment by tareksamni** [comment]
I'm interested in such a feature as well 🤞

**Comment by ashish4github** [comment]
@M00nF1sh Is there any chance this will be picked up in next release you are planning?

**Comment by M00nF1sh** [comment]
@ashish4github i'm take a look at this, and i'm actually surprised if this it not supported already...

**Comment by M00nF1sh** [comment]
@ashish4github This is already supported. 
Just one tip, u should **quote** the host like "tenant*.example.com"  :D, if you use * in yaml, you need to quote it 😄
