### ISSUE TITLE
Feature Request: Support rate limiting

### ISSUE THREAD

**Issue by ashish4github** [kubernetes-sigs/aws-alb-ingress-controller#964]
Need ability to rate limi the API calls based on the IP similar to one provided by nginx.

Did not find any annotation to support this ability. Is there a way this can be done today?

Below is the nginx link for rate limiting for reference:

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting

**Comment by s1rc** [comment]
I feel like this should be default functionality for an ingress.

**Comment by mariocandela** [comment]
> I feel like this should be default functionality for an ingress.

+1
