### ISSUE TITLE
Ability to 

### ISSUE THREAD

**Issue by streetmapp** [kubernetes-sigs/aws-alb-ingress-controller#966]
Similar to [this issue](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/746), wanting the ability to **disable** the controller from managing certain components. 

For example, we are using AWS Firewall Manager to handle automatic WAF association on our ALBs based on tags. However, since we don't do an explicit apply of Web ACL in the ALB ingress definition, the ingress controller will disassociate the Web ACL that was applied by the Firewall manager. 

So having the ability to turn off certain components from being managed by the ingress controller would be helpful if we are already handling their configuration in another location.

**Comment by M00nF1sh** [comment]
Hi
For WAF, you can disable it by add an args to the alb-ingress-controller deployment:
```
--feature-gates=waf=false
```
We can extends the support to other features as well, if there are valid use cases :D
