### ISSUE TITLE
local environment

### ISSUE THREAD

**Issue by mjhaller** [kubernetes-sigs/aws-alb-ingress-controller#974]
Has anyone tried to address environment parity with local using this ingress controller?  Nginx ingress controllers can at least be run locally in `minikube`.  Is there an approach to running this ingress controller locally via some kind of mock or fake?

**Comment by karancode** [comment]
(just curious) what will you achieve by running it with mock/fake endpoints? 
I think the whole point behind this ingress it get you an alb readily created.

**Comment by mjhaller** [comment]
my question probably wasn't very clear.  just like the cloud provider code creates an ELB when you use a load balancer type on the nginx ingress controller, an ALB would be created by this ingress controller.  I was just wondering about how i think about this controller running locally - independent of AWS.  I guess i was thinking of some kind of mapping of the cloud-provider functionality into the minikube environment.  Seems pretty challenging, as you'd need some kind of local version of an ALB.  And, I believe `localstack` is not goign to help here - https://github.com/localstack/localstack/issues/25

hope my quest seems clearer.   i think it probably is just not an intention for this to run locally.  most of the annotations don't make sense outside of aws.

**Comment by marcosdiez** [comment]
I solved this using helm charts, which allow us to have `if`s in the YAML files.
