### ISSUE TITLE
Support for Cognito/OIDC Client Credentials Grant 

### ISSUE THREAD

**Issue by flythebluesky** [kubernetes-sigs/aws-alb-ingress-controller#975]
Client Credentials Grant (i.e. sending JWT Authorization Bearer access_token in the header) is not supported. We were hoping to use ALB + Cognito for some API microservices but this will not be possible without Client Credentials support. 

See:
https://tools.ietf.org/html/rfc6749#section-4.4
https://tools.ietf.org/html/rfc6750#section-6.1.1
https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/ (bottom of page)

**Comment by flythebluesky** [comment]
I ended up creating an OAuth2 proxy to get total control of the auth flows without having to depend on the LB.

**Comment by binarymist** [comment]
Can you elaborate @flythebluesky ?

**Comment by casey-robertson-paypal** [comment]
I know this is really old @flythebluesky but as far as I can tell this still isn't possible?

**Comment by andrewhharmon** [comment]
it seems possible now. can we revisit this?
 https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-verify-jwt.html
