### ISSUE TITLE
Static IP addresses for alb

### ISSUE THREAD

**Issue by mattjs** [kubernetes-sigs/aws-alb-ingress-controller#977]
Is it possible to get a static IP instead of a url when using the ingress controller?

**Comment by michcio1234** [comment]
@mattjs since you closed the issue, do you have answer to that question? Could you share it?

**Comment by M00nF1sh** [comment]
@michcio1234 
You can manually setup an globalAccelerator in front of ALB to get a static IPAddress. (This will incur additional cost if you don't benefit from the cross-region Acceleration)
I believe ALB will rollout static IP support at some time. (not official)
