### ISSUE TITLE
Single ALB in Version 1.0.1, but not working in 1.1.2

### ISSUE THREAD

**Issue by npolagani** [kubernetes-sigs/aws-alb-ingress-controller#984]
I was able to use one ALB for multiple Ingress Resources (from one namespace) in Version 1.0.1.  I did create a new EKS cluster and installed Version 1.1.2, which is creating a new ALB for each Ingress Resource (from same namespace), which is severely limiting our ability to use AWS Ingress Controller.  Is there anyway that we could use same ALB in 1.1.2 ? or as I read I just need to wait for new release 1.1.3 ?

**Comment by tdmalone** [comment]
^ cross-posted at https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/724#issuecomment-517113838, https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/228#issuecomment-517112339
