### ISSUE TITLE
Inability to restrict secret viewing on controller

### ISSUE THREAD

**Issue by davidhao3300** [kubernetes-sigs/aws-alb-ingress-controller#999]
We'd like to not let the ALB controller see all of the secrets in our cluster. It appears that this is used only for the OIDC functionality, so we understand that doing so will make OIDC nonfunctional for us. Can we add a flag to disable secret watching so that we can use the rest of the controller functionality?

**Comment by davidhao3300** [comment]
Restricting secret watching results in the controller looping on
`E0812 23:27:00.798060       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20181213151034-8d9ed539ba31+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:ingress:alb-ingress-controller" cannot list resource "secrets" in API group "" at the cluster scope`

**Comment by dudicoco** [comment]
@davidhao3300 I was able to partially workaround this by giving the controller only list and watch permissions, so at least it can't read the secrets contents.

@M00nF1sh I think that it is too permissive to give this kind of permissions to the controller, can we do something about it please?

**Comment by jbg** [comment]
This is a legitimate bug and should be re-opened, please @M00nF1sh?

The installation YAML gives `aws-load-balancer-controller` access to read every secret in the entire cluster, which is obviously against any sensible policy of granting least necessary permission.

**Comment by jbg** [comment]
@dudicoco `list` still allows reading the secret contents.

This is resolved in v2.4.1, FYI.

**Comment by dudicoco** [comment]
@jbg are you sure `list` allows to read the secrets contents?

I believe `list` allows you to see all of the resources in the namespace while `get` allows you to see the contents of the resources.

**Comment by jbg** [comment]
No, `list` is for retrieving a collection including full object content. You can test it out yourself pretty easily, just give a service account list permission on secrets and then retrieve a list of secrets from the API server.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb

**Comment by dokuboyejo** [comment]
@jbg  Thanks ...confirmed fix in `2.4.1`
